### ISSUE TITLE
bug: "Show code" on a schedule's page does not work for flows

### ISSUE THREAD

**Issue by jaller94** [windmill-labs/windmill#1028]
### Describe the bug

The "Show code" button only works if one selected a Script. It does not work for a Flow.

![Screenshot 2022-12-18 at 17-42-18 New Schedule Windmill](https://user-images.githubusercontent.com/10872136/208309449-f1e3cb74-476b-44c5-bc09-cfd49c271cad.png)

### To reproduce

1. Go to [New Schedule](https://app.windmill.dev/schedule/add) or open the page of an existing Flow
2. Click on "Flow" to have a flow to be triggered by the schedule.
3. Select any flow.
4. Click on "Show code".
5. See error

### Expected behavior

It should have looked for a flow with that path, not a script.

### Screenshots

![Screenshot_2022-12-18_17-47-14](https://user-images.githubusercontent.com/10872136/208309594-75fa04c9-0cd2-41b8-8e51-22eb19de8f9b.png)

### Application version

Windmill v1.55.0-53-g398c109a

**Comment by rubenfiszel** [comment]
fixed
