### ISSUE TITLE
feature: Editor console auto-scroll down

### ISSUE THREAD

**Issue by rossmccrann** [windmill-labs/windmill#104]
It would be great if the editor console could automatically scroll down with the page rather than having to manually expand and close it to see further content.

<img width="1100" alt="Screenshot 2022-06-07 at 10 32 28" src="https://user-images.githubusercontent.com/43697404/172406846-69499cde-906a-4e42-8d2c-acbcf559ce0c.png">
---
---
---
<img width="1018" alt="Screenshot 2022-06-07 at 10 20 33" src="https://user-images.githubusercontent.com/43697404/172404154-edbefa43-fc57-43ab-ad71-fed026b82f14.png">

**Comment by rubenfiszel** [comment]
Done
