### ISSUE TITLE
feature: Airtable will drop support for api key in Jan 24

### ISSUE THREAD

**Issue by fatonramadani** [windmill-labs/windmill#1137]
<img width="843" alt="Screenshot 2023-01-20 at 15 15 55" src="https://user-images.githubusercontent.com/456655/213719623-c158ca3b-ca89-44d7-93a5-91647b251cb2.png">

https://airtable.com/developers/web/api/authentication#types-of-token

**Comment by rubenfiszel** [comment]
@fatonramadani I think we just have to migrate the instruction to point to PAT. Can I add this to your backlog ?

**Comment by fatonramadani** [comment]
@rubenfiszel Yes, will do

**Comment by gautamprikshit1** [comment]
Can't seem to find the relative instructions
