### ISSUE TITLE
bug: missing hub flows

### ISSUE THREAD

**Issue by a0m0rajab** [windmill-labs/windmill#1156]
### Describe the bug

The hub flows button is missed in the script/flow picker in the App: 
![image](https://user-images.githubusercontent.com/18273833/214468502-b5319b4b-b957-4919-9e1b-56b0a78eb78d.png)

### To reproduce

1. Go to 'App creator.'
2. insert result
3. go to settings -> compute 

### Expected behavior

To have Hub Flows button

**Comment by a0m0rajab** [comment]
The location of the related code: 
https://github.com/windmill-labs/windmill/blob/main/frontend/src/lib/components/apps/editor/settingsPanel/mainInput/RunnableSelector.svelte#L62

Meanwhile, would not it be better if we had those three functions as one function with two parameters (path, type) passed from the buttons?
![image](https://user-images.githubusercontent.com/18273833/214468904-33f94b94-9bb8-4726-a79d-ad61d946c77f.png)

**Comment by rubenfiszel** [comment]
It's intended, flows are not generic enough to be imported straight to apps
