### ISSUE TITLE
bug: cannot create OAuth resource connecting to Keycloak

### ISSUE THREAD

**Issue by martinrlilja** [windmill-labs/windmill#1162]
### Describe the bug

I tried to create an OAuth resource that connects to Keycloak, but in the last step, after connecting I get an error when saving it. The error seems to be coming from `/api/w/[workspace]/oauth/create_account`.

I think it is because the `refresh_token` field on `account` has a limit of 255 charactes but the refresh token from Keycloak is just under 700 characters long (a JWT). Maybe a limit closer to `variable.value` would be preferable?

### To reproduce

1. Add an oauth provider that creates large refresh tokens, such as Keycloak to `oauth.json`.
2. From the resources tab click Add a resource/API.
3. Select the custom oauth API and click Connect.
4. Click Save after logging in to the oauth provider.
5. See error `Internal: creating account in [workspace]: error returned from database: value too long for type character varying(255)`

### Expected behavior

There shouldn't be any issues saving a 700 bytes long refresh token. :)

### Browser information

Firefox

### Application version

1.60.0

**Comment by rubenfiszel** [comment]
Thanks for the report, should be able to do a migration fix today. Curious about your keycloak config!

**Comment by rubenfiszel** [comment]
@martinrlilja in latest commit, a migration increase the token size limit to VARCHAR 1500, lmk if that worked for you

**Comment by martinrlilja** [comment]
Thanks for the quick response! It worked flawlessly.

This is the config I use for Keycloak:

```json
{
    "keycloak_<realm>": {
        "id": "...",
        "secret": "...",
        "connect_config": {
            "auth_url": "https://.../realms/<realm>/protocol/openid-connect/auth",
            "token_url": "https://.../realms/<realm>/protocol/openid-connect/token",
            "scopes": ["openid", "offline_access"]
        }
    }
}
```

**Comment by rubenfiszel** [comment]
Thanks, I added your snippets to our docs: https://docs.windmill.dev/docs/how-tos/setup_oauth
