### ISSUE TITLE
bug: cannot demote user from admin permissions in workspace

### ISSUE THREAD

**Issue by martinrlilja** [windmill-labs/windmill#1167]
### Describe the bug

After adding a new user to a workspace and making them admins, I cannot change their permissions to anything else. I am still signed in as the old user when changing their permissions.

### To reproduce

1. Go to Workspace settings
2. Add a new user as an admin or change an existing user to admin.
3. Try to change their permissions to Opertor or Admin.
4. See error "Admins cannot be demoted by themselves, ask another admin to demote you".

### Expected behavior

I should be able to change the permissions of other users after making them admins.

### Screenshots

![demote-user-bug](https://user-images.githubusercontent.com/1858564/215758840-1ffa70d1-dc19-41ab-af47-d3c317bf5c1b.png)

### Application version

v1.60.0-173-gf377c84f

### Additional Context

A similar feature would be nice so that the last super user cannot remove super user status from themselves.

**Comment by rubenfiszel** [comment]
Thanks for the report.
Fixed in a2ed69f8
