### ISSUE TITLE
feature: allow periods and @ in usernames

### ISSUE THREAD

**Issue by unreality** [windmill-labs/windmill#1172]
Many organisations use 'user.name' or even 'user.name@domain.com' as usernames, it would be nice if the database constraint allowed these.

**Comment by rubenfiszel** [comment]
The main reason for those constraints is to promote easy to use usernames that will make most paths, easy to read paths. Is this a problem that you are facing yourself within your organization ?

I think periods are a fair thing to allow but having full emails as usernames might be a bit much. On the other hand, it seems a bit of an arbitrary constraint I would agree. I will add it as a Todo

**Comment by antrix** [comment]
Sorry for raising this on an old issue but was this change actually completed? Are periods now allowed in usernames? If so, can you share which version onwards this change is supported?

**Comment by rubenfiszel** [comment]
For now this is a won't do @antrix
