### ISSUE TITLE
bug: Connect Workspace to Slack results in Sql Error

### ISSUE THREAD

**Issue by NReilingh** [windmill-labs/windmill#1193]
### Describe the bug

When attempting to handle the callback after authorizing a workspace to connect to slack, I get a database constraint error:

```
windmill-db-1     | 2023-02-09 23:59:57.771 UTC [588] ERROR:  null value in column "display_name" of relation "folder" violates not-null constraint
windmill-db-1     | 2023-02-09 23:59:57.771 UTC [588] DETAIL:  Failing row contains (slack_bot, my-workspace, null, {}, {}).
windmill-db-1     | 2023-02-09 23:59:57.771 UTC [588] STATEMENT:  INSERT INTO folder
windmill-db-1     |                   (workspace_id, name, owners, extra_perms)
windmill-db-1     |                   VALUES ($1, $2, $3, $4) ON CONFLICT DO NOTHING
```

`windmill-windmill_server-1  | 2023-02-09T23:59:57.772766Z ERROR request: windmill_common::error: error="Sql error: error returned from database: null value in column \"display_name\" of relation \"folder\" violates not-null constraint" method=POST uri=/api/w/fisher-center/oauth/connect_slack_callback username="admin" email="admin@windmill.dev" workspace_id="my-workspace"`

I did a naive search of the codebase and came up with this snippet, which appears to be the only INSERT INTO FOLDER statement I can find that omits `display_name`:

https://github.com/windmill-labs/windmill/blob/b03b3be154efb0984f9623c27acc05617f125bc5/backend/sqlx-data.json#L5142

### To reproduce

1. Create a new Slack app, retain the Client ID and Client Secret, and store them in an `oauth.json` file.
2. Run a local Windmill instance from the sample `docker-compose.yml`, and mount the `oauth.json` file into `/usr/src/app/oauth.json` of the windmill_server container.
3. In Workspace settings, Slack Command tab, click Connect to Slack, and grant permission in the Slack OAuth page that opens.
4. Flow is redirected back to Windmill, and a red error pop-up appears in the top right hand corner.

### Expected behavior

No error will appear, and instead the slack connection will be completed.

### Screenshots

<img width="1093" alt="image" src="https://user-images.githubusercontent.com/2458645/217968144-9f2a0f4c-a08b-48a6-9b5a-9b54f0433ea2.png">

<img width="1451" alt="image" src="https://user-images.githubusercontent.com/2458645/217968059-6517af10-4149-4b3e-bd5f-9eb0db4ef62d.png">

### Browser information

Safari 16.3 (18614.4.6.1.5)

### Application version

Windmill v1.62.0-26-gc8f0e23e

### Additional Context

I was originally testing this using ngrok to proxy my locally-running docker compose stack to the public internet with TLS, so I don't know if the repro is exactly accurate. If the line of code I referenced isn't immediately obvious that there's a missing database migration or constraint error, let me know and I can provide more specific steps to setting up the compose stack and Slack app.

**Comment by rubenfiszel** [comment]
Thanks for the report @NReilingh . In latest commit, it's highly likely to have been fixed but will test more thoroughly tomorrow.

**Comment by rubenfiszel** [comment]
Tested and it is fixed
