### ISSUE TITLE
bug: Website link to "Self-host yourself" leads to 404

### ISSUE THREAD

**Issue by GwynHannay** [windmill-labs/windmill#1195]
### Describe the bug

Hiya. :-)

Just wanted to give you the heads up that the link on the main docs page to "Self-host yourself" leads to a page that no longer exists.

### To reproduce

1. Go to https://docs.windmill.dev
2. Click on link "Self-host yourself" next to the button "Try Windmill Cloud".
3. This leads to the page https://docs.windmill.dev/docs/how-tos/self_host
4. See error "Page Not Found".

### Expected behavior

You'll need to find where that page has gone and link it again.

**Comment by rubenfiszel** [comment]
Just fixed, thank you very much for the report!
