### ISSUE TITLE
bug: Stuck in a flow preview page.

### ISSUE THREAD

**Issue by cesaryuan** [windmill-labs/windmill#1235]
### Describe the bug

When trying to preview a flow named "A very simple flow to showcase for-loops", UI will get stuck after some interactions.

### To reproduce

1. Go to 'Hub Flow'
2. Click on 'A very simple flow to showcase for-loops' to preview it
3. Click 'Flow Input"
4. Page gets stuck.

### Expected behavior

No stuck.

### Screenshots

https://user-images.githubusercontent.com/35998162/221344191-ebd6a588-3a0a-4c4e-a338-4356998a49bd.mp4

### Browser information

Chromium 102.0.5005.167

### Application version

Windmill v1.69.3

**Comment by rubenfiszel** [comment]
Thanks for the bug report, I'm on it.

**Comment by rubenfiszel** [comment]
Fixed on e1f686d
