### ISSUE TITLE
bug: Bad request: slack client not setup

### ISSUE THREAD

**Issue by ateliershen** [windmill-labs/windmill#1262]
### Describe the bug

Hi, I was following the tutorial here (https://docs.windmill.dev/blog/connect-slack-with-windmill) and tried to connect Windmill to my Slack channel.

But as long as I clicked on "Connect to Slack", 

![CleanShot 2023-03-06 at 17 24 45@2x](https://user-images.githubusercontent.com/30176935/223070169-9b3b834f-0a50-42eb-a730-19e6ad8e1487.jpg)

It throws the error "Bad request: slack client not setup".

![CleanShot 2023-03-06 at 17 25 17@2x](https://user-images.githubusercontent.com/30176935/223070581-28411310-c343-4e59-8bc8-bd70b5948995.jpg)

Is there anything I should do before clicking on the button? Thank you.

### To reproduce

1. Go to "/workspace_settings"
2. Click on "Connect to Slack"
3. See error: Bad request: slack client not setup

### Expected behavior

Should be redirected to the Slack OAuth page.

### Screenshots

![CleanShot 2023-03-06 at 17 25 17@2x](https://user-images.githubusercontent.com/30176935/223070142-b3dafe52-b359-49d1-b863-9e404c1e7c73.jpg)

### Application version

ghcr.io/windmill-labs/windmill:1.71

**Comment by rubenfiszel** [comment]
Hi @ateliershen,

Indeed you need to setup a slack app: https://api.slack.com/apps?new_app=1 and then add the client id and client secret following the same format as for the google instructions on: https://docs.windmill.dev/docs/advanced/setup_oauth/

**Comment by rubenfiszel** [comment]
I wrote more information here:
https://docs.windmill.dev/docs/advanced/setup_oauth/

**Comment by ateliershen** [comment]
Hi @rubenfiszel ,

Thanks for the prompt response!

My app was set up with https://easypanel.io/ so I don't have direct access to the .yaml file or the root folder. It's from the app template. 

I cannot defend my lack of Docker knowledge here, but please consider making OAuth configurable via "/workspace_settings" on the web. Sometimes the platform admin might not be the developer who set up the instance.

If this makes sense I can create a feature request for this. Thank you!

**Comment by rubenfiszel** [comment]
@ateliershen I think easypanel supports docker file directly which mean one could likely build a custom one that takes windmill as `FROM` and then copy the oauth.json file at the right place. The reason for requiring a file is that the file is then read at start and kept in memory for fast access. Doing it configurable through the db would mean a db read access for a lot of requests. There might be a better way to do this.

Would you be willing to share the steps needed right now to deploy on easypanel ? I'd be keen to add it to the windmill documentaiton.

**Comment by ateliershen** [comment]
Hi @rubenfiszel ,

Sure, I created a short screencast to demonstrate how to install Windmill on easypanel: https://gofile.io/d/lq6MC4

Steps:
1. Create a Project
2. Select Windmill from the app template 
3. Add the domain for this Windmill instance (and set up the DNS)
4. Wait for it to spin up
5. Navigate to the domain and log in with default credentials

I hope this helps!
