### ISSUE TITLE
feature: Search run by payload content/header

### ISSUE THREAD

**Issue by saidhasyim** [windmill-labs/windmill#1271]
The ability to search the run by payload content. For now, whenever I need to inspect a specific transaction, I will open using the flow name, one by one. I may have >20 at time close to each other. Or if it is easier, I can also get the source system to pass some identifier in the “Header” (if that makes the search less resource intensive) before POST-ing to our webhook, whichever makes more sense to you.

**Comment by rubenfiszel** [comment]
I think we can definitely do a search feature that takes a list of arbitrary field from the args and allow `==, >=, <=, ~=` on them.
