### ISSUE TITLE
In-Flow script editor

### ISSUE THREAD

**Issue by rubenfiszel** [windmill-labs/windmill#130]
Currently when building flows, and the script needed for a particular step does not exist yet, an user has to iterate separately on the script, save and go back and forth with the flows.

A much better UX would be to allow for edition and embedding of scripts directly in the flow builder. The embedded script editor must have an option to save permanently the script

**Comment by fatonramadani** [comment]
Done in https://github.com/windmill-labs/windmill/pull/175
