### ISSUE TITLE
bug: Messy right panel when adding flow step property

### ISSUE THREAD

**Issue by vidz1979** [windmill-labs/windmill#1320]
### Describe the bug

Right panel get messy when adding flow step property. View the video for better understanding.

### To reproduce

1. Go to Editing a flow
2. Click on flow's Input and Add Property
3. See error

### Expected behavior

The screen appear correctly drawed.

### Screenshots

https://user-images.githubusercontent.com/5623041/226965564-27c9f7d1-c0ae-4966-a47c-d3f6d9d1a006.mov

### Browser information

Chrome on Mac and Windows

### Application version

Windmill v1.80.1-2-gbfb5c1b5

**Comment by rubenfiszel** [comment]
Fixed in latest commit
