### ISSUE TITLE
bug: no built-in resource types for self hosted Windmill

### ISSUE THREAD

**Issue by NiklasRosenstein** [windmill-labs/windmill#1347]
### Describe the bug

The documentation appears to imply that Windmill comes with a number of predefined resource types.

https://docs.windmill.dev/docs/core_concepts/resources_and_types

However, the self-hosted Windmill instance I just spun up doesn't have those.

I'm deploying the latest Windmill helm chart (1.0.2):

```hcl
resource "helm_release" "windmill" {
  provider   = helm.k0s_main
  name       = "windmill"
  namespace  = "default"
  repository = "https://windmill-labs.github.io/windmill-helm-charts/"
  chart      = "windmill"
  values = [<<-EOF
    windmill:
      baseUrl: https://windmill.nkl.st
      enableOauth: true
      oauthConfig: |
        {
          "google": {
            "id": "REDACTED",
            "secret": ${jsonencode(data.vault_generic_secret.windmill.data["google_oauth_client_secret"])}
          }
        }
    EOF
  ]
}
```

### To reproduce

1. Deploy Windmill 1.0.2 using Helm to Kubernetes
2. Join the Demo project
3. Create a new Resource

### Expected behavior

Windmill comes with the default resource types, or provides steps to install them.

### Screenshots

![image](https://user-images.githubusercontent.com/1318438/229256133-a4938bab-8e6a-484a-823f-468ae95b87b7.png)

**Comment by rubenfiszel** [comment]
I think you're on an old version of the windmill because we hadn't updated the helm charts in a while. Could you try upgrading the helm charts to 1.1.0. You should then see an app setup prompt which will make you sync with the latest resource types from the hub.

**Comment by rubenfiszel** [comment]
On the top-right of the login screen, you should be able to see the version. Latest is:

![image](https://user-images.githubusercontent.com/275584/229271051-8180987b-d8d3-4163-b17f-7e3789d354cb.png)

If the setup screen doesn't appear, you should go to the special admins workspace:

![image](https://user-images.githubusercontent.com/275584/229271042-12adb194-a121-4754-8132-9d4730adf0cc.png)

And then you can run the script to sync once or go to the app setup to set it up as a schedule:
![image](https://user-images.githubusercontent.com/275584/229271030-68a4215b-f1b2-4064-bbeb-2bf7266dfaff.png)

**Comment by NiklasRosenstein** [comment]
Hey @rubenfiszel, thanks I've tried that and got Windmill `v1.84.1-9-g492f2252`. Unfortunately it still didn't show the built-in resources.

The issue is probably that I never logged in as the admin user but immediately connected to Windmill using OAuth! After logging in as admin I found this screen:

![image](https://user-images.githubusercontent.com/1318438/229347410-1de3c3c2-3610-4627-8364-f413ed6d7056.png)

And after following the setup steps, I've now got the built-in resource types available. 😃

**Comment by rubenfiszel** [comment]
@NiklasRosenstein Glad to know,

just a note that if you were to deploy this with a set of users that are non superadmins, you will want to deploy latest which contains this improvement: https://github.com/windmill-labs/windmill/commit/492f22526ac018efba961b88eebd823eb2c4f415

It will ensure that those users do not need to wait 60s for their permisions to apply a newly created folders which can be a bad experience. (the reason being, cache staleness)

Also feel free to join our Discord, we're super responsive in there :)

https://discord.com/invite/V7PM2YHsPB

**Comment by marcolussetti** [comment]
@rubenfiszel It seems like this same behaviour is occurring in `v1.103.0-13-g133adefc` (latest available via docker-compose), despite going through the setup.

No resource types loaded on new workspaces, the `superusers` workspace, or the `demo` workspace. The `starter` workspace has PostgreSQL and Slack.

**Comment by rubenfiszel** [comment]
@marcolussetti I tried to reproduce on a fresh docker-compose and I couldn't. Could you go to the superadmins workspace and run the sync script ?

**Comment by marcolussetti** [comment]
@rubenfiszel Thank you for such a quick reply, this is what I got on running it.

```

Expanded Result

{
    "error": {
        "name": "ExecutionErr",
        "message": "ExitCode: 1, last log lines:
error: Expected a JavaScript or TypeScript module, but identified a Unknown module. Importing these types of modules is currently not supported.
  Specifier: https://x.nest.land/arithmetic4@0.1.1/mod.ts
    at https://deno.land/x/fonction@v1.8.0-beta.7/src/constants/index.ts:2:19"
    }
}
```

I have now deleted deleted the volumes, did a docker-compose pull, rebuilt everything. It appears to work well now. I wonder if it's at all possible that my experimenting a little bit before I run that script caused the issue? I think I created a few workspaces, attempted to create a script, etc.
