### ISSUE TITLE
bug:

### ISSUE THREAD

**Issue by jaller94** [windmill-labs/windmill#1369]
### Describe the bug

When switching the disabled/enabled status of a flow and re-opening the edit modal, it still shows the previous status.

In the screenshot below, the schedule is enabled but in the modal it looks like it's still disabled:

![Screenshot](https://user-images.githubusercontent.com/10872136/230151238-dc61a267-4146-4c18-806f-635b91c44693.png)

### To reproduce

1. Go to a flow page (must have a primary schedule)
2. Click on 'Edit schedule'
3. Change the status of the schedule from disabled to enabled or the other way around.
4. Click 'Save'
5. Note, the toggle on the flow page updated itself correctly.
6. Click on 'Edit schedule' again.

### Expected behavior

The "Edit schedule" modal shows the correct status on consecutive openings.

### Screenshots

![Peek 2023-04-05 18-54](https://user-images.githubusercontent.com/10872136/230151848-b2eebb5c-520e-4da8-b18a-9722cffc5fb6.gif)

### Browser information

Mozilla Firefox 111.0.1

### Application version

Windmill v1.85.0-23-g8c727227

**Comment by rubenfiszel** [comment]
Fixed in latest commit, thanks for the issue!
