### ISSUE TITLE
feature: Add PowerShell execution support to Windmill

### ISSUE THREAD

**Issue by pcgeek86** [windmill-labs/windmill#1435]
I write a lot of PowerShell code to automate various tasks. It would be great if Windmill included the ability to run PowerShell scripts. PowerShell is object-oriented and much more powerful than simple Bash scripts.

Both AWS Lambda and Azure Functions (FaaS) support PowerShell as a runtime.

Here are some common tasks that someone might perform with PowerShell scripts:

* Deploy AWS CloudFormation templates as stacks
* Deploy Microsoft Azure cloud resources
* Run filesystem clean-up scripts on a cron schedule
* Stop / start services when necessary
* Run uptime monitors (ICMP, DNS, HTTPS, SSH, etc.)
* Call REST APIs against external services (ie. self-hosted GitLab servers, GitHub, Airtable, Baserow, etc.)

**Comment by rubenfiszel** [comment]
That's a great idea and likely not too hard given that pwshell seems to be installable on alpine linux as an interpreter: https://github.com/PowerShell/PowerShell/releases/download/v7.3.4/powershell-7.3.4-linux-alpine-x64.tar.gz

I do not have the bandwidth right now to add it but will get to it in a few weeks and would review any contribution towards it

**Comment by pcgeek86** [comment]
PowerShell is available as a Linux container image as well. It's as easy as this to run it:

```
docker run --rm -it mcr.microsoft.com/powershell
```

**Comment by jeremylcarter** [comment]
Will this indirectly allow small amounts of .NET classes to be invoked as well? As PowerShell can interop with .NET.

For example `[System.Math]::Sqrt(36)`

**Comment by pcgeek86** [comment]
Yes, power shell is built on.net and you can invoke most .NET methods and instantiate classes from PowerShell.

In fact, you can even load additional .NET assemblies into PowerShell. A lot of people, myself included, use PowerShell more like a .NET scripting language. It's crazy what you can do with PS.

**Comment by rubenfiszel** [comment]
Since this issue got a bit more popularity, we will prioritize it, expect some updates next week :)

**Comment by jeremylcarter** [comment]
How can we help out? If I can understand the PowerShell integration process I would like to then tinker with full .NET integration. Very excited 😊

**Comment by dharmatech** [comment]
Saw the post about this project on HN. When I read that y'all support multiple languages, my thoughts went straight to PowerShell. So glad to see that y'all are considering it!

**Comment by pcgeek86** [comment]
Getting ready to trial Windmill soon. Any news on PowerShell script support? 🙂

**Comment by pcgeek86** [comment]
Added a temporary work-around here: https://hub.windmill.dev/scripts/powershell/1612/run-powershell-(pwsh)-script-powershell#406

Works great on my self-hosted Windmill server.

**Comment by rubenfiszel** [comment]
powershell is now part of the default windmill image and one of the proposed template. The only TODO left is to add support on the monaco editor instead of wrapping with bash

**Comment by HugoCasa** [comment]
powershell now natively supported #2025
