### ISSUE TITLE
feature: warn when closing the editor with unsaved changes

### ISSUE THREAD

**Issue by gustavopch** [windmill-labs/windmill#1447]
Basically, `window.addEventListener('beforeunload', ...)` warning that changes will be lost.

**Comment by rubenfiszel** [comment]
Changes are not lost, you can go back to that page. The content is stored in history

**Comment by gustavopch** [comment]
Hmm, I had lost some changes and was able to recover going back in the tab history. Still, it seems to me a confirmation dialog would be helpful. It could even mention that it's possible to restore the changes by traversing the history. Something like:

> You have unsaved to changes. If you leave the page, you can restore them by using the browser back button. Want to leave the page?

I think it would be valuable because that behavior is not obvious and many users could lose changes without understanding they could easily restore them. In fact, that's what was going to happen to me now if you didn't explain. 😅

**Comment by gustavopch** [comment]
BTW, I recovered the code in the editor by going back, but the "Save" button was grayed out. Had to copy the code, go back to Home and open the script, paste to replace and then save.

**Comment by rubenfiszel** [comment]
done
