### ISSUE TITLE
bug: workflow shared folder not persisting data

### ISSUE THREAD

**Issue by murunwas** [windmill-labs/windmill#1478]
### Describe the bug

data store in shared folder cleared every time the workflow finish running.

how to persist data such as images and csv files to shared folder that I can also access them every time workflow/script run?

### To reproduce

every time I run this workflow,`./shared` folder is always empty.

![image](https://user-images.githubusercontent.com/8838943/234382489-d4718298-d91d-4b27-89df-35dca0ef888d.png)

### Expected behavior

to persist data downloaded/uploaded such as templates and csv files

**Comment by rubenfiszel** [comment]
Not sure I would qualify this as a bug since it's intended. To persist images and csv, I would use a data storage layer such as s3. You can also store things as resources if they are small enough to be held as blob storage.
