### ISSUE TITLE
bug: App become unresponsive/freeze when expand button is clicked

### ISSUE THREAD

**Issue by murunwas** [windmill-labs/windmill#1481]
### Describe the bug

I created a script that return large json data, when I click expand button the whole app become unresponsive/freeze as shown on image below.

![image](https://user-images.githubusercontent.com/8838943/234669257-5dad7933-9fe2-4661-8ce0-64d999d6a9af.png)

### To reproduce

as described above

### Expected behavior

to view json or show friendly message

### Screenshots

![image](https://user-images.githubusercontent.com/8838943/234669653-4b55d18c-095a-4762-9b02-3f6bee044d2f.png)

**Comment by rubenfiszel** [comment]
This is now fixed
