### ISSUE TITLE
bug: Bash script arguments with default value ignore custom input values

### ISSUE THREAD

**Issue by mwa** [windmill-labs/windmill#1489]
### Describe the bug

Any custom input values are ignored when setting a default value for an argument in a Bash script. The argument value is always set to its default value.

### To reproduce

1. Create a new script for language _Bash_
2. Insert example script:
    ```bash
    a="$1"
    b="${2:-default b}"
    c="${3:-default c}"

    echo "a: $a"
    echo "b: $b"
    echo "c: $c"
    ```
3. Fill in custom argument values:
    * a: `aaa`
    * b: `bbb`
    * c: `ccc`
4. Run _Test_
5. Output is
    ```
    a: aaa
    b: default b
    c: default c
    ```

### Expected behavior

All arguments should be set to their input value, or their default if blank

The output of the above script should be:
```
a: aaa
b: bbb
c: ccc
```

### Browser information

Firefox 112.0.2 (64-Bit)

### Application version

Windmill v1.89.0 in Docker image `ghcr.io/windmill-labs/windmill:1.89.0`

**Comment by rubenfiszel** [comment]
![image](https://user-images.githubusercontent.com/275584/235263583-ac12aa56-2dea-492e-b8e6-19f2c6138620.png)
I cannot reproduce for some reasons.

**Comment by rubenfiszel** [comment]
@mwa do you have any idea ? Could you reproduce on app.windmill.dev ?

**Comment by mwa** [comment]
@rubenfiszel I cannot reproduce this behaviour on app.windmill.dev either.

While debugging, we discovered that our custom Windmill worker container inadvertently used an older Windmill version v1.69.3, which did not yet forward the default bash script arguments. The error seems to have been caused by this version mismatch.

After updating the worker to v1.89.0 everything now works as expected.
