### ISSUE TITLE
bug: first time experience does not seem to work

### ISSUE THREAD

**Issue by xrd** [windmill-labs/windmill#1565]
### Describe the bug

I installed a self-hosted version of windmill. It takes me to the login page, but does not allow me to create or login. I cannot find a default user.

https://mywindmill.xxxx.com/user/login?rd=%2Fuser%2Ffirst-time

I tried to hit /user/first-time. The screen flashes, and then redirects me back to the login screen.

Related: https://github.com/windmill-labs/windmill/pull/1194/files

### To reproduce

1. Go to the main windmill url
2. It redirects to /user/login
3. No credentials work

### Expected behavior

Should permit me to access a setup screen.

### Browser information

Firefox 102.6 EST

### Application version

v1.100.1-1-ge64f0e98

### Additional Context

Used the docker-compose image:  ghcr.io/windmill-labs/windmill:main

**Comment by rubenfiszel** [comment]
Default user is admin@windmill.dev / changeme. It should be in the README and every self-host instructions.

**Comment by dbi1** [comment]
Hello,

I followed the install instructions, and am getting the caddy basic auth popup asking for credentials, which seems correct.

However, the default credentials from the install docs and also above (admin@windmill.dev / changeme) don't seem to work, it keeps bringing up the auth popup.

The only difference between standard install instructions and my instance are that I set the port to 5678 in the .env file:
`CADDY_REVERSE_PROXY=":5678"`

Thank you for any help and for building windmill!

**Comment by rubenfiszel** [comment]
You shouldn't get the basic auth popup so something is wrong there. Could you try without modification and then tweak caddy later ?

**Comment by dbi1** [comment]
Sorry, very embarrassing, had another container running on that port.. Thanks for the quick reply!

**Comment by dbi1** [comment]
Got it up and running per standard instructions, works great on port 80 (i.e. without changing anything).

I did -independently of the above, on a brand new server- have an issue getting it to run on port 5678.

The issue came from ports 80 and 443 being hardcoded in the docker-compose.yml file, in the caddy section. Deleting those, and adding 5678:5678 instead seems to fix the issue.
