### ISSUE TITLE
feature: document react/vue/svelte app import

### ISSUE THREAD

**Issue by binarytide** [windmill-labs/windmill#1569]

**Comment by rubenfiszel** [comment]
Will do tomorrow but essentially it is using such a template: https://github.com/windmill-labs/windmill-react-template that configures vite to build iife bundle as an output and then import that bundle directly. We will provide templates for svelte, vue, vanillaJS as well as adding raw apps to the CLI sync capabilities.

**Comment by rubenfiszel** [comment]
Here is a v0 of that documentation. We are still missing the templates for all kind of frameworks but they are fairly easy to build and we will do them in one batch.
