### ISSUE TITLE
feature: ability to use variables in forms

### ISSUE THREAD

**Issue by hialvaro** [windmill-labs/windmill#1596]
when creating an app, I would like to be able to set a default value from the selected table as the field default value for a form. something like this:

![](https://i.imgur.com/jQ6Hdfh.png)

Another good option would be to be able to set default values for runables inputs:

![](https://i.imgur.com/fL2wuSS.png)

In this case, I would like the `name` field to have a default value of the selected row if there is no user input.

**Comment by rubenfiszel** [comment]
Currently you can do this by making the form a compute and computing dynamically the schema. It's not as convenient as the UI builder but it will work.

**Comment by hialvaro** [comment]
Huh, I don't really see how could I do that, is there any example?

**Comment by hialvaro** [comment]
Awesome! Thank you for the support. Windmill is such an awesome product! Keep up the good work :)

**Comment by hialvaro** [comment]
Hey, is it possible to get values from the UI (i.e current selected row value) from the inline script?

**Comment by rubenfiszel** [comment]
Yes it you take it as an input and connect to it

**Comment by rubenfiszel** [comment]
You can also choose a frontend script and access it directly
