### ISSUE TITLE
bug: Docs have incorrect import for typescript getVariable

### ISSUE THREAD

**Issue by edlouth** [windmill-labs/windmill#1600]
### Describe the bug

Currently docs https://docs.windmill.dev/docs/core_concepts/variables_and_secrets has `import * as wmill from 'https://deno.land/x/windmill/index.ts';`

I got it working by using `import { getVariable } from "https://deno.land/x/windmill@v1.101.1/mod.ts";`

### To reproduce

See https://docs.windmill.dev/docs/core_concepts/variables_and_secrets

### Expected behavior

`import { getVariable } from "https://deno.land/x/windmill@v1.101.1/mod.ts";`

**Comment by rubenfiszel** [comment]
Fixed, thanks for the report!
