### ISSUE TITLE
feature: App groups / pages / dashboards

### ISSUE THREAD

**Issue by hialvaro** [windmill-labs/windmill#1601]
It would be nice to be able to group apps in pages, so I can share a single URL for a page that groups several apps:

![](https://i.imgur.com/CWfZJOM.png)

In this screenshot, the red arrow points the apps that are grouped in the left menu, the right space shows the selected app.

> This is a screenshot from [LowCoder](https://github.com/lowcoder-org/lowcoder), which has this exact feature and is very nice.

**Comment by rubenfiszel** [comment]
We support pages in apps. Look for side tabs

**Comment by hialvaro** [comment]
But I can't add an app inside another app right?

**Comment by rubenfiszel** [comment]
Right now you cannot but we might be able to provide it as a component to embed other apps
