### ISSUE TITLE
feature request: re-use script in flow

### ISSUE THREAD

**Issue by ImSingee** [windmill-labs/windmill#1619]
Just like the [Importing an action script from the workspace](https://docs.windmill.dev/docs/flows/flow_editor#importing-an-action-script-from-the-workspace). But I want not to copy the script but trigger the script.

It will be helpful if we have many shared action scripts (Finding all references and changing each other is not easy).

BTW, I can do this by copying the script signature and requesting the OpenAPI. But I even do not find how to do this via the windmill deno library.

**Comment by rubenfiszel** [comment]
> Just like the [Importing an action script from the workspace](https://docs.windmill.dev/docs/flows/flow_editor#importing-an-action-script-from-the-workspace). But I want not to copy the script but trigger the script.

The language of the docs is inaccurate. It's actually not importing the script but just triggering it which I think is what you're looking for.

**Comment by ImSingee** [comment]
@rubenfiszel Oh so sad I have used the manual trigger many days 😭

**Comment by rubenfiszel** [comment]
I fixed the docs :)
