### ISSUE TITLE
feature request: custom Environment Variable

### ISSUE THREAD

**Issue by ImSingee** [windmill-labs/windmill#1634]
I think, in some cases setting custom environment variable (not the current variable, which requires an HTTP request) is very useful.

By the way, `TZ` is useful, and maybe it should be set by default.

**Comment by rubenfiszel** [comment]
What custom environment variables are you thinking of ?

I think it's either a contextual variable and in which case it's autoset (and maybe TZ fit that category)
or it's a user defined variable and it should be the current variables, which can be set in the env programatically if needed. Do you have exampes in mind ?

**Comment by ImSingee** [comment]
The main case is that one of my dependencies reads the environment variable before my set (it reads from Go's `init` function and persists it as a private variable). I find no ways to override it.

**Comment by rubenfiszel** [comment]
I'm adding this to the backlog and should be able to add that as an advanced metadata

**Comment by mingfang** [comment]
I also need the ability to pass worker env variable to each script automatically.
One possible implementation would be to set an ENV called `ENV_WHITELIST=MYVAR1,MYVAR2`, and then in 
https://github.com/windmill-labs/windmill/blob/711b47c78d129467eda52ff77b866ada36d61a0e/backend/windmill-common/src/variables.rs#L64
we can add `MYVAR1` and `MYVAR2` as ContextualVariable

**Comment by rubenfiszel** [comment]
It would probably be better to add them as metadata of the scripts. The implementation is not that complicated and it's in the backlog. ETA: 1 week.
