### ISSUE TITLE
feature: Support GET method in webhooks

### ISSUE THREAD

**Issue by u12206050** [windmill-labs/windmill#1637]
So I have a few systems where by I can only specify a single url to trigger events on. This url is executed with a GET method which currently isn't supported.

The GET method with support url params should be quite trivial to implement, and for sure adds some value.

**Comment by rubenfiszel** [comment]
For scripts, it's already supported. See the GET sync endpoint:
![image](https://github.com/windmill-labs/windmill/assets/275584/42ffb104-fa70-409b-8a91-b6d66f9c0f77)
