### ISSUE TITLE
feature: subpath in base url

### ISSUE THREAD

**Issue by dbi1** [windmill-labs/windmill#1639]
Hello,

It would be great to have the ability to access windmill using a subpath in the base url.

Example: my_domain.tld/windmill

While a subdomain is the nicest way to go, sometimes it is not possible. In those cases, a subpath could be the solution.

Thank you very much for your consideration.

**Comment by rubenfiszel** [comment]
The work to do is mostly frontend side, likely adjusting: https://kit.svelte.dev/docs/configuration#paths and then prefixing all base urls with that prefix. And then a lot of testing. It's too niche of a feature request and a bit too much work but if someone from the community want to tackle this, feel free.

**Comment by dbi1** [comment]
Got it, thanks for answering so quickly!
