### ISSUE TITLE
feature: Allow edits of custom resource types

### ISSUE THREAD

**Issue by cedricziel** [windmill-labs/windmill#1650]
As a user, I would like to edit a custom resource type that I added.

In the current iteration, editing is not possible and to iterate, i need to delete & recreate.

<img width="1110" alt="image" src="https://github.com/windmill-labs/windmill/assets/418970/dc790055-da8c-4df2-9fa3-5953a3587915">

**Comment by rubenfiszel** [comment]
This was originally thought of as a protection since you may be mutating a resource type scripts already depend on and resources have been already defined on. Deleting is a bit more explicit although not convenient for iteration.

**Comment by rubenfiszel** [comment]
done
