### ISSUE TITLE
feature: support to modify subdomain and path for webhook entry

### ISSUE THREAD

**Issue by VaalaCat** [windmill-labs/windmill#1685]
Enabling custom subdomain domains and paths and public entry without a token in a webhook entry can enhance the development of serverless functions, similar to how Cloudflare's Workers did.

**Comment by rubenfiszel** [comment]
You can already do the subdomain bit by customizing the revere proxy.

Custom path can be done by a middleware for now and could be done later

**Comment by VaalaCat** [comment]
I mean reverse proxy handling all web hook request to a windmill listened port, then windmill detect the hostname and path in header.
By this every script or flow could have a unique subdomain rather than one main domain same as the windmill host.
