### ISSUE TITLE
feature: add first class support for making REST calls

### ISSUE THREAD

**Issue by mingfang** [windmill-labs/windmill#1695]
Currently the frontend can have inline HTTP scripts to make REST calls.
It would be better to add a Postman like support for REST.

Also the calls should be proxied by the Windmill server to avoid CORS issues.

**Comment by rubenfiszel** [comment]
Fair enough, it would also be pretty given we can just straight use the worker http client.

**Comment by rubenfiszel** [comment]
The backend part of this is done with the job kind 'http' and require the url to be passed at arg key: 'url'.

The benchmark tool tested it successfully and achieve 150rps even for slow apis.

The frontend part is a todo.

**Comment by rubenfiszel** [comment]
done with REST jobs implemented through a native deno jsruntime with fetch support
