### ISSUE TITLE
bug: cannot serialize json with nan

### ISSUE THREAD

**Issue by programmarchy** [windmill-labs/windmill#1696]
### Describe the bug

If a Python script result contains a string `"nan"` it is not serialized correctly, and either throws an error or replaces `"nan"` with `" null "`.

Example 1:

```
def main():
    return { 'test': '\nan' }
```

```
ExecutionErr: error during execution of the script:
Error parsing result: invalid escape at line 1 column 11
```

Example 2:

```
def main():
    return { 'test': 'nan' }
```

```
{
    "test": " null "
}
```

I ran across this in a pretty standard payload, e.g.

```
{"email_body": "Hello,\nAn excellent opportunity..."}
```

### To reproduce

1. Create a new script with one of the examples
2. Click on Test
3. See error or incorrect output

### Expected behavior

Example 1 should return `{ "test": "\nan" }` and Example 2 should return `{ "test": "nan" }`.

### Browser information

Safari Version 16.2 (18614.3.7.1.5)

### Application version

Windmill CE v1.110.0-6-g9a5a0c37

### Additional Context

Looks like this regex is the culprit:

https://github.com/windmill-labs/windmill/blob/main/backend/windmill-worker/src/python_executor.rs#L343

**Comment by rubenfiszel** [comment]
YOu're exactly right about the culprit and it's because json serializer is not json compliant and serialize float NaN as 'NaN' which is not parsable by json serializers, hence our regex. I've made the regex more precise by only applying to the specific  case sensitive string 'NaN'. Otherwise we can always refine the regex.

**Comment by rubenfiszel** [comment]
Fixed in https://github.com/windmill-labs/windmill/commit/9cd73ab32bdc64029445aad4bae634e945393923

**Comment by programmarchy** [comment]
@rubenfiszel Instead of a regex, would setting `allow_nan=False` in `json.dumps` work?

https://docs.python.org/3/library/json.html#infinite-and-nan-number-values

e.g. `json.dumps(res, separators=(',', ':'), default=str, allow_nan=False)`

**Comment by rubenfiszel** [comment]
@programmarchy the reason we do not do this is that pandas/numpy actually return NaN pretty frequently and it's better behavior to consider them to be null than making them not work at all (allow_nan will just error out).

We should improve this as the current solution is a hack but using another library would slow down all the scripts and make python require a non std library to execute.
