### ISSUE TITLE
feature: Rich Text Editor

### ISSUE THREAD

**Issue by Sube-py** [windmill-labs/windmill#1698]
Hi Devs:
     At first, the windmill is so powerful, brought me a lot of convenience.
     But, I really hope to have the function of rich text editing, so that I can make the email more readable and beautiful when I send.
Thanks.

**Comment by rubenfiszel** [comment]
Hi @Sube-py could you be more specific please. Have you created an app that uses a textarea to send an email and you would like to replace the textarea with a rich editor ?

**Comment by zsnmwy** [comment]
Now I'm creating an app to manage the product and order.
The product detail page is rich text. The Textarea is unable to meet the demand.

I hope to add some pic from the media center of the rich text editor.
I want to have some preset pics in the media center.

---

I try the HTML component with Quill.
But it's not easy to export the content.

<img width="1555" alt="image" src="https://github.com/windmill-labs/windmill/assets/35299017/f207a5bd-b856-4b1c-ad0f-469d58b225dd">

**Comment by rubenfiszel** [comment]
:+1: ,

we will do exactly that, thanks for the pointer. I will try to do it today

**Comment by rubenfiszel** [comment]
done
