### ISSUE TITLE
bug: after creating a resource and saving, editing the resource shows empty or default values(but persists the originally saved values)

### ISSUE THREAD

**Issue by binarytide** [windmill-labs/windmill#1707]
### Describe the bug

same as title

### To reproduce

1. create a resource
2. save resource
3. close resource
4. edit resource

### Expected behavior

once a resource is created and saved, editing that resource should show the originally entered and saved values

### Browser information

Arc  0.107.0(chromium version: 114.0.5735.106)

### Application version

Windmill CE v1.112.0-1-g1a7aa4cd

**Comment by binarytide** [comment]
I can confirm that the values are present in the response to resources/get

**Comment by rubenfiszel** [comment]
@binarytide could you try with latest: `Windmill v1.114.1-12-g1b0b93de` and let me know if you still have this issues. We recently fixed an issue about the form that could have caused this.

**Comment by binarytide** [comment]
that did the trick, thank you!
