### ISSUE TITLE
bug: Script input inconsistent between Script Run and Flow Step Input

### ISSUE THREAD

**Issue by MichaelHindley** [windmill-labs/windmill#1725]
### Describe the bug

When using `windmill sync push`, the parameters of the `main` function are not populated as script input to be used in flows,
but are present as inputs in the script `Run` view.

### To reproduce

1. Create a script with a parameter in the main function (ts)
2. Run `wmill sync push` to push the script
3. Go to the scripts Run page, observe the ability to enter values for the parameters supplied
4. Go to or create a flow and try to add the script as an Action, observe not being able to give the script any `Step Input`.

### Expected behavior

Able to give the script parameters as step input when they have parameters defined in the main function

### Screenshots

<img width="1049" alt="image" src="https://github.com/windmill-labs/windmill/assets/1016639/c7a8614a-bcb5-41f9-85bc-fae36ef7d7ad">
<img width="1737" alt="image" src="https://github.com/windmill-labs/windmill/assets/1016639/85297828-1906-4296-a195-e3e6fc786ccd">

<img width="1734" alt="image" src="https://github.com/windmill-labs/windmill/assets/1016639/d5204059-269a-45fe-af8b-d8ecba458038">

### Application version

Windmill CE v1.111.3-7-g0b1d031b

**Comment by rubenfiszel** [comment]
Fixed in 2db53377

**Comment by rubenfiszel** [comment]
@MichaelHindley does it work for you too now ?

**Comment by MichaelHindley** [comment]
Yes, it works now, cheers!
