### ISSUE TITLE
Generalize queue and worker to being able to be run on external systems

### ISSUE THREAD

**Issue by rubenfiszel** [windmill-labs/windmill#173]
Windmill should always be able to work out-of-the box but we should generalize the queue and worker component such that for instance the queue instead of being on postgres would have an adapter for:
- kafka
- redis
- ...

and the worker could be run on:
- cloudflare worker
- AWS Lambda
- GCP cloud function
- GCP cloud run
- ....

**Comment by jacobbogers** [comment]
maybe optimize the queue stuff with a pg extension?
