### ISSUE TITLE
bug: oauth access token for gmail does not auto-refresh

### ISSUE THREAD

**Issue by MichaelHindley** [windmill-labs/windmill#1732]
### Describe the bug

Given this notification:
![image](https://github.com/windmill-labs/windmill/assets/1016639/04366076-aaed-427b-b757-5eaa68446b7c)

I would not expect this error:
![image](https://github.com/windmill-labs/windmill/assets/1016639/69da2be6-3794-422b-a793-52c120df44e8)

With this code:
<img width="859" alt="image" src="https://github.com/windmill-labs/windmill/assets/1016639/53ec4257-d497-4755-b363-95191183b75e">

Manually refreshing the token in the UI removes the error.

### To reproduce

Setup gmail oauth  in oauth.json (docker-compose setup) and try to use an expired token, observe error.

### Expected behavior

Token to be auto-refreshed when used as wmill.Resource in script, given it's expired

### Application version

Latest docker containers as of this message

**Comment by rubenfiszel** [comment]
Will investigate today, thanks for the report

**Comment by rubenfiszel** [comment]
I am currently unable to reproduce this.

I have set a gmail oauth resources, manually updated the account expiration to be expired, then used it as a resource and the token was indeed automatically refreshed. One way of testing this is to do:

```
 UPDATE account set expires_at = now();
 ```

Would you have more backend logs or more context that would help me reproduce this ?

**Comment by royalmaster960** [comment]
i am too. but i am using google sheet Oauth. It's not auto refresh token.
Now i am fixing by manual following:
Step 1: Click variable category
Step2: Click to token path
Step3: Using script call wmill.get_variable (token_path), at the moment windmill is returning the new token. (if you dont follow step 1 and 2, the old token will be return
<img width="1345" alt="image" src="https://github.com/windmill-labs/windmill/assets/110345381/b69e9ec4-679c-465b-a6da-4674876a7334">

**Comment by MichaelHindley** [comment]
> I am currently unable to reproduce this.
> 
> I have set a gmail oauth resources, manually updated the account expiration to be expired, then used it as a resource and the token was indeed automatically refreshed. One way of testing this is to do:
> 
> ```
>  UPDATE account set expires_at = now();
> ```
> 
> Would you have more backend logs or more context that would help me reproduce this ?

I'll try to get more debug data on that soon

**Comment by MichaelHindley** [comment]
Logs from windmill-server container when this occurs. (triggering manual refresh removed the "invalid client" error as I've observed in logs)

```txt
windmill-windmill_server-1  | 2023-06-17T20:38:41.697474Z  INFO request:job_run: windmill_audit: operation="jobs.run.script" action_kind=Execute resource="EE only" parameters={"redacted":"-"} workspace_id="mikesplace" username="michael" method=POST uri=/api/w/mikesplace/jobs/run/h/91bb9fd81292aea9 username="michael" email="redacted@domain.com" workspace_id="mikesplace" email="redacted@domain.com"
windmill-windmill_server-1  | 2023-06-17T20:38:41.706859Z  INFO request: windmill_api::tracing_init: response latency=37 status=201 method=POST uri=/api/w/mikesplace/jobs/run/h/91bb9fd81292aea9 username="michael" email="redacted@domain.com" workspace_id="mikesplace"
windmill-windmill_worker-3  | 2023-06-17T20:38:41.713672Z  INFO windmill_worker::worker: fetched job 0188cb14-db11-0dc0-509c-83a0403e7a9a, root job: none worker=wk-e79af244c7b1-AcpZx workspace_id=mikesplace id=0188cb14-db11-0dc0-509c-83a0403e7a9a root_id=none
windmill-windmill_worker-3  | 2023-06-17T20:38:41.783222Z  INFO request: windmill_api::tracing_init: response latency=24 status=200 method=GET uri=/api/w/mikesplace/resources/get_value/u%2Fmichael%2Fgrand_gmail username="michael" email="redacted@domain.com" workspace_id="mikesplace"
windmill-windmill_server-1  | 2023-06-17T20:38:41.784950Z  INFO request: windmill_api::tracing_init: response latency=9 status=200 method=GET uri=/api/w/mikesplace/jobs_u/get/0188cb14-db11-0dc0-509c-83a0403e7a9a
windmill-windmill_worker-3  | 2023-06-17T20:38:41.791895Z  INFO request: windmill_audit: operation="variables.decrypt_secret" action_kind=Execute resource="EE only" parameters={"redacted":"-"} workspace_id="mikesplace" username="michael" method=GET uri=/api/w/mikesplace/variables/get/u%2Fmichael%2Fgrand_gmail?decrypt_secret=true username="michael" email="redacted@domain.com" workspace_id="mikesplace"
windmill-windmill_worker-3  | 2023-06-17T20:38:41.799910Z  INFO request: windmill_api::oauth2: OAuth loaded clients:  method=GET uri=/api/w/mikesplace/variables/get/u%2Fmichael%2Fgrand_gmail?decrypt_secret=true username="michael" email="redacted@domain.com" workspace_id="mikesplace"
windmill-windmill_worker-3  | 2023-06-17T20:38:41.800023Z ERROR request: windmill_common::error: error="Bad request: invalid client" method=GET uri=/api/w/mikesplace/variables/get/u%2Fmichael%2Fgrand_gmail?decrypt_secret=true username="michael" email="redacted@domain.com" workspace_id="mikesplace"
windmill-windmill_worker-3  | 2023-06-17T20:38:41.800077Z  INFO request: windmill_api::tracing_init: response latency=15 status=400 method=GET uri=/api/w/mikesplace/variables/get/u%2Fmichael%2Fgrand_gmail?decrypt_secret=true username="michael" email="redacted@domain.com" workspace_id="mikesplace"
windmill-windmill_worker-3  | 2023-06-17T20:38:41.801771Z  INFO windmill_worker::worker: finished Deno job 0188cb14-db11-0dc0-509c-83a0403e7a9a worker_name=wk-e79af244c7b1-AcpZx job_id=0188cb14-db11-0dc0-509c-83a0403e7a9a workspace_id=mikesplace is_ok=false
windmill-windmill_server-1  | 2023-06-17T20:38:41.853513Z  INFO request: windmill_api::tracing_init: response latency=3 status=200 method=GET uri=/api/w/mikesplace/jobs_u/getupdate/0188cb14-db11-0dc0-509c-83a0403e7a9a?running=true&log_offset=104
windmill-windmill_server-1  | 2023-06-17T20:38:41.862548Z  INFO request: windmill_api::tracing_init: response latency=3 status=200 method=GET uri=/api/w/mikesplace/jobs_u/get/0188cb14-db11-0dc0-509c-83a0403e7a9a
windmill-windmill_server-1  | 2023-06-17T20:38:44.083560Z  INFO request: windmill_api::tracing_init: response latency=0 status=200 method=GET uri=/api/w/mikesplace/variables/list_contextual username="michael" email="redacted@domain.com" workspace_id="mikesplace"
windmill-windmill_server-1  | 2023-06-17T20:38:44.089160Z  INFO request: windmill_api::tracing_init: response latency=5 status=200 method=GET uri=/api/w/mikesplace/variables/list username="michael" email="redacted@domain.com" workspace_id="mikesplace"
```

As for other context I'm not sure but, the oauth.json just has the id & secret, running docker(mac, engine version 24.0.2), tried running script both in UI, CLI & VSCode extension and same results- once the token is expired it is not refreshed. I did not set it to expired manually in the db, rather just triggered the script after being away from laptop for a while.

Anything else I can do to provide more details?

**Comment by rubenfiszel** [comment]
We've been able to reproduce this once, I will dig more today!

**Comment by rubenfiszel** [comment]
Ok I figured it out. It's due to a recent change in the recommended configuration such that the worker serve the api themselves for their own needs, including the api to refresh the token.

The solution is to mount oauth.json (or equivalent method) to the workers as well.

I am updating the docs and the helm charts.
