### ISSUE TITLE
bug: The script did not show parameters

### ISSUE THREAD

**Issue by royalmaster960** [windmill-labs/windmill#1735]
### Describe the bug

I have 2 bug when change require parameter to default parameters

### To reproduce

Bug 1 (picture 1)
1. Go to python script
2. Click on : Save script
3. Close windmill tab on browser
4. Go to edit script
5. Add default parameters.
6. Save script and see error parameters did not update

Bug 2: (picture 2)
 i am at step 6 now, I think my browser is caching something, i am refresh my browser that show error: "413 ERROR
The request could not be satisfied"

### Expected behavior

Expected: the script will show default parameters

### Screenshots

<img width="1345" alt="image" src="https://github.com/windmill-labs/windmill/assets/110345381/afdfd193-693c-4623-b6cf-79adbac073d3">

<img width="1345" alt="image" src="https://github.com/windmill-labs/windmill/assets/110345381/c389ad40-f753-4e87-bb57-ceed66e2b04f">

**Comment by rubenfiszel** [comment]
Your script is not parsable because arguments that have default parameters in python need to be after all the ones that do not have default parameters

The bug 2 is because your script is too big and the saved state in the URL is too big for cloudfront to handle
