### ISSUE TITLE
bug: Cannot Import Resource Types from the Hub

### ISSUE THREAD

**Issue by Anton-Shutik** [windmill-labs/windmill#1737]
### Describe the bug

I have a fresh windmill instance, deployed from helm chart. On a first login it showed a message that it couldn't  find `setup_app` job.

Then I tried to sync up Resource types manually, [with the script](https://hub.windmill.dev/scripts/windmill/1323/import-resource-types-from-the-hub-windmill) (from admin@windmill.dev account), but it always says: `Internal: Could not insert into queue <id>: error returned from database: new row violates row-level security policy for table "queue"`

### To reproduce

1. Go to `Scripts`
2. Click on `Create new`
3. Copy and paster [script from](https://hub.windmill.dev/scripts/windmill/1323/import-resource-types-from-the-hub-windmill) 
4. Click on `Test`

### Expected behavior

Script executed sucesfully 

### Screenshots

![image](https://github.com/windmill-labs/windmill/assets/1625053/78a10b68-e17c-4f35-b966-a853a022a05e)

### Browser information

Version 113.0.5672.126 (Official Build) (arm64)

### Application version

Windmill CE v1.115.0-7-g6310a7dd

**Comment by Anton-Shutik** [comment]
Database is on AWS RDS
```
select version();
                                                   version                                                    
--------------------------------------------------------------------------------------------------------------
 PostgreSQL 15.3 on aarch64-unknown-linux-gnu, compiled by gcc (GCC) 7.3.1 20180712 (Red Hat 7.3.1-6), 64-bit
(1 row)

```

**Comment by Anton-Shutik** [comment]
I don't think so. Our roles managed from `rds_superuser` role, which was setup during RDS instance creation (we cant have postgres superuser access on RDS by their design)

When I create another admin, and try to run the script from their account, [the script](https://hub.windmill.dev/scripts/windmill/1323/import-resource-types-from-the-hub-windmill) runs, but fails with:

```
Error: The mediaType text/html is not supported by ObjectSerializer.parse.
    at Function.parse (https://deno.land/x/windmill@v1.31.0/windmill-api/models/ObjectSerializer.ts:514:15)
    at ResourceApiResponseProcessor.existsResourceType (https://deno.land/x/windmill@v1.31.0/windmill-api/apis/ResourceApi.ts:885:34)
    at eventLoopTick (ext:core/01_core.js:181:11)
    at async main (file:///tmp/windmill/wk-hg9cz-PjWJh/0188d391-47e6-edf5-6b59-e48ea4804c20/main.ts:20:9)
    at async run (file:///tmp/windmill/wk-hg9cz-PjWJh/0188d391-47e6-edf5-6b59-e48ea4804c20/wrapper.ts:14:20)
```

**Comment by rubenfiszel** [comment]
I deleted the script since it is obsolete.

The right script to run is in: https://docs.windmill.dev/docs/advanced/self_host#admins-workspace

So it seems you do not have the same error anymore ?

This error: 'Internal: Could not insert into queue <id>: error returned from database: new row violates row-level security policy for table "queue"' 

is really weird. I will attempt reproduce on a fresh rds.

**Comment by rubenfiszel** [comment]
The setup_app is loaded from an initial migration, it's not loaded from the hub. What I suspect is that  because of the way the initial migration was previously setup, you had 2 windmill databases on the same instance and the grant were not done properly on the second database. This is now fixed on latest https://github.com/windmill-labs/windmill/commit/6dabc933890709746aab83cbbd0cad41a42723bc but you will have to nuke your databases and repull

**Comment by rubenfiszel** [comment]
I think it's more likely that you are not in the admins workspace. The apps are workspace specific. 

Can you try going to /apps/get/g/all/setup_app?workspace=admins with a windmill superuser ?

**Comment by Anton-Shutik** [comment]
I figured it out. For some reason `windmill_admin` didn't have `BYPASSRLS` flag enabled. No it works fine with current users setup.

```
windmill=> \du
                                                                                         List of roles
     Role name     |                         Attributes                         |                                                  Member of                                                   
-------------------+------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------
 ...
 windmill_admin    | Cannot login, Bypass RLS                                  +| {windmill_user}
                   | Password valid until infinity                              | 
 windmill_ddl_user | Create DB                                                 +| {windmill_admin,windmill_user}
                   | Password valid until infinity                              | 
 windmill_user     | Cannot login                                              +| {}
                   | Password valid until infinity                              | 
```

Thanks for you help and patience!
