### ISSUE TITLE
bug: Error: Migrating database: while executing migrations: error returned from database: role "windmill_user" does not exist

### ISSUE THREAD

**Issue by mhristof** [windmill-labs/windmill#1738]
### Describe the bug

when running windmill with RDS postgress as the storage database, im getting this error

```
{"timestamp":"2023-06-19T11:25:26.106637Z","level":"INFO","message":"Connecting to database...","target":"windmill"}
{"timestamp":"2023-06-19T11:25:26.264892Z","level":"INFO","message":"Database connected","target":"windmill"}
Error: Migrating database: while executing migrations: error returned from database: role "windmill_user" does not exist
Caused by:
    0: while executing migrations: error returned from database: role "windmill_user" does not exist
    1: error returned from database: role "windmill_user" does not exist
    2: role "windmill_user" does not exist
```

With the same credentials provided in env var `DATABASE_URL`, if i run the script mentioned in https://github.com/windmill-labs/windmill#postgres-without-superuser, i can start windmill OK.

### To reproduce

Setup an RDS instance with config

```
module "db" {
  source  = "terraform-aws-modules/rds/aws"
  version = "5.9.0"

  identifier = "windmill-${var.name}"

  engine         = "postgres"
  engine_version = "14"
  family         = "postgres14"

  instance_class    = "db.t3.medium"
  allocated_storage = 20

  db_name  = "windmill"
  username = "windmill"
  port     = "3306"
```

and pass the value of 
```
        {
          name  = "DATABASE_URL"
          value = "postgres://${module.db.db_instance_username}:${module.db.db_instance_password}@${module.db.db_instance_endpoint}/windmill"
        },
```

in the docker.

The logs will show

```
{"timestamp":"2023-06-19T11:25:26.106637Z","level":"INFO","message":"Connecting to database...","target":"windmill"}
{"timestamp":"2023-06-19T11:25:26.264892Z","level":"INFO","message":"Database connected","target":"windmill"}
Error: Migrating database: while executing migrations: error returned from database: role "windmill_user" does not exist
Caused by:
    0: while executing migrations: error returned from database: role "windmill_user" does not exist
    1: error returned from database: role "windmill_user" does not exist
    2: role "windmill_user" does not exist
```
and windmill wont start.

### Expected behavior

Detect that the user passed in windmill has root permissions and run all the migrations required

### Application version

ghcr.io/windmill-labs/windmill:1.116.0

**Comment by rubenfiszel** [comment]
Given that you were able to run the sql script, you just need to run that in psql with the same DATABASE_URL. It's just an sql query.

**Comment by rubenfiszel** [comment]
I think it is an rds superuser (which is an rds specific thing) and not an actual postgres superuser. I will try to see if we can adapt the migration to this pattern.

**Comment by mhristof** [comment]
either that or a README update would be fine TBH (since RDS doesnt allow users to create `usesuper` users).

Thanks for the promt reply

**Comment by rubenfiszel** [comment]
Starting from: https://github.com/windmill-labs/windmill/commit/6dabc933890709746aab83cbbd0cad41a42723bc

The initial user creation does not do the check and will attempt to do it regardless

That should solve those database specific issues in the future
