### ISSUE TITLE
feature: improve docs for o365 auth

### ISSUE THREAD

**Issue by mhristof** [windmill-labs/windmill#1749]
[From the docs](https://docs.windmill.dev/docs/misc/setup_oauth), i can see

> <integration> code must match with the code that is setup in [oauth_connect.json](https://github.com/windmill-labs/windmill/blob/main/backend/oauth_connect.json)

and in `oauth_connect.json` i can't see any info about office 365. The keys available are
```json
[
  "basecamp",
  "bitbucket",
  "gcal",
  "gcloud",
  "gdrive",
  "github",
  "gitlab",
  "gmail",
  "gsheets",
  "linkedin",
  "slack"
]
```

I can also see some mention in [oauth_login.json](https://github.com/windmill-labs/windmill/blob/v1.116.0/backend/oauth_login.json) which kinda suggests its supported but its unclear how to set it up.

**Comment by rubenfiszel** [comment]
oauth_login is the login/IdP providers that we support for login into windmill.
oauth_connect are the resource types for which we support getting the token and refreshing the token through an oauth flow.

We support microsoft login oauth (which is what power the microsoft login on app.windmill.dev)
We likely support o365 out of the box even for resources, but we would need to test it further. For a lot of resources and resource types, we are a very small team so we would rely on the community to help test them and provide us with their configuration settings.

**Comment by rubenfiszel** [comment]
We have this open PR for all the oauth flow we are likely to be able to support but would need to do the work of documenting/testing: https://github.com/windmill-labs/windmill/issues/1482
