### ISSUE TITLE
feature: Skip flow step when testing

### ISSUE THREAD

**Issue by hialvaro** [windmill-labs/windmill#1750]
Sometimes it can be useful to skip a flow step when testing it, such as sending chat messages. For this, it would be great to be able to skip a step when testing (or even permanently).

**Comment by rubenfiszel** [comment]
I thought that was such a good idea that I just did, and it's merged on main:
![image](https://github.com/windmill-labs/windmill/assets/275584/7311f743-e02e-4c3d-b565-d0def031e2dd)

**Comment by hialvaro** [comment]
Awesome, thank you!
