### ISSUE TITLE
feature: Run a flow on a particular worker or worker group

### ISSUE THREAD

**Issue by ccxuy** [windmill-labs/windmill#1763]
Hi,

After trying out some small tasks, I find out scripts can bind to a worker group, but flow can not bind to a group. That is nessesary when a flow need some particular feature or store some data on same machine.

Could this be considered as a future improvement?

**Comment by rubenfiszel** [comment]
Yes, it could be done

**Comment by rubenfiszel** [comment]
Implemented in a0997911bf9da8651ddb830e9e09f2d3f82c73e4
