### ISSUE TITLE
feature:  how to prevent job kill due to time out 

### ISSUE THREAD

**Issue by Bmixo** [windmill-labs/windmill#1783]
i want this scripts  keep running and i dont want it time out ,how can i do that

![image](https://github.com/windmill-labs/windmill/assets/25509024/8f0655cf-f1f1-465c-bfbf-b91eb67e6691)

**Comment by rubenfiszel** [comment]
You can configure the timeout through the TIMEOUT env variable. Otherwise, we have a timeout for free plans on the cloud but not for premium plans.

**Comment by Bmixo** [comment]
> You can configure the timeout through the TIMEOUT env variable. Otherwise, we have a timeout for free plans on the cloud but not for premium plans.

but i means i want comfigure TIMEOUT  for  singal scripts rather all of the scripts. if i pass the TIMEOUT env variable in the docker it that means all the scripts will not be timeout? but i just want the specific scripts will not time out
