### ISSUE TITLE
Classify scripts by category + Icon + search

### ISSUE THREAD

**Issue by rubenfiszel** [windmill-labs/windmill#18]
The current product makes sense for a tiny set of community scripts.

We want an exhaustive set (see #15 ) and as such we need to better categorize the scripts (which for now have no category concepts).

For improved UX, we are likely to also want to have an medium size icon for each category

Last but not least, for every interactions that could pick from a community scripts, we want to display a sample of it ("Most popular? Most relevant given context ?) and have a search field to search for the relevant script.

The search function should use keyword from summary, description.

We can imagine later using neural net search engine and encode scripts in a manifold. A simpler version of this is to start with tags.

**Comment by aggmoulik** [comment]
Hi @rubenfiszel Can you elaborate on the task by technical implementation? I would love to work with such technical challenges.

**Comment by rubenfiszel** [comment]
@aggmoulik: The tasks could be splitted as follow
1. some part that is API re-design that I will work on asap that is not technically very interesting: Adding tags, icon, categories fields to scripts
2. Add popularity/usage information per-scripts
3.  integrate a powerful search flow that is powerful (find relevant scripts), snappy (fast) and lightweight on the backend and database (do not need to fetch all scripts everytime)
    - Before the community scripts reach 500,  one can probably do it all in the frontend by passing the entire index
    - After that it might make sense to integrate with backend search engine such as meilisearch: https://www.meilisearch.com/

I believe 3. is the most interesting and one could start doing evaluation of the benefit/cost of passing the index to the frontend vs backend search
