### ISSUE TITLE
bug: Python - Installing requirement based package from Github URL installs dependencies but not the package

### ISSUE THREAD

**Issue by bluecoconut** [windmill-labs/windmill#1804]
### Describe the bug

I am trying to install a python package from a Github URL, and it almost works. This path works with pip install and requirements.txt with local interpeters, but with the windmill workers it seems to not install the final package?

### To reproduce

1. Go to create a new script
2. Select python
3. Type in:
```python
# requirements:
# git+https://github.com/approximatelabs/sketch.git@main
import sketch
def main():
    print(dir(sketch))
```
4. Watch installs happen (including successful install of the package it seems --> `Successfully installed sketch-0.4.2`)
4. See that actual execution errors -> Cannot import `sketch`. 

### Expected behavior

It almost seemed like this works, and investigating `print(help("modules"))` shows everything as successfully installed _except_ the desired package itself. Eg. all the dependencies of the package successfully install, so it just seems like the final egg for the final package doesn't get linked to or something.

**Comment by bluecoconut** [comment]
Extra Note:
In the `.script.yaml`, it looks like it successfully parses as well
```yaml

...

lock:

...

- 'sketch @ git+https://github.com/approximatelabs/sketch.git@main'
```

**Comment by rubenfiszel** [comment]
Fixed on latest!
