### ISSUE TITLE
bug: postgres column type UUID not working

### ISSUE THREAD

**Issue by some-user123** [windmill-labs/windmill#1808]
### Describe the bug

When querying a table with a column of type UUID, I get:
```
{
    "name": "ExecutionErr",
    "message": "ExitCode: 1, last log lines:\ncolumn_name:id"
}
```

### To reproduce

```sql
 CREATE TABLE my_table (
  id UUID,
  name VARCHAR(255)
);

INSERT INTO my_table (id, name) VALUES ('4eb527a6-9f9f-4fdb-8c27-12ebcaebb7c1', 'foo');
```

Connect to the database, create a postgres script:
```sql
SELECT name, id FROM my_table;
```

Test it.

It works if the `id` column is not included in the result.

### Expected behavior

Should not fail.

### Screenshots

![image](https://github.com/windmill-labs/windmill/assets/74715856/ac6de117-37f3-4625-b892-a18f31f04cf2)

### Application version

Windmill CE v1.125.1-2-g18f4dc07

**Comment by rubenfiszel** [comment]
Fixed on latest

**Comment by some-user123** [comment]
Thanks a lot, it's working. However, I encountered the next column type (`Date`) that's not working. Is there a list of supported column types?

**Comment by rubenfiszel** [comment]
Date works on latest. The best way to know what types are supported it to look at pg_executors.rs but I think we're starting to cover the largest majority of them. Feel free to re-open an issue if you find any other type missing!
