### ISSUE TITLE
feature: rate limiting of steps

### ISSUE THREAD

**Issue by some-user123** [windmill-labs/windmill#1809]
As an idea for improvement (of an awesome tool 🤩):

I'd like to limit the load a certain workflow step is causing. Therefore, I'd like to limit the number of executions of this step to a certain frequency, e.g. at most 10 per minute or 100 per second or 5 per day.
Workflow step should not be executed immediately but put on a queue, when this limit is (or would be) reached.

**Comment by rubenfiszel** [comment]
We will implement concurrency limits fairly shortly

**Comment by some-user123** [comment]
I've seen #1765. Would concurrency limits cover above requirements? To me concurrency limit sounds more like "not more than N parallel executions of this step at any given time". Knowing how long the execution takes (seconds per request), this can be converted to a rate limit (requests per second).

However, I'd like to specify a rate limit instead of a concurrency limit to:
- be independent of the duration of an request
- have limits much lower than 1 concurrent execution (e.g. max 5 requests per day)

**Comment by rubenfiszel** [comment]
We are implementing concurrency limits with time windows so it would behave as a rate limit and have the characteristics you describe

**Comment by rubenfiszel** [comment]
This is now implemented with concurrency limits and time windows
