### ISSUE TITLE
bug: cannot edit flow when coming from detail page

### ISSUE THREAD

**Issue by some-user123** [windmill-labs/windmill#1825]
### Describe the bug

See below

### To reproduce

1. Click on "Home"
2. Click in a flow --> shows details of the flow
3. Click "Edit" in the top right corner
4. I only see a white page and need to refresh the whole app

### Expected behavior

Should display the flow as it does when:
1. Click on "Home"
2. Click "Edit" next to flow

**Comment by rubenfiszel** [comment]
should be fixed on latest
