### ISSUE TITLE
bug: UI 🐛 if text box has focus, then CTRL + S keyboard shortcut invokes browser function, not Windmill "Save Draft"

### ISSUE THREAD

**Issue by pcgeek86** [windmill-labs/windmill#1862]
### Describe the bug

If I am editing a script in Windmill UI, and one of the input boxes has focus, then pressing `CTRL + S` invokes the browser action "save as". 

### To reproduce

![image](https://github.com/windmill-labs/windmill/assets/466713/3e40b3af-3bbf-495b-8025-c9560c1288a3)

### Expected behavior

Pressing `CTRL + S` should invoke the Windmill "save draft" function.

**Comment by HugoCasa** [comment]
Seems to not be the case anymore (at least on chrome, firefox and safari), closing
