### ISSUE TITLE
bug: IO Error on latest docker image

### ISSUE THREAD

**Issue by murunwas** [windmill-labs/windmill#1864]
### Describe the bug

I'm getting the IO error on the latest docker image as shown on the image below
![image](https://github.com/windmill-labs/windmill/assets/8838943/c86c81bd-d9c3-40ae-ba6a-44b7d2a195ce)

### To reproduce

1.  docker pull latest image
2. run any script

![image](https://github.com/windmill-labs/windmill/assets/8838943/8190111c-3ac2-4cba-a57e-10b04be49a6c)

### Expected behavior

the scripts to run successfully

### Screenshots

![image](https://github.com/windmill-labs/windmill/assets/8838943/566c3b99-b119-4477-ba5c-79024d1628a2)

**Comment by rubenfiszel** [comment]
Fixed on latest
