### ISSUE TITLE
bug: Getting "Error building oauth clients: Is a directory (os error 21)" when running docker compose on mac

### ISSUE THREAD

**Issue by bejoyzm** [windmill-labs/windmill#1874]
### Describe the bug

I am trying to run docker compose up and getting the "Error building oauth clients: Is a directory (os error 21)"

`windmill-windmill_server-1         | 2023-07-13T21:14:51.690990Z  INFO windmill: Connecting to database...
windmill-windmill_server-1         | 2023-07-13T21:14:51.725157Z  INFO windmill: Database connected
windmill-windmill_server-1         | 2023-07-13T21:14:51.741807Z  INFO windmill:
windmill-windmill_server-1         | ##############################
windmill-windmill_server-1         | Windmill Community Edition v1.129.1-2-g85471252
windmill-windmill_server-1         | ##############################
windmill-windmill_server-1         | 2023-07-13T21:14:51.741897Z  INFO windmill: config: DISABLE_SERVER: false, NUM_WORKERS: 0, METRICS_ADDR: false, BASE_URL: http://localhost, GO_PATH: /usr/local/go/bin/go, PATH: /usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/go/bin, HOME: /root, REQUEST_SIZE_LIMIT: 50097152
windmill-windmill_server-1         | thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ()', windmill-api/src/lib.rs:93:10
windmill-windmill_server-1         | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
windmill-windmill_server-1         | 2023-07-13T21:14:51.742257Z ERROR windmill_api: Error building oauth clients: Is a directory (os error 21)`

### To reproduce

1. Run the following commands

`curl https://raw.githubusercontent.com/windmill-labs/windmill/main/docker-compose.yml -o docker-compose.yml
curl https://raw.githubusercontent.com/windmill-labs/windmill/main/Caddyfile -o Caddyfile
curl https://raw.githubusercontent.com/windmill-labs/windmill/main/.env -o .env

docker compose up `

2. Notice the error in the log:

```
curl https://raw.githubusercontent.com/windmill-labs/windmill/main/docker-compose.yml -o docker-compose.yml
curl https://raw.githubusercontent.com/windmill-labs/windmill/main/Caddyfile -o Caddyfile
curl https://raw.githubusercontent.com/windmill-labs/windmill/main/.env -o .env

docker compose up -d
```

3. Access http://localhost/ and we see a 502

### Expected behavior

Being able to see the login screen and access the system with the default authentication

### Browser information

Firefox, Chrome (latest version)

**Comment by rubenfiszel** [comment]
You need to curl oauth.json. I edited the Readme to add this new curl. Thanks for the report

**Comment by bejoyzm** [comment]
Thank you. This worked
