### ISSUE TITLE
API documentation copy-paste error for cancelSuspendedJob

### ISSUE THREAD

**Issue by yureckey** [windmill-labs/windmill#1898]
### Describe the bug

https://app.windmill.dev/openapi.html#/operations/cancelSuspendedJobGet
https://app.windmill.dev/openapi.html#/operations/cancelSuspendedJobPost
Responses
201
"job resumed" - I guess it should be "cancelled"?

### To reproduce

https://app.windmill.dev/openapi.html#/operations/cancelSuspendedJobGet

### Expected behavior

should be "job cancelled"

**Comment by rubenfiszel** [comment]
Fixed in next commit, thanks
