### ISSUE TITLE
wording in the flow -> add -> schedule

### ISSUE THREAD

**Issue by yureckey** [windmill-labs/windmill#1900]
### Describe the bug

https://app.windmill.dev/flows/add
settings -> schedule
"...their webhooks or their UI but they only have only one primary schedules..."
"they only have only one" - I think first "only" isn't needed

### To reproduce

https://app.windmill.dev/flows/add
settings -> schedule

### Expected behavior

less "only"

**Comment by rubenfiszel** [comment]
fixed in next commit, thanks
