### ISSUE TITLE
Dependencies are not installed when importing other script as shared logic

### ISSUE THREAD

**Issue by deadlocks** [windmill-labs/windmill#1901]
### Describe the bug

I am building a common Python script for all the utilities. In other scripts I simply import this script and use the functions. However the dependencies are not resolved after importing and I get error on runtime

Consider a simple example of util script (I need specific version of this module). When run individually, this script is running fine

```
# f/utils/common

# requirements:
# dependency
# elasticsearch==7.8.0

from elasticsearch import Elasticsearch

def biblio_from_elastic():
    pass

````

In other script I call it like this 

```
# u/anmolsaini/viewable_script

import f.utils.common as gb_utils

def main():
    return gb_utils.biblio_from_elastic()

```

On run I get this error
![image](https://github.com/windmill-labs/windmill/assets/2733405/b0d83e91-ab52-4ab5-b701-5741ccb728ca)

### Expected behavior

The dependencies of the imported scripts should be resolved automatically

**Comment by rubenfiszel** [comment]
Unfortunately, right now windmill is not able to resolve automatically imports from local imports. It is something we could improve and I will use this issue to track progress.

**Comment by deadlocks** [comment]
Got it. Is there any workaround? Like a way to install such dependencies globally so that they can be shared by any script under workspace?

**Comment by rubenfiszel** [comment]
The immediate workaround is to add the dependencies requirement in your importing scripts.
Otherwise yes, if you are using self-hosted or dedicated enterprise instance, it's possible to add local dependencies using a combination of:
PIP_LOCAL_DEPENDENCIES and ADDITIONAL_PYTHON_PATHS which are documented in the README (but we should write a mini tutorial in the docs about.

**Comment by deadlocks** [comment]
I tried experimenting with these variables but not sure what's the correct way to do it. Is there any documentation or example that I can follow?

Appreciate all the help and it's a great project :)

**Comment by rubenfiszel** [comment]
Apologies, PIP_LOCAL_DEPENDENCIES is all you need:

for instance to have pandas and numpy be included automatically in all scripts:
PIP_LOCAL_DEPENDENCIES=pandas,numpy

Then make sure that your docker image that you use for your workers has installed prior pandas and numpy:

For instance, by running:

```
RUN /usr/local/bin/python3 -m pip install pandas
RUN /usr/local/bin/python3 -m pip install numpy
```

**Comment by rubenfiszel** [comment]
Original issue is now implemented
