### ISSUE TITLE
feature: Event Driven Workflow Execution

### ISSUE THREAD

**Issue by ImSingee** [windmill-labs/windmill#1903]
Is there any plan to implement event-driven workflow execution (or event trigger)?

For example:

1. An interval trigger that fetches RSS and produces arbitrary events in an execution 
2. For each (new) event, automatically run workflow/script

**Comment by ImSingee** [comment]
And another thing is that de-duplicate.

I tried to implement some de-duplicate by myself, but I failed to build a perfect one. -- The main part is the lack of the atomic update (enqueue and dequeue an events queue atomically)

**Comment by rubenfiszel** [comment]
Have you tried using flow's triggers (which are normal scripts but just have a different default template) + setState/getState + schedule ?

**Comment by ImSingee** [comment]
@rubenfiszel Sorry for my late reply.

The `setState`/`getState` is not atomic. This means, in a concurrent context, some of my events may be lost.

**Comment by rubenfiszel** [comment]
getState/setState are backed by postgres so they can definitely be used to build atomic patterns. But also you can set the main flow to have a concurrency limit of 1 which would solve a lot of this :)

**Comment by rubenfiszel** [comment]
I believe you're in an older version of windmill with a bug related to that. Can you update to latest and report if you have that issue.

The time window is just how far we look back for jobs that would as being "concurrent", 0 or undefined is only jobs that are currently running

**Comment by ImSingee** [comment]
@rubenfiszel Sorry for that. My this instance of windmill is only 1.136, and I upgraded to 1.165 then it works well.

But, I think sometimes the concurrency limit cannot work well in some cases: if there's more than 1 queued executions, they may (it won't happen every time, but I can easily reproduce it) be started at the same time.

I set the concurrency limit to 1, and then run around 10 times, and some executions start at the same time.

<img width="1292" alt="image" src="https://github.com/windmill-labs/windmill/assets/11208082/6223460a-b9f7-4947-9b5f-617130fa11ef">

<img width="1272" alt="image" src="https://github.com/windmill-labs/windmill/assets/11208082/f1a2f31a-d3dd-4bc3-9026-8c210b81dc39">
<img width="1440" alt="image" src="https://github.com/windmill-labs/windmill/assets/11208082/01946a8f-fcf3-4c00-bed9-84dff848a35c">
<img width="1440" alt="image" src="https://github.com/windmill-labs/windmill/assets/11208082/39e63496-4f9b-45c1-a3bb-a820dd07322a">
<img width="1440" alt="image" src="https://github.com/windmill-labs/windmill/assets/11208082/209191e5-55e4-4241-ba63-0e205c9c207d">

Here's my test script

```bash
# shellcheck shell=bash
# arguments of the form X="$I" are parsed as parameters X of type string
echo "Start At $(date)"

sleep 20

echo "End At $(date)"
```

**Comment by rubenfiszel** [comment]
Ah yes, I think what is happening is a race issue where the N workers are all fetching the same jobs at the same time and not seeing the row locked by the other workers. We will need to fix this

**Comment by ImSingee** [comment]
@rubenfiszel I get it! By the way, my database is a Postgres cluster, maybe the cluster influences the problem.

**Comment by rubenfiszel** [comment]
No I don't think it's the cluster, I have a pretty good intuition of what is happening. We will need to improve this

**Comment by rubenfiszel** [comment]
@ImSingee this should be fixed in latest

**Comment by ImSingee** [comment]
@rubenfiszel Yes, it works perfectly!
<img width="791" alt="image" src="https://github.com/windmill-labs/windmill/assets/11208082/6486d34d-3262-43fd-9948-fc958a6b54ec">

I can now starting developing my own event-driven system
