### ISSUE TITLE
bug: postgres connection

### ISSUE THREAD

**Issue by ricardo8c** [windmill-labs/windmill#1908]
### Describe the bug

When I try to add a postgres resource with the following parameters:

{
  "password": "****************",
  "sslmode": "disable",
  "dbname": "postgres",
  "user": "postgres",
  "host": "db.cnenlfqcrhvasjdljtez.supabase.co",
  "port": 5432
}

I get the error message:
Supplied DSN has invalid sslmode 'undefined'

I have the same issue when I try to add a local postgres resource. And I have this issue adding supabase postgres in windmill cloud as well

### To reproduce

1. Go to 'resources'
2. Click on 'Add a resource'
3. Select postgres type
4. Add the parameters as json or in the form
5. Click on 'Test connection'
6. See the error message on top

### Expected behavior

Connection being established

### Browser information

Brave Version 1.52.130 Chromium: 114.0.5735.198 (Versão oficial) 64 bits

### Application version

Windmill EE v1.133.0-7-g8f6d9721

**Comment by rubenfiszel** [comment]
Thanks for the report, fixed on latest
