### ISSUE TITLE
bug: Different base64 encoded string for File Input in Script/Flows and Apps

### ISSUE THREAD

**Issue by snjv94** [windmill-labs/windmill#1916]
### Describe the bug

An Input step in a flow (type: string, Advanced: File (base64)) returns base64 encoded string of the uploaded file.
![image](https://github.com/windmill-labs/windmill/assets/8110663/f41a052a-299a-4f9d-9afb-8fb9f1876f1d)

But in Apps, a File Input component returns base64 encoded string of the uploaded file **along with the Mimetype**. 
![image](https://github.com/windmill-labs/windmill/assets/8110663/9846ed8d-214f-4a2b-8642-4cfa915219c8)

This difference in behaviour is causing the underlying script to work perfectly fine in case of Flow but causing error for Apps.

Is there a way to get the same behave for the File Input fields/component?

### To reproduce

Script:
![Windmill-SampleScript](https://github.com/windmill-labs/windmill/assets/8110663/4116b30f-96c5-4a24-b652-c01d6837fd46)

Flow:
![Windmill-SampleFlow](https://github.com/windmill-labs/windmill/assets/8110663/d6917e4c-0a7b-4760-a213-6a51e8ce0692)

App:
![image](https://github.com/windmill-labs/windmill/assets/8110663/68517852-61fe-4c2d-8b27-e9b250065b6a)

### Expected behavior

I was expecting the same base64 encoded string for all the File Upload Input types.

**Comment by rubenfiszel** [comment]
Thanks for the issue, we will fix this by making the data prefix a component config of the app's file input component

**Comment by rubenfiszel** [comment]
@fatonramadani ^
