### ISSUE TITLE
bug: icon `Trash2` doesn't show up

### ISSUE THREAD

**Issue by takuyahara** [windmill-labs/windmill#1919]
### Describe the bug

When choosing icon `Trash2` it doesn't show up.

### To reproduce

1. Add "Table"
2. In "Table actions" click "Add Button"
3. Click the added button
4. In "Configuration -> After Icon" choose `Trash2`

It goes same on "Before Icon".

### Expected behavior

Icon `Trash2` shows up.

### Screenshots

![image](https://github.com/windmill-labs/windmill/assets/46240835/45e18019-78ed-40f1-b102-9766450b8433)

**Comment by rubenfiszel** [comment]
Can reproduce, @fatonramadani can you take a look please

**Comment by rubenfiszel** [comment]
@fatonramadani ^
