### ISSUE TITLE
feature: Allow Shared Directory to Work with Worker Groupa

### ISSUE THREAD

**Issue by ReaHe** [windmill-labs/windmill#1927]
Hello,

I am requesting the ability to allow the shared folder capability to work when specifying work groups for scripts in a flow. I discussed this a little bit in this discord message https://discord.com/channels/930051556043276338/930051556043276341/1132016347199590443.

Current Implimentation:
Right now is if a shared directory is checked/enabled for a flow, all worker groups seem to be dismissed and Windmill instead relies upon the worker group tags for the script type itself. I believe this is due to trying to maintain all scripts/tasks on the same worker to maintain the usability of the shared directory. However even when all the scripts specify the same worker group, this is still simply ignored.

Feature Request:
I would like to see this updated in two possible ways.
1. If all the worker groups are the same for all the scripts in the flow when the shared directory is Checked, the flow should execute on a worker in that provided worker group.
2. (My preferred way of seeing this updated) , if possible allow the shared directory to work even when different worker groups are used in a flow. In this case choose a dedi ated worker for each possible worker group needed and if a worker is allowed to participate in multiple groups, then make that worker be the dedciated worker for each possible group needed (if they're allowed). Then keep a shared directory per dedicated worker. BUT do not try and pass the shared directory between workers or anything like that. Instead leave it local to each worker that is participating in the flow.  And any tasks executed on those workers can use the shared directory that's local to the flow for the tasks provided to that worker. If another worker needs files from the other workers shared directory then a S3 cache or similar capability should be used.

The Way I Imagine Using This:
2 Windmill Workers with seperate groups
Group 1 - customer_1
Group 2 - monitoring_pod
These two workers work in seperate subnets that basically do not communicate with each other besides using Windmill.

Let's say I have a flow composed of 4 tasks:
1st task (group customer_1): is a bash script that goes and pulls a git repo, it then compiles whatever code it pulled into a binary and then places that binary into the shared directory
2nd (group customer_1): a python script is then executed to open the binary in the shared directory and perform some type of analysis, possibly looking for poor compiler optimizations in the code. After analyzing this information it then passes it to the 3rd task.
3rd (group monitoring_pod): the third task is another python script that then takes the analysis and posts it to a API such as elk to log the analysis and make it searchable. It then dumps the analysis with metadata in the shared directory.
4th (group monitoring_pod): this is a bash script that uses the logger command to push the analysis file in the shared directory to a syslog server.

In this example the shared directories are seperate from each other and only contain and work with the tasks executed on it. Overall I hope my example is somewhat detailed enough to paint the picture. Thx in advance whenever you take the time to look at this.

Very Respectfully,
ReaHe

**Comment by rubenfiszel** [comment]
We implemented this in a fashion that is similar to what you suggested in 1 in a0997911bf9da8651ddb830e9e09f2d3f82c73e4
