### ISSUE TITLE
feature: ACL/Permissions for Running Specific Worker Groups

### ISSUE THREAD

**Issue by ReaHe** [windmill-labs/windmill#1935]
Hello,

Due to a recent update from the changelog posted in discord https://discord.com/channels/930051556043276338/1054971402119286815/1133066786615603420 , whitelists/blacklists are being removed from workers. This feature however was providing the ability to restrict users from running specific worker groups by restricting access to particular workspaces. After discussing with the developer (https://discord.com/channels/930051556043276338/930051556043276341/1133459568626770052) there is currently no implimented fallback to continue to be able to restrict user access to workers when editing scripts or flows for workers on that windmill server instance.

Because of this I am requesting a feature to impliment the ability to restrict worker groups via workerspaces from the perspective of the windmill server and not windmill workers.

My Expectation:
In workspace settings (similar to where you edit user permissions to the workspace), specify which workgroups that workspace is allowed to run against.
By default I believe workspaces should always be able to run against the normal default tags, however custom tags should be automatically blocked on all workspaces unless explicitly allowed in the workspace settings.

How I Would Use This Feature:
Worker groups is pivotal to how I am want to use windmill in my network. I specifically deploy windmill workers in different network segments, that have specific accesses that other windmill workers will not have intentionally. I then use the workspaces as methods to provide specific users with access to specific workers they should have access too. For instance when I have a worker node deployed in a customer area that queries a specific API that the customer specifically has only allowed access for specific users, this is how I restrict that access. While also preventing every other user from querying that endpoint, this also helps segregate information for one user who should not see the output of specific scripts since they don't have workspace access either. From there the user who's allowed to see the data can extract specific fields that do not provide identifying information of the customer and can push it to a ELK server for searchable statistics.

Thanks in advance for taking the time to read this and I hope you consider implimenting this feature.

**Comment by rubenfiszel** [comment]
Done:

```
You can restrict some tags to specific workspace using the following syntax:

```
CUSTOM_TAGS=light,gpu(workspace+workspace2)
```
