### ISSUE TITLE
bug: connection test timeout mismatch

### ISSUE THREAD

**Issue by some-user123** [windmill-labs/windmill#1951]
### Describe the bug

I'm currently trying to establish a connection to a postgres database on the host machine and there seem to be network issues (different story ;-).

However, if I test the postgres connection to a host/port that's not responding, two things happen:

a) the script runs for a very long time. The timeout seems to be quite high (120s?). As this blocks a worker completely and you might retry this test within seconds you quickly end up with a queue full of connection tests, that nobody will ever see results of.

b) the frontend shows a message within a few seconds: "not found: Completed Job not found at name 018998e0-96d3-3641-88d3-c83795679137". So, as I user I don't get a good message, what's happened with my connection test.

I'd suggest: Timeout for connection test should be much lower (10s?). Frontend should wait for a corresponding time...

### To reproduce

1. Resources > Add a resource > postgresql
2. Host: 8.8.8.8, Port: 5432, ...
3. Test connection

### Expected behavior

Should display proper result (connection did not work: timeout)

### Application version

Windmill cloud

**Comment by appledesire** [comment]
Based on the information provided, it appears that there are two issues with testing the connection to a Postgres database when the host/port are not responding.

Firstly, the script seems to have a high timeout value (approximately 120 seconds) for the connection test. This extended timeout can cause the script to run for a very long time, blocking a worker completely. This can also lead to a queue full of connection tests that nobody will ever see the results of. To address this, it is suggested to lower the timeout for the connection test to a more reasonable value, such as 10 seconds.

Secondly, the frontend displays a misleading error message within a few seconds, stating "not found: Completed Job not found." This error message does not provide adequate information to the user about what has happened with their connection test. It is recommended to update the frontend to wait for a corresponding amount of time before displaying an error message, ensuring that the user receives accurate feedback on the status of their connection test.

**Comment by rubenfiszel** [comment]
you are exactly right @appledesire and I think the fix to both issues is pretty simple. After the fixed timeout of 5seconds by the frontend, we will cancel the job AND display a better error message saying it didn't complete in time.

Thanks for the report and feedbacks!

**Comment by rubenfiszel** [comment]
Fixed by #1988
