### ISSUE TITLE
bug: cannot convert between the Rust type `alloc::string::String` and the Postgres type `uuid`

### ISSUE THREAD

**Issue by some-user123** [windmill-labs/windmill#1957]
### Describe the bug

After reading postgres UUID (#1808) I would now like to use them as an key to update my db.

Postgres Action:

```sql
-- $1 id
-- $2 name
UPDATE table SET name = $2 WHERE id = $1
```

leads to 
```
The result keys are: error  
ExecutionError: error serializing parameter 0: cannot convert between the Rust type `alloc::string::String` and the Postgres type `uuid`
```

### To reproduce

Create a postgres action with above code and try to execute against a table where `id` column is of type UUID.

### Expected behavior

No error ;-)

As an alternative I wanted to execute the postgres query from typescript/deno. The hub contains example scripts with these imports:
```
import { pgClient, type Resource, type Sql } from "https://deno.land/x/windmill@v1.88.1/mod.ts";
```

However, `pgClient` is not available any more when import from v1.137.1. Is it not possible any more to use the db connection in typescript?

### Application version

CE v1.137.1-2-g7c354ef7

**Comment by rubenfiszel** [comment]
```
-- $1 id
-- $2 name
UPDATE table SET name = $2 WHERE id = $1
```

We need the type somehow, so can you try:

```
-- $1 id
-- $2 name
UPDATE table SET name = $2 WHERE id = $1::UUID
```

> However, pgClient is not available any more when import from v1.137.1. Is it not possible any more to use the db connection in typescript?

We now recommend to use the normal standard client of deno/npm instead of providing one with the client. The native Postgresql is the one layer providing the convenience so it's not necessary anymore.

**Comment by some-user123** [comment]
```sql
UPDATE table SET name = $2 WHERE id = $1::UUID
```
doesn't work either.

I'll try using the native postgresql client. (My hope was that windmill would not only provide the client for convenience but also keep the connection.)

**Comment by rubenfiszel** [comment]
What is the error ?

> I'll try using the native postgresql client. (My hope was that windmill would not only provide the client for convenience but also keep the connection.)

As a follow up, we will likely offer a syntax for multiple statement queries soon

**Comment by some-user123** [comment]
> What is the error ?

Still the same: `ExecutionError: error serializing parameter 0: cannot convert between the Rust type `alloc::string::String` and the Postgres type `uuid``

**Comment by rubenfiszel** [comment]
Uh, will fix soon, thanks for the report!

**Comment by rubenfiszel** [comment]
fixed in latest version! (wait a bit for build)
