### ISSUE TITLE
bug: cannot query a Numeric PostgreSQL value

### ISSUE THREAD

**Issue by TheOneValen** [windmill-labs/windmill#1967]
### Describe the bug

When create a PostgreSQL script where I want to query some data.

```
SELECT "date", speed, longitude
FROM synced_positions;
```

yields a

```
ExecutionError: conversion issue for value at column_name:longitude with type Numeric
```

Query without `longitude` yields expected result. Types in database:

date: timestamp
speed: int2
longitude: numeric(9, 6)

### To reproduce

1. Create a PostgreSQL script
2. Query
3. ExecutionError

### Expected behavior

Query result

### Application version

1.138

**Comment by rubenfiszel** [comment]
Fixed on latest, thanks for the report
