### ISSUE TITLE
Typo on site homepage

### ISSUE THREAD

**Issue by makasaurus** [windmill-labs/windmill#2]
**Describe the bug**
Typo under "UI? Done" section of homepage. Need a space between "scripts.Gain"

**To Reproduce**
1. Go to windmill.dev
2. Error

**Expected behavior**
A space between "scripts." and "Gain"

Let me know if you need more details. 😄

**Comment by rubenfiszel** [comment]
I am super grateful for the issue. I will fix it.

I just released the website opensource too in the meantime: https://github.com/windmill-labs/windmilldocs/
