### ISSUE TITLE
bug: adding/removing folders messes up items

### ISSUE THREAD

**Issue by some-user123** [windmill-labs/windmill#2028]
### Describe the bug

When adding a new folder, the "statistics" (like number of resources, variables...) for the new folder isn't 0 (as you would expect for a newly created folder) but taken from a different folder. Once the page is refreshed, the statistics are correct.

Similarly, items get messed up, when removing a folder from the list.

### To reproduce

1. Create a folder and add some content:
![image](https://github.com/windmill-labs/windmill/assets/74715856/1ebc901a-f9e5-41c5-95e9-3763f4a2e472)

2. Add another folder
![image](https://github.com/windmill-labs/windmill/assets/74715856/879d301b-b773-4672-a27d-95e97f75bbcf)

3. Refresh
![image](https://github.com/windmill-labs/windmill/assets/74715856/7c784bcd-e29c-4b7f-b7d4-16c75b469445)

4. Delete folder
![image](https://github.com/windmill-labs/windmill/assets/74715856/f6df9e9e-417f-4f9b-b680-031298008111)

5. Refresh
![image](https://github.com/windmill-labs/windmill/assets/74715856/778f66f2-a3a9-40fd-917d-cece70c4d963)

### Expected behavior

Numbers always correct.

### Application version

CE v1.144.4-6-g891d1207

**Comment by rubenfiszel** [comment]
Fun bug @fatonramadani , thanks for the report

**Comment by rubenfiszel** [comment]
Fixed on latest
