### ISSUE TITLE
bug: sporadic dependency management errors

### ISSUE THREAD

**Issue by vrachev** [windmill-labs/windmill#2035]
### Describe the bug

I created a very basic langchain script, and 5% of the time I run the script it succeeds, the other 95% I run into a dependency resolution error. No changes to the script. I added screenshots with a successful run and errant run. 

I created the script several times and it reproduced each time.

### To reproduce

1. Paste in following script:

```
import { ChatOpenAI } from "npm:langchain/chat_models/openai";
import { ChatMessage, HumanMessage, SystemMessage } from "npm:langchain/schema";

type Openai = {
  api_key: string;
  organization_id: string;
};

export async function main(
  openAIAuth: Openai,
) {
  const chat = new ChatOpenAI({
    temperature: 0,
    openAIApiKey: openAIAuth.api_key,
  });

  const result = await chat.predictMessages([
    new HumanMessage(
      "Translate this sentence from English to French. I love programming.",
    ),
  ]);

  return result;
}
```

2. Add OpenAI auth resource

3. Run test execution until both you see both successful and errant runs.

### Expected behavior

Consistent output

### Screenshots

<img width="1345" alt="Screen Shot 2023-08-11 at 5 10 05 PM" src="https://github.com/windmill-labs/windmill/assets/4767834/c002ca3f-7554-4a82-8c10-2feed64cc569">
<img width="1336" alt="Screen Shot 2023-08-11 at 5 09 54 PM" src="https://github.com/windmill-labs/windmill/assets/4767834/c7516ad3-8855-4659-a446-85022db39539">

### Application version

EE v1.145.1

### Additional Context

If we rewrite the above script to just use the base model and not the chat model, no dependency errors occur. Here's the script:

```
import { OpenAI } from "npm:langchain/llms/openai";

type Openai = {
  api_key: string;
  organization_id: string;
};

export async function main(
  openAIAuth: Openai,
) {
  const llm = new OpenAI({
    temperature: 0,
    openAIApiKey: openAIAuth.api_key,
  });

  const result = await llm.predict(
    "Translate this sentence from English to French. I love programming.",
  );

  return result;
}
```

**Comment by rubenfiszel** [comment]
This is an interesting case. I assume that you are on the cloud app. The only possibility for this is that there are different version cached depending on the workers. I think the problem should disappear were you to pin the version. I will investigate and share my findings.

**Comment by vrachev** [comment]
Thanks @rubenfiszel, pinning the version fixed the issue and should be sufficient to unblock me. And yes this happened on the cloud app. Let me know if there's more info that can help with the general issue.

**Comment by rubenfiszel** [comment]
I think it's a deno issue and will probably be fixed in a future update of deno.

In the meantime, this works everytime with bun:
```
import { ChatOpenAI } from "langchain/chat_models/openai";
import { ChatMessage, HumanMessage, SystemMessage } from "langchain/schema";

type Openai = {
  api_key: string;
  organization_id: string;
};

export async function main(
  openAIAuth: Openai,
) {
  const chat = new ChatOpenAI({
    temperature: 0,
    openAIApiKey: openAIAuth.api_key,
  });

  const result = await chat.predictMessages([
    new HumanMessage(
      "Translate this sentence from English to French. I love programming.",
    ),
  ]);

  return result;
}
```

And we are soon gonna make bun as prominent as our deno runtime.

**Comment by vrachev** [comment]
Thanks. Can I use bun in the cloud app? Couldn't find a setting and it defaults to using Deno (which fails):

```
Relative import path "langchain/chat_models/openai" not prefixed with / or ./ or ../ and not in import map from "file:///wuw6hgntru.ts"deno(resolver-error)
```

**Comment by rubenfiszel** [comment]
@vrachev it's one of the language, bun is one of the last one in the language menu. We will likely promote bun to replace deno as the primary language in not too long

**Comment by vrachev** [comment]
Thanks, I found it - didn't realize at first that the TS icon was a clickable button.

**Comment by vrachev** [comment]
Feel free to close if this goes away with Bun being the main runtime.

**Comment by rubenfiszel** [comment]
We did some massive improvements to the Bun runtime and are working toward marking it as non-experimental soon!
