### ISSUE TITLE
feature: Switch to a minimalist base container image (ex. Chainguard or distroless)

### ISSUE THREAD

**Issue by Jared314** [windmill-labs/windmill#2039]
While the impact on security is debatable, a container that is "green" on security scans streamlines self-host / on-prem adoption where policy requires such scans.

**Comment by rubenfiszel** [comment]
Do you experience doing this ? Would you be willing to try and experiement ?

**Comment by Jared314** [comment]
I have some experience in doing this on internal images. I would be willing to experiment switching out the base images.
