### ISSUE TITLE
bug: "Add variable" button in cloud app adds import statement with wrong version

### ISSUE THREAD

**Issue by vrachev** [windmill-labs/windmill#2041]
### Describe the bug

When I click to add a variable in Deno, windmill adds an import statement, but the version doesn't exist in deno.land (the prior version does). 

It added
```
import * as wmill from "https://deno.land/x/windmill@v1.145.3/mod.ts";
```

probably because I'm on version v1.145.3 of windmill, but that version hasn't been published to deno.land yet. Changing to 1.145.2 solved the issue for me, but figured I'd cut a ticket for the small UX bug. 

### To reproduce

Mentioned above. 

### Expected behavior

add the correct version in the import statement.

### Application version

EE v1.145.3-1-g4dcf7ae0

**Comment by rubenfiszel** [comment]
Fixed! There was a problem in publishing that version to deno.land
