### ISSUE TITLE
feature: Confusing variable type mismatch

### ISSUE THREAD

**Issue by vrachev** [windmill-labs/windmill#2042]
This may have already been discussed before, but figured I'd bring up in case it hasn't. 

When you add a parameter of a built in type (perhaps not just built in but haven't tested), the object is passed in. For gsheets auth this looks like
```
{token: mysecret}
```

When you embed the variable 
```
await wmill.getVariable("u/vrachev/gsheets_auth")
```
I was surprised that it loaded the literal string value of the secret, as opposed to the object above. Is this behavior intentional? Thanks

**Comment by rubenfiszel** [comment]
Variables are just strings, resources are objects that may contain linked variables, especially in the context of sensitive values, in which case it's not just a variable but a secret variable.

You are looking for:
```
await wmill.getResource("u/vrachev/gsheets_auth")
```
