### ISSUE TITLE
Deno + nsjail documentation

### ISSUE THREAD

**Issue by Palmik** [windmill-labs/windmill#2078]
Hello,

Your documentation makes it sound like you combine the Deno sanbdoxing with nsjail: https://github.com/windmill-labs/windmill/blob/dafc7c24b051e91cb71ef16121b94c0030273ee5/README.md?plain=1#L173

But when I looked at the implementation, it seemed that when executing TypeScript with Deno, you don't do so in nsjail: https://github.com/windmill-labs/windmill/blob/main/backend/windmill-worker/src/worker.rs#L1758

Can you please help clarify?

**Comment by rubenfiszel** [comment]
@Palmik We used to use both but there wasn't any need for deno since deno's sandboxing capabilities are sufficient for the multi-tenant instance. Deno is the only language for which instead of using nsjail we just tighten the permission flags. I reworded that part of the README. Thank you for bringing it up.

**Comment by Palmik** [comment]
I see, thanks for the explanation. I am surprised that deno is enough, afaik Cloudflare Workers use sandboxing on top of V8 isolates (what deno relies on as well): https://developers.cloudflare.com/workers/learning/security-model/

**Comment by rubenfiszel** [comment]
@Palmik yes, they have a different security model. Our workers are isolated with docker containers, and each worker run only 1 job at a time (except for native jobs but those do not interpret arbitrary code) whereas they run the v8 isolates on the same v8. So maybe I should have mentioned that we actually have a second layer of sandboxing through docker on our multi-tenant/cloud instance.

Furthermore, all the jobs data are ephemeral.  Is all of the above enough to guaranty complete security ? It would seem to me that yes it is but we welcome any security experts finding vulnerability in this scheme and helping us making it more secure.
