### ISSUE TITLE
loading feedback when clicking on the pagination buttons

### ISSUE THREAD

**Issue by renatocaliari** [windmill-labs/windmill#2089]
I miss having loading feedback when clicking on the pagination buttons of the Table component. 

Maybe they could have visual feedback similar to the submit button, and perhaps the table itself could indicate that it is updating the content.

I hope that the new [pagination functionality in the List component](https://github.com/windmill-labs/windmill/issues/2088) can also align with this.

**Comment by fatonramadani** [comment]
Added in both tables and lists!
