### ISSUE TITLE
High default timeout

### ISSUE THREAD

**Issue by vrachev** [windmill-labs/windmill#2099]
Had an execution last night that ran for 90 minutes until it timed out. 
<img width="323" alt="Screenshot 2023-08-16 at 3 34 22 PM" src="https://github.com/windmill-labs/windmill/assets/4767834/b20f93b3-7afc-4d29-b835-19d4f1f2df0b">

Seems like a very high timeout, given that it eats up roughly half of the allotted monthly requests in the team plan (assuming 1 member). I've since added timeouts to each step but would be great to have a global variable I can set.  

[Link to task](https://app.windmill.dev/run/0189fc33-b435-d935-7007-cfdb443406ec?workspace=irregex).

Thanks as always.

**Comment by rubenfiszel** [comment]
You are on a premium workspace so you have a higher timeout permitted. I agree right now the timeout story could be improved now that it's possible to set the timeout per-step, but it's not a bug per-se, more of a feature working as intended but maybe not optimal.

**Comment by rubenfiszel** [comment]
The planned improvement is to have a default timeout settable per workspace, overridable at the script and step level. The workspace timeout cannot be higher than the instance timeout and the instance timeout is different for premium and non premium workspace on cloud (self-hosted can be set at any value)

**Comment by vrachev** [comment]
Thanks, makes sense. Setting timeouts at the step level works fine, but would would love workspace/flow/script level timeouts when you get around to it. Also worth documenting the current timeout defaults.

**Comment by rubenfiszel** [comment]
Yes, we will revamp timeout very soon and document it properly. Timeout are the most common questions we get, even for self-hosted. Let me write it here for posterity.
Currently, non-premium workspace on cloud have 300s timeout. Premium workspaces have 18 times that.
On self-hosted instances, the instance-wide timeout is set with the TIMEOUT environment variables.

**Comment by vrachev** [comment]
Thanks, I tried to search around but missed any comments from others.
