### ISSUE TITLE
feature: Allow setting custom headers on graphql requests

### ISSUE THREAD

**Issue by ManavDia** [windmill-labs/windmill#2101]
Hi love the new Graphql feature, but the API I need to interact with requires a custom header. Is it possible to set the headers on the graphql requests, as this would be a common scenario for a lot of graphql APIs.

**Comment by youtiaoguagua** [comment]
I think this is necessary, and we can get the request header through an API.

**Comment by rubenfiszel** [comment]
![image](https://github.com/windmill-labs/windmill/assets/275584/179723ba-847b-4097-9d96-417a6e1e1b04)

The new graphql resource type supports custom_headers. Be sure to sync your resource types for this to appear.
