### ISSUE TITLE
feature: use dynamic number of parameters in postgres script (bulk insert)

### ISSUE THREAD

**Issue by some-user123** [windmill-labs/windmill#2105]
I'd like to bulk INSERT a large number of rows to a postgres database.

Looping over them is not very efficient and slow. Instead, I'd like to put them all in one statement like this:

```sql
INSERT INTO table (id, value) VALUES (1, 'foo'), (2, 'bar');
```

Unfortunately, the number of rows (two in above example) is not known in advance. I think, currently, that's not possible using a postgres script.

**Comment by SindreSvendby** [comment]
You can use another script (like TS/python or another) and then programmatically create your insert and send it to the database. 

Will that meet your needs or do you see any drawbacks using that approach?

**Comment by rubenfiszel** [comment]
Agree with Sindre, the goal of our postgres integration is to be prepared statements (which has some performance implications). For anything that fall outside of this, one should use python/typescript.

**Comment by some-user123** [comment]
Given that there is a postgres script type, my initial thought was, that I should use it for postgres queries. Obviously, I've hit a limitation here.

Going back to typescript/python/go would be a workaround. However, I haven't figured out yet how to use ORM libraries there (#1826). ORM libraries often provide bulk insert functionality, making it very simple to work with an array/list of objects. At the same time these libraries make sure, SQL injection is prevented.
Working with lists/large amount of data in windmill, doesn't seem to be uncommon to me. So, I thought, it's a good idea, to improve functionality to work with lists in the postgres script type, e.g. by some macro. Up to your decision, of course.

**Comment by rubenfiszel** [comment]
My reasoning is that whatever macro/dsl I will invent that is not canonical postgresql/mysql is gonna end up being a worse language than minimal typescript.

The only con I see of typescript vs macro is that one has to copy paste the snippet to execute a query in typescript.

However, since we will still want to improve the experience of being able to use typescript/python with db, I rather improve the DX in those languages than invest too much in a macro SQL language.

**Comment by rubenfiszel** [comment]
WONT DO for now
