### ISSUE TITLE
Allow graphql script to accept dynamic headers not only bearer token

### ISSUE THREAD

**Issue by murunwas** [windmill-labs/windmill#2112]
### Describe the bug

trying to use graphql script but  it only accepts bearer token header. my graphql endpoint require custom header `x-token` to authenticate.

![image](https://github.com/windmill-labs/windmill/assets/8838943/c68b1845-8b43-4081-b078-0bd0084b4c3e)

### To reproduce

1. Click scripts button
2. Choose `Graphql` laguage
3. Click add resource as shown below
![image](https://github.com/windmill-labs/windmill/assets/8838943/b615a5af-f5d4-4a81-96ea-7efd5dda80cb)

### Expected behavior

able to add custom headers

**Comment by rubenfiszel** [comment]
Same as #2101
