### ISSUE TITLE
bug: schedule for flow: time zone inconsistent & dark mode unreadable

### ISSUE THREAD

**Issue by some-user123** [windmill-labs/windmill#2120]
### Describe the bug

1. When creating a schedule for a flow and using the simplified builder, I can set the timezone and the UTC time. The time (e.g. 10:00) is interpreted within the selected time zone (e.g. Addis Ababa), not UTC. It might be better to call this field "At time" instead of "At UTC time".
![image](https://github.com/windmill-labs/windmill/assets/74715856/7bbc5cb2-a105-4b3d-9164-c75d3fbff8ca)

2. In dark mode, the drop downs for day of the month, day of week, etc. are not readable. (Drop down for timezone is always in light mode, therefore readable.)
![image](https://github.com/windmill-labs/windmill/assets/74715856/1a64a3a4-fa8c-4def-8317-e696984f6161)

### To reproduce

See above

### Expected behavior

Consistent & readable ;-)

**Comment by rubenfiszel** [comment]
done
