### ISSUE TITLE
bug: cannot disable retries

### ISSUE THREAD

**Issue by some-user123** [windmill-labs/windmill#2133]
### Describe the bug

In the UI linear and exponential retries can be enabled/disabled separately. Doesn't work properly.

### To reproduce

1. Create flow
2. Create action
3. Enable linear retries for this action
4. Deploy
5. Edit again, expected: exponential retries are disabled, actual: exponential retries are enabled
6. Disable both linear and exponential retries
7. Deploy
8. Edit again, expected: all retries are disabled, actual: all enabled

### Expected behavior

Deploy and Edit should not change state.

### Application version

EE v1.151.2

**Comment by rubenfiszel** [comment]
It's fixed on last commit
