### ISSUE TITLE
bug: cannot get resource or variable in windmill self-hosted instance when using http_proxy env

### ISSUE THREAD

**Issue by VaalaCat** [windmill-labs/windmill#2149]
### Describe the bug

cannot get resource or variable in windmill self-hosted instance when using http_proxy/https_proxy env even if I fresh install it from docker-compose several times

### To reproduce

1. Create new script and variable
2. Click on run script
3. See error

### Expected behavior

return "test"

### Screenshots

<img width="1409" alt="image" src="https://github.com/windmill-labs/windmill/assets/42285362/434145f1-5fd9-4d16-86ce-7f08ad4cd216">
<img width="1366" alt="image" src="https://github.com/windmill-labs/windmill/assets/42285362/2abd357a-ce30-4e65-96a8-e4dce42d7dc0">

### Application version

CE v1.154.0-1-gab8a27f1

**Comment by rubenfiszel** [comment]
@VaalaCat did you figure that one out ?

**Comment by rubenfiszel** [comment]
I think you can simply add localhost to no_proxy

**Comment by VaalaCat** [comment]
> @VaalaCat did you figure that one out ?

yes, I just add localhost to no_proxy and problem solved.

wish windmill could provide a way pass http_proxy/https_proxy to script or deno. Which many package use this env as default proxy, it's hard to modify every package's behavier in windmill without provide those two envs for now.
