### ISSUE TITLE
bug: args not being sent to script with custom UIs

### ISSUE THREAD

**Issue by AndreTeixeira1998** [windmill-labs/windmill#2172]
### Describe the bug

I am unable to pass arguments to scripts. When using the Windmill React Template given for custom UIs, trying to execute a Workspace script by it's path, the script is executed but the arguments are undefined during it's execution.

### To reproduce

Clone [the latest Windmill React Template ](https://github.com/windmill-labs/windmill-react-template.git)
Change the following function: 
```
  async function executeTest() {
    setLoading(true);
    const result = await executeWorkspaceScript("u/your_script/path", {
      x: "Bar",
    });
    setLoading(false);
    setResult(result);
    console.log("arg", arg);
    console.log("result", result);
  }
```

create the following Deno script using the Windmill UI and change "u/your_script/path" to the created workspace script path.

```
export async function main(x: string) {
  console.log("Hello from test.ts");
  return foo(x);
}

function foo(x: string): string {
  return "FOO: " + x;
}
```

### Expected behavior

expected output: FOO: Bar

Actual Output: FOO: undefined

**Comment by rubenfiszel** [comment]
I updated the template, it should work now: https://github.com/windmill-labs/windmill-react-template/commit/1bdaa3bbf148c724dd98aad1955dbf03438eed5b

**Comment by AndreTeixeira1998** [comment]
Thanks 

that was it
