### ISSUE TITLE
bug: Not able to set up Digital Ocean Postgres DB with sslmode : require

### ISSUE THREAD

**Issue by ampsarfraz** [windmill-labs/windmill#2184]
### Describe the bug

I am trying to connect to a postgres database on digital ocean which has sslmode : require. I get an error 'The certificate used to secure the TLS connection is invalid' for this scenario
{
  "password": "xxxxx",
  "sslmode": "require",
  "dbname": "defaultdb",
  "user": "doadmin",
  "host": "xxxxxxx.db.ondigitalocean.com",
  "port": 25060
}

### To reproduce

Add postgres resource with below connection details

{
  "password": "xxxxx",
  **"sslmode": "require",**
  "dbname": "defaultdb",
  "user": "doadmin",
  "host": "xxxxxxx.db.ondigitalocean.com",
  "port": 25060
}

### Expected behavior

Should connect without any errors.

**Comment by rubenfiszel** [comment]
We need to add the certificate as a value you can pass to the resource type postgresql

**Comment by ampsarfraz** [comment]
Can you please provide a json sample that we can use?

**Comment by rubenfiszel** [comment]
I've just pushed a fix so that "Test Connection" actually use the backend driver instead of another frontend library. I've then tested with a newly created DO db and it worked without additional CA certificate. You might want to give a try with latest

**Comment by rubenfiszel** [comment]
Also, Root certificate support has been added with the new field: `root_certificate_pem` for the postgresql resource type

**Comment by ampsarfraz** [comment]
Thank you.
