### ISSUE TITLE
bug: Not able to add a Graphql Resource  to Hasura endpoint

### ISSUE THREAD

**Issue by ampsarfraz** [windmill-labs/windmill#2185]
### Describe the bug

Tried to set up a resource as a Hasura Instance and got the below error.

{
  "base_url": "https://xxxx/v1/graphql",
  "content-type": "application/json",
  "X-Hasura-Admin-Secret": "xxxx",
  "bearer_token": ""
}

error during execution of the script: Malformed Authorization header

### Expected behavior

Should work properly

**Comment by rubenfiszel** [comment]
Could you share how your hasura instance is setup so we can reproduce please.

**Comment by rubenfiszel** [comment]
Also, can you test if the equivalent fetch/curl request would be valid by writing it by hand

**Comment by ampsarfraz** [comment]
Hasura Instance is setup on Digital Ocean and currently a different application uses it and we are able to query it through Postman as well. 

Please find below a screenshot from Postman.

![image](https://github.com/windmill-labs/windmill/assets/23452573/ef7467f2-5dbd-4074-98ee-b6b9faaf10d3)

**Comment by rubenfiszel** [comment]
Thanks for this, I will investigate shortly

**Comment by rubenfiszel** [comment]
I think maybe you didn't follow the resource type struct, here is what you should see for instance (I tested with a webhook catcher):
![image](https://github.com/windmill-labs/windmill/assets/275584/f9b36f91-0e37-41bf-b8f4-de64d106fd3d)
![image](https://github.com/windmill-labs/windmill/assets/275584/1bbdc4c0-2bef-444e-a045-055075adcfd7)

And here is the result as expected:
![image](https://github.com/windmill-labs/windmill/assets/275584/375bb8f5-d901-4a61-9e38-54bb3036cea5)
