### ISSUE TITLE
feature: define flow result

### ISSUE THREAD

**Issue by TheOneValen** [windmill-labs/windmill#2195]
Hi!

I have a proposition:

Currently all results in a flow are somehow collected and become the flow result. I would like to be able to define (like with inputs) what of all the results shall be the flow result.

What do you think?

Have a great day!

**Comment by rubenfiszel** [comment]
I'm not sure to understand the point, you can always do a script that filter the wanted fields only

**Comment by TheOneValen** [comment]
All run views and the schedule view do show the flow results. I would like to sometimes hover to see the results. A script at the end would work too, i guess. This is more an convenience thing to just define the flow result as you do with inputs.
