### ISSUE TITLE
feature: flow - Copy input's schema from direct input

### ISSUE THREAD

**Issue by ImSingee** [windmill-labs/windmill#2203]
<img width="1393" alt="image" src="https://github.com/windmill-labs/windmill/assets/11208082/987c47cd-6313-4089-b709-1d42c9abb0cb">

Now, we already can generate a flow schema from a request. But sometimes, our input is from another source or cannot be reproducible easily, but we have a JSON representation of it.

Now, what I have to do is use another util (e.g., curl or paw) to send the data to the request manually. I think it would be nice if we could directly paste a JSON and generate the schema from it.

**Comment by rubenfiszel** [comment]
Will do, thanks for the suggestion!

**Comment by fatonramadani** [comment]
Done in: https://github.com/windmill-labs/windmill/pull/2352
