### ISSUE TITLE
feature: use workspace name in the windmill app url

### ISSUE THREAD

**Issue by rauanmayemir** [windmill-labs/windmill#2206]
Currently, workspace is used implicitly as a context in the windmill web app, so switching a workspace doesn't affect much except for re-rendering the page.

But if you have several workspaces, passing a link to an app/flow/run to your colleague becomes a nigthmare and a hassle with selecting the correct workspace. I've been dealing with a similar issue in my work and ultimately decided to use explicit contexts.

So instead of using urls like `https://app.windmill.dev/runs/018a4a7d-0345-f250-833a-13784f759f74` I would suggest using something like `https://app.windmill.dev/workspace/workspace_name/runs/018a4a7d-0345-f250-833a-13784f759f74` or even `https://app.windmill.dev/workspace_name/runs/018a4a7d-0345-f250-833a-13784f759f74`.

**Comment by rubenfiszel** [comment]
You can always force the workspace by setting it as a query arg:
```
<url>?workspace=X
```

We should probably set it in the url in more contexts but normally most UUIDs url contain it. If you have example where that's not the case, we will fix it.

**Comment by rauanmayemir** [comment]
By default, urls will only show `/runs/uuid`. So a non-technical employee would simply copy a browser url and send it. Then the other side will see this:
![image](https://github.com/windmill-labs/windmill/assets/9691/9e34ab13-4011-4738-aa0d-3ad98fabd56c)

**Comment by rubenfiszel** [comment]
I agree with what you are saying and that is what I was trying to save above wrt to the uuids. Normally, all the urls that leads to those uuid have the workspace attached as query arg for the reason you mention. When that is true, the url to copy and share has the workspace specified in it. I will do another pass on our internal links to make sure that is always the case and update it here.

**Comment by rubenfiszel** [comment]
This should be fixed in: https://github.com/windmill-labs/windmill/commit/d311d76557432a72a5d6d7ab010aeb1fe0e599de
