### ISSUE TITLE
feature: custom public url

### ISSUE THREAD

**Issue by f3l1x** [windmill-labs/windmill#2209]
Hi! ✋ 

At first, awesome tool, truly is.

I would really appreciate if we can host our public app under custom domain. It would increase UX of our users, for now we have some all apps under the docs/confluence page.

I've tried nginx/caddy as reverse proxy, but it looks like that domain path is crucial at this moment for JS app. I can imagine that we can send some header downstream, like `X-Windmill-AppId` and it would render in JS app.

But, it's up to you. Thanks.

```js
<script>
	{
		__sveltekit_hppeja = {
			base: "",
			env: {}
		};

		// Render from backend somehow?
		const appId = '1234567890';

		const element = document.currentScript.parentElement;

		Promise.all([
			import("/_app/immutable/entry/start.30d4de58.js"),
			import("/_app/immutable/entry/app.60673d04.js")
		]).then(([kit, app]) => {
			kit.start(app, element);
		});
	}
</script>
```

**Comment by rubenfiszel** [comment]
Thanks for the kind words.

Yes we do plan to make windmill apps embeddable as simple widgets apps mountable on arbitary divs but this will likely require the enterprise edition. If you would be open to it, we could do a pilot and prioritize this item.

**Comment by f3l1x** [comment]
Hi @rubenfiszel. I need to discuss it on our side, but I assume we are not planning to switch to enterprise version at this moment.

**Comment by oliverbj** [comment]
@rubenfiszel was this change completed? We are interested in being able to change the public URL and is running an EE license.

**Comment by rubenfiszel** [comment]
Hi @oliverbj , not yet but given your needs, we will re prioritize it
