### ISSUE TITLE
bug: Cannot see run detail for specific run

### ISSUE THREAD

**Issue by ImSingee** [windmill-labs/windmill#2215]
### Describe the bug

Cannot see run detail for specific run (route: `/runs/UUID`)

### To reproduce

1. Go to Home page and open a flow
2. Click on one item under the "previous runs" (See run detail in a new tab)
3. The list will always be empty

<img width="486" alt="image" src="https://github.com/windmill-labs/windmill/assets/11208082/efa3893c-c0dd-457b-8ce5-f1c8c82cfb0e">

<img width="523" alt="image" src="https://github.com/windmill-labs/windmill/assets/11208082/1b89ce87-72ce-4b33-8fcd-5be40ea7a412">

<img width="1283" alt="image" src="https://github.com/windmill-labs/windmill/assets/11208082/72931394-e7d3-4147-a446-06ab50c565ca">

### Expected behavior

See the detail for specific run

### Application version

v1.165.0

**Comment by rubenfiszel** [comment]
Fixed in https://github.com/windmill-labs/windmill/commit/719a7b11da81f68452ba9fc22ff456fe1ddde1de
