### ISSUE TITLE
bug: webhook payload can not be a list

### ISSUE THREAD

**Issue by ykorzikowski** [windmill-labs/windmill#2221]
### Describe the bug

It's not possible sending a valid json payload containing a list to windmill. Its only possible to send a json object. 

### To reproduce

Create a new Flow and send a json-list as payload. 

This will fail: 
```
curl -X POST https://windmill.vpn.swokiz.com/api/w/l...    -H 'Content-Type: application/json'    -d '[{"foo": 42}]'
```

### Expected behavior

This will not fail:

```
curl -X POST https://windmill.vpn.swokiz.com/api/w/l...    -H 'Content-Type: application/json'    -d '[{"foo": 42}]'
```

**Comment by rubenfiszel** [comment]
It's not really a bug but intended. We need to know to what parameter name to assign your payload. This is why we extract it from a json object and require the payload to be a json object. Do you have a use-case where you cannot pass:
```
{foo: list}
```
and process with a main function as follows:
```
def main(foo):
     ....
```

instead ?

**Comment by ykorzikowski** [comment]
Yas, I am using EspoCRM Webhook feature which is sending a json list instead of ana object. 

My current workaround is using a N8N Workflow splitting this list in multiple windmill.dev requests.

**Comment by rubenfiszel** [comment]
> My current workaround is using a N8N Workflow splitting this list in multiple windmill.dev requests.

:smile: 

I had on my-todo list to solve https://github.com/windmill-labs/windmill/issues/2217 this afternoon which would also solve this :)

**Comment by ykorzikowski** [comment]
Yes it was not my intention to have 2 workflow engines :D

But it sounds nice :) I can't wait to test this

**Comment by rubenfiszel** [comment]
Turn out it was already solved, your list will just be passed in the arg `body`
