### ISSUE TITLE
bug: scheduled flows are not updated properly

### ISSUE THREAD

**Issue by BigBerny** [windmill-labs/windmill#2238]
### Describe the bug

I noticed for the second or third time that when I modify a scheduled flow the scheduler still runs the old version. As confirmed by Ruben, the first iteration after a flow modification will not run the updated code yet but only the next one. It would be awesome if you could fix that.

### To reproduce

1. Create flow that runs every week
2. Modify the flow
3. The next week it will still run the old flow
4. Afterwards it should run the new code (based on Ruben's message, can't confirm)

### Expected behavior

Updates to flows should take effect immediately. The next time a scheduled flow is run, it should already run the latest version.

**Comment by rubenfiszel** [comment]
That problem is likely to have already been solved looking at the code and since you were on 1.88 which is pretty old. Can you confirm you still have the same issue on latet?
