### ISSUE TITLE
feature: obtaining website hostname

### ISSUE THREAD

**Issue by zeeeeby** [windmill-labs/windmill#2266]
Hello,

I'm trying to set up automatic error alerts in Slack. I want to create a message like `<https://windmill.a.b.com/run/${flow_id}?workspace=${workspace}|${flow_id}>` but I'm facing the challenge of not knowing how to obtain the hostname `https://windmill.a.b.com/` (hardcoding the value is not suitable).

I couldn't find anything suitable in `Deno.env`, and the closest keys have these values.

```
WM_BASE_URL: "http://windmill",
BASE_INTERNAL_URL: "http://localhost:37969",
```

Is there any way to obtain what I want?

**Comment by rubenfiszel** [comment]
Hi @zeeeeby ,

WM_BASE_URL is what you want and you need to pass it as env variable to the container which done by the .env in the docker-compose:

https://github.com/windmill-labs/windmill/blob/main/.env#L13
