### ISSUE TITLE
bug: Unable to access user list for org: Sql error: error occurred while decoding column "executions": mismatched types; Rust type `i64` (as SQL type `INT8`) is not compatible with SQL type `NUMERIC`

### ISSUE THREAD

**Issue by djpecot** [windmill-labs/windmill#2284]
### Describe the bug

As the org admin, I am unable to see/manage users within my organization. However, I can still add users currently that I am aware of:

<img width="1036" alt="Screenshot 2023-09-14 at 12 08 31 PM" src="https://github.com/windmill-labs/windmill/assets/8185181/aa249bfa-6827-4e0a-a60f-5e4f236785e7">

Could just be an issue with my account/org.

### To reproduce

As an admin, check the users currently active. 

### Expected behavior

List of current users within my org.

### Screenshots

<img width="1036" alt="Screenshot 2023-09-14 at 12 08 31 PM" src="https://github.com/windmill-labs/windmill/assets/8185181/205ffbad-2202-4500-9799-1dd6d8959e1b">

### Browser information

Version 1.56.14 Chromium: 115.0.5790.114 (Official Build) (x86_64)

### Application version

EE v1.172.1-6-g92a00a20

**Comment by rubenfiszel** [comment]
It's fixed already but we didn't redeploy, redeploying now
