### ISSUE TITLE
bug: Python scripts fail if username begins with number

### ISSUE THREAD

**Issue by JGtHb** [windmill-labs/windmill#2292]
### Describe the bug

All Python scripts seem to fail with `SyntaxError: invalid decimal literal` if the owning user's name begins with a number and also contains letters. (It will fail with a slightly different invalid syntax if the user name contains only numbers) I suspect this is because Python identifiers can not start with a number.

### To reproduce

1. Create a new user with a 'name' that begins with a number and also contains letters.
2. Log into the user and create a new Python script using your name as your workspace username.
3. Run the default python script. Observe that it errors with SyntaxError: invalid decimal literal.

### Expected behavior

Usernames that begin with a number can successfully run Python scripts, or usernames are validated on creation to prevent them from beginning with a number.

### Application version

CE v1.173.0-10 (Selfhosted)

**Comment by rubenfiszel** [comment]
Thank you for the report, on latest version, we now validate more strongly that the username must start with a letter as suggested
