### ISSUE TITLE
feature: Rich Results customisation

### ISSUE THREAD

**Issue by dm-canteen** [windmill-labs/windmill#2293]
I would love some more options with the Rich Results component, which I use a lot to display Pretty JSON objects to the user:

1. **Custom header text:** The 'Results' text should be editable via a parameter.
2. **Toggle _Result Keys, Clipboard, Maximise_**: The whole `<div>` should be able to be toggled on/off similar to "Hide Refresh Button" on Tables.

![image](https://github.com/windmill-labs/windmill/assets/109326069/653ad79d-a7d9-4d3b-85b1-e833ee972c70)

Additionally, after recent changes there is a **Styling > Show** menu which is currently blank for Rich Results, it would be nice to have an option to override some CSS for the results as well  (#2057?):
![image](https://github.com/windmill-labs/windmill/assets/109326069/74473f97-2d1e-4f6d-8a76-50a617245f54)

**Comment by rubenfiszel** [comment]
@fatonramadani can you take a look at this. The missing component styling seems like a bug and the rest is reasonably easy to do

**Comment by dm-canteen** [comment]
Fixed by https://github.com/windmill-labs/windmill/pull/2294

**Comment by mmospanenko** [comment]
Can't copy in VSCode, how to debug?
<img width="329" alt="image" src="https://github.com/windmill-labs/windmill/assets/2766211/8a245e37-58fa-4c63-96f4-be891078f2e3">

**Comment by djm2k** [comment]
@mmospanenko looks like a new issue caused by lack of clipboard permission on the plugin side

**Comment by mmospanenko** [comment]
yeah, seems permissions, I don't have any ideas where to change it(
