### ISSUE TITLE
bug: Postgresql resource no longer working

### ISSUE THREAD

**Issue by Incisive** [windmill-labs/windmill#2334]
### Describe the bug

I'm self hosting windmill on an EC2 instance, connected to an RDS database. When creating a "resource" using the same credentials given to the Windmill server it is having a hard time resolving/connecting to the database.  All the flows/script I have that use that same database from an application level function fine, however the Windmill resource aspect seems broken after I recently updated the stack to the latest versions of windmill.

Clearly all my security groups are functioning as the Windmill server itself uses this same DB and is accessing it fine.

Thanks!

### To reproduce

1. Go to "resources" section
2. Add a new postgresql resource (ssl required or optional, doesn't seem to matter).  I'm using an AWS RDS instance.
3. Click test resource and see the connection failure

### Expected behavior

I expect the Postgresql resource to connect when tested.

### Screenshots

![image](https://github.com/windmill-labs/windmill/assets/1934496/814be2f5-9a43-410d-b80a-81a15fec17cf)

### Browser information

Chrome Version 117.0.5938.62 

### Application version

CE v1.176.0-9-g0b27e605

### Additional Context

I've verified the accounts/creds multiple times and it's exactly the same.  This seems to have started when I pulled down the latest docker images running a `docker-compose up -d`

**Comment by rubenfiszel** [comment]
Could you go in the Runs page, then 'All' and look at one of the 'Preview without path' job that correspond to the connection test. You should see something like this: 
![image](https://github.com/windmill-labs/windmill/assets/275584/69531c95-933d-4db9-aec0-00ef3172f117)

I couldn't reproduce your error but this should give us a clue

**Comment by Incisive** [comment]
Figured it out! Looks like I had no "native" workers running, and all my test jobs / postgres tasks were waiting queued up in a "waiting for worker" state

![image](https://github.com/windmill-labs/windmill/assets/1934496/83bb9532-e347-4807-b73a-22d12906befe)

I was able to test that same connection and it works as expected now.  Sorry for the false alarm!

**Comment by Haibread** [comment]
We had the same issue while updating from 1.174 to 1.175

We resolved it by removing the `WORKER_TAGS=nativets,postgresql,mysql,graphql,snowflake` env var in the docker compose and replacing it with `WORKER_GROUP=native` for the native worker

**Comment by rubenfiszel** [comment]
@Haibread your comment made us realize we had done a mistake in ensuring back-compatibility between WORKER_TAGS and WORKER_GROUP. Although your solution is preferred, it is no longer necessary to do so in latest. WORKER_TAGS will be added to the tags fetched from the WORKER_GROUP (which in the absence of being defined is "default")
