### ISSUE TITLE
feature: Implement Synchronized Sidebar with Active Heading Highlighting

### ISSUE THREAD

**Issue by abhiraj-ku** [windmill-labs/windmill#2344]
Issue: 
On the Docs page  When a link is clicked, the content should scroll to the corresponding section, and the clicked link should be visually highlighted as the active section in the sidebar.

Context:
This feature will improve user experience and navigation on our website. Users will easily identify their current location within the content, enhancing overall usability

**Comment by fatonramadani** [comment]
Thanks for the feedback! I've fixed that in the documentation repo:
https://github.com/windmill-labs/windmilldocs/pull/319

**Comment by abhiraj-ku** [comment]
Happy to contibute in any form !
