### ISSUE TITLE
investigate the workflow for self-hosting when BYPASSRLS is not available (e.g. in Azure)

### ISSUE THREAD

**Issue by IamJeffG** [windmill-labs/windmill#2345]
#### Context
Azure's hosted PostgreSQL database offering ("Azure database for flexible servers") notoriously does not provide a true superuser account at all, and therefore [it is impossible to delegate BYPASSRLS permission to a new role.](https://learn.microsoft.com/en-us/azure/postgresql/flexible-server/concepts-security#row--level-security)

#### Ask
Ultimately I think I would appreciate clear guidance along the lines of either "don't even try to self-host Windmill without BYPASSRLS" or, alternatively, "you can use Azure Database and here is the recipe to set that up, and these are the things that will break."

I know there have been one or two [past](https://github.com/windmill-labs/windmill/issues/1738) [attempts](https://github.com/windmill-labs/windmill/issues/1347) to make sure migrations and `u/admin/hub_sync` work without BYPASSRLS, and this gives me a false confidence that it should work, even though the docs don't say anything about running without BYPASSRLS. 

#### Workaround
A workaround that I've hacked up (on `CE v1.177.0-5-g4219377b`) is:

1. [Setup the database and roles as documented](https://raw.githubusercontent.com/windmill-labs/windmill/main/init-db-as-superuser.sql), except that I cannot use `WITH BYPASSRLS` on windmill_admin
2. Go through initial setup. I see all the migrations complete successfully (according to table `_sqlx_migrations`).
3. :disappointed: I see that it cannot save any script to the admin workspace ("Error while saving the script as a draft: Sql error: error returned from database: permission denied for table script"), including it can't save `u/admin/hub_sync`.
4. As hinted by https://github.com/windmill-labs/windmill/issues/1738 after the initial setup has created the SQL tables, I can go into the Database and change the owner of the new tables to `windmill_admin` and then I see the `u/admin/hub_sync` script & can run it! 

```sql
ALTER TABLE store OWNER TO windimill_admin;  -- formerly owned by the `nonsuperuser` role used by $DATABASE_URL to login
ALTER TABLE queue OWNER TO windimill_admin;
```

But I wonder what different thing will break by manually changing table owners like this.  What about the next migration?  Or if it is always fine for these (and other?) tables to be owned by `windmill_admin`, then can the migration create them as that role to begin with?

**Comment by rubenfiszel** [comment]
Thank you for the clear write-up. I wasn't aware that BYPASSRLS wouldn't work on some db like azure. It seems like the only sensible solution is to add a policy for windmill_admin that is equivalent to BYPASSRLS.

> CREATE POLICY admin_policy ON x TO windmill_admin USING (true);

We will add it to the backlog, we can expedite this for enterprise use-cases.

**Comment by IamJeffG** [comment]
Great idea.  I was able to verify that creating POLICY on all tables with RLS solves the problem!  Thank you.

In summary, my updated workflow for self-hosting a new Windmill deployment in Azure is:
1. [Setup the database and roles as documented](https://raw.githubusercontent.com/windmill-labs/windmill/main/init-db-as-superuser.sql), except without `WITH BYPASSRLS` on windmill_admin.
2. Start the app and navigate to its homepage. Even before you login, it'll run migrations and create the database tables that you will need to modify in the next step.
3. Run the following queries against the database:

<details><summary>Click to view queries</summary>
<p>

```sql
CREATE POLICY admin_policy ON account TO windmill_admin USING (true);
CREATE POLICY admin_policy ON app TO windmill_admin USING (true);
CREATE POLICY admin_policy ON audit TO windmill_admin USING (true);
CREATE POLICY admin_policy ON capture TO windmill_admin USING (true);
CREATE POLICY admin_policy ON completed_job TO windmill_admin USING (true);
CREATE POLICY admin_policy ON flow TO windmill_admin USING (true);
CREATE POLICY admin_policy ON folder TO windmill_admin USING (true);
CREATE POLICY admin_policy ON queue TO windmill_admin USING (true);
CREATE POLICY admin_policy ON raw_app TO windmill_admin USING (true);
CREATE POLICY admin_policy ON resource TO windmill_admin USING (true);
CREATE POLICY admin_policy ON schedule TO windmill_admin USING (true);
CREATE POLICY admin_policy ON script TO windmill_admin USING (true);
CREATE POLICY admin_policy ON usr_to_group TO windmill_admin USING (true);
CREATE POLICY admin_policy ON variable TO windmill_admin USING (true);
```

</p>
</details>

4. Login as `admin@windmill.dev`, change superuser, and schedule hub sync.  If you don't immediately see the prompts to do this, something did not work.

**Comment by machisuji** [comment]
Hi @IamJeffG - is this still working for you? I've run into the same issues and I wasn't sure which tables to create the policy for. Not entirely sure what "tables with RLS" means or how I find out which those are. So I just did on all tables.

And while the normal user now works the superadmin workspace still doesn't. It doesn't seem to see any of the tables.
When I access the superadmin workspace I just see the following:

![image](https://github.com/user-attachments/assets/abe80240-84ea-4dc8-95bc-02944833dcf5)

Is the superuser workspace working for you?

**Comment by IamJeffG** [comment]
@machisuji Yes it is still working, a year later!

Here is my full write-up of how I deployed it in September 2023: https://gist.github.com/IamJeffG/73be1d5a4627e65cf0b5f32ed8fc703a

I have not touched the deployment details or database config since, yet am still successfully using the windmill deployment regularly.

**Comment by rubenfiszel** [comment]
On latest, we actually added all the windmill_admin bypass RLS to be applied automatically as part of a migration: https://github.com/windmill-labs/windmill/commit/e44decb9c2c0c657312a8f79d71262001bce7813 

so it should be easier and the query above should not be needed anymore. Let us know if you still encounter issues. We're deployed by thousand of enterprise customers on all sorts of managed databases, azure is the only one we really had issues with but this should sort it out.
