### ISSUE TITLE
feature: improvement suggestions allowing to run wmill in restricted/unprivileged mode

### ISSUE THREAD

**Issue by rauanmayemir** [windmill-labs/windmill#2391]
For running windmill components in unprivileged mode, setting the usual params works with almost no effort except for the lack of unified approach to having a workdir environment - a temp directory owned by unprivileged runtime user that would let wmill to write npm/pip cache or work with zip archives (that happens during workspace pull/push).

It would be nice to have a configurable `WORKDIR` env variable defaulting to say `/tmp` which would be used for all things FS. E.g `/tmp/.npm`, `/tmp/.pip`, `/tmp/cache`, etc. That way, runtime user would be able to have its own runtime directory while having zero permission to do anything else whatsoever. (readOnlyRootFilesystem)

**Comment by rubenfiszel** [comment]
Fixed in latest. It's now generated temporarily in /tmp/windmill (and removed at the end of the request)
