### ISSUE TITLE
bug: date input won't clean up its value after input value is erased on form 

### ISSUE THREAD

**Issue by camilacampos** [windmill-labs/windmill#2395]
### Describe the bug

I'm using some date inputs on a form and I realized they are not being cleaned up after I erase the values on the form.

I first found this bug on version 1.165.0. I upgraded to 1.80.0 but the problem persists.

### To reproduce

1. Add any date input on an app
1. Fill the input with some date
    - input result is the date you added
1. Erase the filled date on the input
    - input result is still the date you added before

### Expected behavior

When the date input is erased/cleaned, the input result should be cleaned as well (with a null value).

### Screenshots

![image](https://github.com/windmill-labs/windmill/assets/2309096/0492ff9a-74a4-4a7c-94f4-607d1d461e62)

### Browser information

Chrome Version 117.0.5938.132

### Application version

windmill versions 1.165.0 and 1.80.0

**Comment by rubenfiszel** [comment]
fixed on latest
