### ISSUE TITLE
bug: updating custom resource type description fails

### ISSUE THREAD

**Issue by rconjoe** [windmill-labs/windmill#2400]
### Describe the bug

If I create a custom resource type, save it, and then later attempt to update that resource type's "description", the updated value will not save. Sometimes it will remain as the original, other times it clears the value entirely, leaving a blank description. When observed all requests receive 200 OK responses in the browser.

### To reproduce

1. Go to 'Resources'
2. click the 'Resource Types' tab
3. click on 'Add Resource Type'
4. Add a resource type, give it a description, and click 'Save'
5. On the resource type you just created, click 'Edit'
6. Edit the description and click 'Save'
7. Observe weird behavior

### Expected behavior

I expected the description of the custom resource type to update with what I input.

### Screenshots

1. creating a resource type
![image](https://github.com/windmill-labs/windmill/assets/48492680/17055888-14fd-4bb8-afb9-4a9cb870673f)

2. resource type shows in list
![image](https://github.com/windmill-labs/windmill/assets/48492680/dffea38c-b211-4a10-bd22-efaa1c8a6c77)

3. editing the resource type description
![image](https://github.com/windmill-labs/windmill/assets/48492680/1b58189b-7fcf-42e6-8dee-dc5b521149e0)

4. description has not updated
![image](https://github.com/windmill-labs/windmill/assets/48492680/ad7b6142-4ffa-4311-8062-c2477099b1b1)

5. subsequent attempts to update the description clear the value entirely
![image](https://github.com/windmill-labs/windmill/assets/48492680/dc73c739-70b6-42c4-920a-7ccafba614e2)

### Browser information

Mozilla Firefox 188.0.1

### Application version

CE v1.180.0-12-g67ee81cb

### Additional Context

selfhosted with docker compose.

**Comment by rubenfiszel** [comment]
fixed on latest
