### ISSUE TITLE
bug: docker daemon not running

### ISSUE THREAD

**Issue by kwekewk** [windmill-labs/windmill#2405]
### Describe the bug

Helm Deployment 

### To reproduce

1. Go to script docker
2. Click on test

### Expected behavior

I think it should start new pod?

**Comment by rubenfiszel** [comment]
Have you seen the: `windmill.exposeHostDocker` option ?

**Comment by kwekewk** [comment]
ah, i missed that part. But it didn't work for me
How setup with this? as sidecard for worker pods?
https://www.windmill.dev/docs/advanced/docker#remote-docker-daemon

**Comment by rubenfiszel** [comment]
Mounting the socket is the only option in windmill and I will need more details to help. Is the socket not available from bash ?
