### ISSUE TITLE
bug: Can't select items from Multi Select input on mobile browsers

### ISSUE THREAD

**Issue by ylysyym** [windmill-labs/windmill#2428]
### Describe the bug

Trying to select items from a multi select input doesn't work on mobile browsers; it only results in the selection dropdown being closed. It is possible sometimes to select the active item by pressing enter.

### To reproduce

1. Go to 'Home'
2. Click on '+App'
3. Add Multi Select input
4. Save draft
5. Click Deploy
6. Open the Windmill app from a mobile browser
7. Tap the multi select input field and try to tap one of the options
8. Nothing is selected

### Expected behavior

I expect the tapped option to be selected.

### Browser information

Android Firefox Browser 118.1.1 (Build #2015977611)

### Application version

CE v1.182.3-2-gd51fc57c

### Additional Context

I was able to produce this problem on my Samsung S22 Ultra, running Android 13. It occurs on both Firefox and Chrome, even when using the desktop version of the site. Additionally it works fine when using a browser on my desktop but I would like to use this feature from mobile browsers.

**Comment by rubenfiszel** [comment]
We will look into it soon cc @fatonramadani
