### ISSUE TITLE
bug:change base url use environment in docker compose

### ISSUE THREAD

**Issue by daoan1412** [windmill-labs/windmill#2436]
### Describe the bug

I want to change the base url in the following settings, but I can't install it using the environment in docker. 
![Screenshot from 2023-10-11 21-26-35](https://github.com/windmill-labs/windmill/assets/35399427/4be08ce7-6a8a-47ef-b3d6-dabf4c35ffe6)

### To reproduce

I tried using keys like: BASE_URL, BASE_INTERNAL_URL, WM_BASE_URL but all failed.

### Expected behavior

change base url use environment in docker compose

### Application version

CE v1.182.3-7-g4d26c01d

**Comment by rubenfiszel** [comment]
@daoan1412 BASE_URL is only used as a default and wouldn't be displayed here. If you set it there in the UI it will be the source of truth
