### ISSUE TITLE
bug: After update cannot run postgresql nativets scriptw

### ISSUE THREAD

**Issue by N4v41** [windmill-labs/windmill#2459]
### Describe the bug

after this change [backend/migrations/20231016084043_addback_bigquery.up.sql](https://github.com/windmill-labs/windmill/commit/9314d38bf1da6247b367effe69394f25a27067ca#diff-4af72191a8e9862742b7ef67bee2ea1074b48564185e66a6075a1f47f456612b)
the workertags where changed to the typo "postgresq" insted of "postgresql" causing the jobs using this workertag to not execute the queries.

### To reproduce

1. upgate to latest version, 
2. check the netitivets groups tags
3. try to run a postgresql query with nativets
4. job doesnt execute

### Expected behavior

job being executed by one worker in the nativets group

### Application version

CE v1.183.0-27-ge8badf26

**Comment by rubenfiszel** [comment]
Fixed in latest, thanks for the report. That was exactly right, the migration had a typo
