### ISSUE TITLE
bug: Escape does not close most in front drawer

### ISSUE THREAD

**Issue by abrasher** [windmill-labs/windmill#2482]
### Describe the bug

When there is multiple drawers open, pressing ESC closes the first drawer that was open, not the most recent one.

### To reproduce

1. Go to "Script Editor"
2. Click on "+Resource" to open _Drawer 1_
3. Click on "View/Edit" to open **Drawer 2**
4. Press "ESC", _Drawer 1_ closes
5. Press "ESC", **Drawer 2** closes

### Expected behavior

Most recent drawer should be closed on "ESC"

1. Go to "Script Editor"
2. Click on "+Resource" to open _Drawer 1_
3. Click on "View/Edit" to open **Drawer 2**
4. Press "ESC", **Drawer 2** closes
5. Press "ESC", _Drawer 1_ closes

### Screenshots

https://github.com/windmill-labs/windmill/assets/47009014/3ef686fd-9f69-437a-a71d-03822cde13e6

### Browser information

Microsoft Edge Version 118.0.2088.57 

### Application version

CE v1.186.0-8-g9df33ff6

**Comment by abrasher** [comment]
Very minor UX issue that seems like a fair amount of effort to fix.

Because event listeners trigger in the order they are registered, the first modal will close. The code here:

https://github.com/windmill-labs/windmill/blob/2b7018413a90274164a4c5743ddf1631b1b62f9f/frontend/src/lib/components/common/drawer/Drawer.svelte#L57

prevents the next event listener from triggering as without every drawer would close

I guess the order in which the drawers were opened would have to be tracked or at least keep track of the last opened drawer to skip the event if it isn't the top most drawer.

**Comment by rubenfiszel** [comment]
Thank you for the issue, I think we can solve this using a stack of opened drawers as a svelte module context and close only the latest

**Comment by rubenfiszel** [comment]
Fixed in latest
