### ISSUE TITLE
bug: Bun executions - Cannot find package "semver-intersect" in build.ts

### ISSUE THREAD

**Issue by felipemullen** [windmill-labs/windmill#2533]
### Describe the bug

I am unable to run any script using the Bun runtime. The ui message is the following:

![image](https://github.com/windmill-labs/windmill/assets/3488482/e64b797d-28de-4c86-a7f4-15a9ca25ef39)

Upon investigation it appears that the generated `build.ts` file contains the following line:

```typescript
const { intersect } = require("semver-intersect");
```

but the package is not installed in the job directory.

### To reproduce

1. Create a new script
2. select the `Bun` runtime
3. replace script contents with `console.log('hello world');` or any other simple script

### Expected behavior

The script should run as normal

### Application version

CE v1.194.0-5-gc31299bed

### Additional Context

I changed my `docker-compose.yml` to set the following flag to `true`

```yml
services:
  windmill_worker:
    environment:
      - KEEP_JOB_DIR=true
```

This revealed the following `build.ts` file:

```javascript
const p = {
  name: "windmill-relative-resolver",
  async setup(build) {
    const { writeFileSync, readFileSync, mkdirSync } = await import("fs");
    const { dirname, resolve } = await import("node:path");

    const base_internal_url = "http://localhost:46115".replace(
      "localhost",
      "127.0.0.1"
    );
    const w_id = "icsl";
    const current_path = "u/fmullen/easy_script";

    build.onLoad({ filter: /.*\.url$/ }, async (args) => {
      const url = readFileSync(args.path, "utf8");
      const contents = await (
        await fetch(url, {
          method: "GET",
          headers: { Authorization: "Bearer 8u1djEE8jOPsrufbDy4AtcJClyLCsR" },
        })
      ).text();
      return {
        contents,
        loader: "tsx",
      };
    });
    const cdir = resolve("./");
    const cdirNoPrivate = cdir.replace(/^\/private/, ""); // for macos
    const filter = new RegExp(
      `^(?!\\.\/main\\.ts)(?!${cdir}\/main\\.ts)(?!(?:/private)?${cdirNoPrivate}\/wrapper\\.ts).*\\.ts$`
    );
    build.onResolve({ filter }, (args) => {
      const file_path =
        args.importer == "./main.ts" || args.importer == resolve("./main.ts")
          ? current_path
          : args.importer.replace(cdir + "/", "");

      const isRelative = !args.path.startsWith("/");

      const url = isRelative
        ? `${base_internal_url}/api/w/${w_id}/scripts/raw/p/${file_path}/../${args.path}`
        : `${base_internal_url}/api/w/${w_id}/scripts/raw/p/${args.path}`;
      const file = isRelative
        ? resolve("./" + current_path + "/../" + args.path + ".url")
        : resolve("./" + args.path + ".url");
      mkdirSync(dirname(file), { recursive: true });
      writeFileSync(file, url);
      return {
        path: file,
      };
    });
  },
};


const bo = await Bun.build({
  entrypoints: ["./main.ts"],
  outdir: "./out",
  plugins: [p],
  external: ["*"],
});

const fs = require("fs/promises");

const captureVersion = /(^\@?[^\@]+)(?:\@(.+))?/;

if (!bo.success) {
  bo.logs.forEach((l) => console.log(l));
  process.exit(1);
} else {
  let content = await fs.readFile("./out/main.js", { encoding: "utf8" });
  const imports = new Bun.Transpiler().scanImports(content.replaceAll("__require", "require"));

  const { intersect } = require("semver-intersect");
  const dependencies: Record<string, string[]> = {};
  for (const i of imports) {
    let [_, name, version] = i.path.match(captureVersion) ?? [];
    if (version == undefined) {
      if (dependencies[name] == undefined) {
        dependencies[name] = [];
      }
    } else {
      if (dependencies[name] == undefined) {
        dependencies[name] = [version];
      } else {
        dependencies[name].push(version);
      }
    }
  }
  const resolvedDeps: Record<string, string> = {};
  for (const i in dependencies) {
    resolvedDeps[i] =
      dependencies[i].length == 0
        ? "latest"
        : dependencies[i].reduce((a, b) => {
            return intersect(a, b);
          });
  }
  await Bun.write(
    "./package.json",
    JSON.stringify({ dependencies: resolvedDeps }, null, 2)
  );
}
```

I manually tried the command `bun run build.ts` within the docker container, and was able to successfully reproduce the error in the ui.
Running `bun add semver-intersect` allows `bun run build.ts` to succeed, as expected.

**Comment by rubenfiszel** [comment]
Are you using a custom npm registry?

**Comment by felipemullen** [comment]
Yes, I have a verdaccio proxy for a private artifactory server. The worker has an env variable override:

```
- NPM_CONFIG_REGISTRY=http://verdaccio:4873
```

**Comment by rubenfiszel** [comment]
It's a small bug related to a code path that is specific to using npm config registries, should be easy to fix. Pushing this to the backlog.

**Comment by rubenfiszel** [comment]
I have been trying to reproduce on a fresh docker compose and using the same code path (specifying as npm registry: https://registry.npmjs.org/) which should use the same code path. And I have been unable to.

**Comment by felipemullen** [comment]
I will try and set up a repository that reproduces the issue and I will get back to you. Thanks @rubenfiszel

**Comment by rubenfiszel** [comment]
Thanks a lot, should have time tomorrow to fix it!

**Comment by rubenfiszel** [comment]
@felipemullen I have been able to reproduce thanks to your clear repo.

However, it seems the error has nothing to do with windmill but just bun and verdaccio not working together

Run just the verdaccio part of your docker-compose,
then
```
NPM_CONFIG_REGISTRY=http://localhost:4873/ bun run main.ts
```

with main.ts
```
import "semver-intersect";
```

You will have the same error. I do not have the time to investigate further but to continue, do you have a minimal way to make bun work with verdaccio outside of windmill?

**Comment by felipemullen** [comment]
ah, interesting. Okay, I will see if I can find a way to make this work somehow. I will update this ticket

**Comment by felipemullen** [comment]
Ok I solved the problem, although it was somewhat of a workaround.

I can confirm the issue is with verdaccio, and not with windmill or bun. I tried many different configuration options and nothing would allow bun to download the package whenever `NPM_CONFIG_REGISTRY` was defined.

The solution I settled for, was to define workers dedicated to bun executions:

```yaml
windmill_worker_bun:
  environment:
    # - NPM_CONFIG_REGISTRY=http://verdaccio:4873
    - WORKER_GROUP=bun
    - WORKER_TAGS=bun
  volumes:    
    - ./home/bun/bunfig.toml:/root/.bunfig.toml
  ...

windmill_worker_generic:
  environment:
    - WORKER_TAGS=bash,deno,dependency,flow,go,hub,other,powershell,python3
```

this allows me to configure bun to access private repos using it's [native configuration](https://bun.sh/docs/install/registries), something deno does not have.

Since I need both deno and bun at this point, two types of workers are still necessary.

I plan to only use bun, but migrating scripts might take a few weeks.

thanks for the help @rubenfiszel, I am closing this issue
