### ISSUE TITLE
bug: cannot add workspace from the CLI

### ISSUE THREAD

**Issue by kcalliauw** [windmill-labs/windmill#2547]
### Describe the bug

I'm trying to add a workspace as described in the documentation using the wmill CLI, but I cannot get it to work. 

### To reproduce

I'm using the wmill cli to try to add a workspace, similar to this:

```
wmill workspace add myspace remotespace https://my-windmill-instance/
```
- The command asks me to choose between browser and token
- I choose 'Browser' as the option
- The browser opens and I click authorize
- browser forwards me to localhost:63623 (as an example, random port every time), there, I get a ERR_CONNECTION_REFUSED
- the CLI gives me the following error:

```
Login by going to https://my-windmill-instance/user/cli?port=63623
Opened browser for you
! Credentials or instance is invalid. Aborting.
error: Uncaught (in promise) TypeError: Invalid URL: '/api/workspaces/exists'
    return await fetch(url, request);
                 ^
    at getSerialization (ext:deno_url/00_url.js:89:11)
    at new URL (ext:deno_url/00_url.js:380:27)
    at new Request (ext:deno_fetch/23_request.js:304:25)
    at ext:deno_fetch/26_fetch.js:432:27
    at new Promise (<anonymous>)
    at fetch (ext:deno_fetch/26_fetch.js:428:18)
    at sendRequest (https://deno.land/x/windmill@v1.195.0/windmill-api/core/request.ts:219:18)
    at https://deno.land/x/windmill@v1.195.0/windmill-api/core/request.ts:289:40
    at eventLoopTick (ext:core/01_core.js:183:11)
```

I've verified that the port is open and listening using netstat after it opens the browser (it listens on 0.0.0.0). I've confirmed the port is reachable using 
```
curl -I localhost:63623
```
(this produces a 302 with a location to my https://my-windmill-instance/user/cli-success)

### Expected behavior

The workspace is added

### Browser information

Chrome Version 118.0.5993.117 (Official Build) (64-bit)

### Application version

CE v1.197.0

**Comment by rubenfiszel** [comment]
fixed in latest, apologies for the break (we did a mis-release of the CLI)
