### ISSUE TITLE
bug: JOB_RETENTION_SECS not respected

### ISSUE THREAD

**Issue by TheOneValen** [windmill-labs/windmill#2560]
### Describe the bug

When setting the JOB_RETENTION_SECS  environment variable is set it is not respected.

(I use the docker container)

### To reproduce

Setting the Environment variable JOB_RETENTION_SECS on the container start it does not get logged on startup.

When adding JOB_RETENTION_SECS to the Dockerfile the setting gets logged on startup:

`2023-11-04T08:59:59.239746Z  INFO windmill: config: NUM_WORKERS: 4, BASE_URL: <my_base_url>, TIMEOUT: 600, KEEP_JOB_DIR: false, PYTHON_PATH: /usr/local/bin/python3, DENO_PATH: /usr/bin/deno, GO_PATH: /usr/local/go/bin/go, PATH: /usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/go/bin, HOME: /root, JOB_RETENTION_SECS: 3888000, WORKER_GROUP: default,native`

But the monitor job does not use the value:

`2023-11-04T09:10:29.519556Z  INFO windmill::monitor: deleted 39 jobs completed JOB_RETENTION_SECS 5184000 ago: [<list of jobs>]`

### Expected behavior

Monitor job should use the value set up by the env, preferable with the environment variable given with docker start (or compose up).

### Application version

1.200.0

**Comment by rubenfiszel** [comment]
Did you set it in the servers and not the workers ? Also it's something you can set in the instance settings UI directly

**Comment by TheOneValen** [comment]
I use one server instance with 4 workers all in 1 container. I'll check the UI setting, thank you. Are there preference rules for env variables vs settings?

**Comment by TheOneValen** [comment]
The UI settings work. The environment variable does not. This issue can be closed or regarded as documentation issue.
