### ISSUE TITLE
Stuck in a login loop when trying to add a schedule

### ISSUE THREAD

**Issue by brettwlewis** [windmill-labs/windmill#2599]
I'm a windmill noob, currently on the free tier (either of these could be my problem, or both). lol
I'm busy testing the platform and love what I'm seeing.

I'm stuck trying to add a schedule via the (left) SCHEDULES menu - I can see the Schedule page but as soon as I try and add a NEW SCHEDULE using the top right button, I get pushed to the login screen.

Is this a limitation of the free plan perhaps?

**Comment by rubenfiszel** [comment]
No limitation, investigating now

**Comment by rubenfiszel** [comment]
We made a change recently that resulted in that issue, it's fixed, we will re-deploy in 10mins. Thank you for the report.

**Comment by rubenfiszel** [comment]
It's fixed and deployed @brettwlewis

**Comment by brettwlewis** [comment]
Brilliant! Many thanks - that was super-fast.
The effort and quick response is much appreciated.
I can confirm that it's working.
