### ISSUE TITLE
feature: support kicking off a pipeline with a file upload

### ISSUE THREAD

**Issue by nemccarthy** [windmill-labs/windmill#262]
its great to see that the demo py script can take a file upload object though there is no way to pass this in to a flow as an input param. it would be great to upload files as input to flows

**Comment by rubenfiszel** [comment]
I will improve this to be able to do it from the SchemaEditor but in the meantime you can use the type `wmill.Base64` in Deno or bytes in Python in the first step, and then "Copy 1's step schema".

**Comment by rubenfiszel** [comment]
Done in 2cb6e6e
![Screenshot 2022-07-29 at 11-40-55 New Flow Windmill](https://user-images.githubusercontent.com/275584/181732068-133db9cf-2bc2-46d1-8b1b-8bd10b129b94.png)

**Comment by nemccarthy** [comment]
thanks @rubenfiszel this is great!
