### ISSUE TITLE
bug: Approval/suspend steps in branching bypassed

### ISSUE THREAD

**Issue by jibe-b** [windmill-labs/windmill#2639]
### Describe the bug

I wrote a flow with 1 _branching all_ step, and 1 `approval step` (`Return resume and cancel endpoints (windmill)`) in each branch.

The flow runs and finishes without asking for the approval action (`Resume` button clicked) to be achieved.

### To reproduce

1. Write a flow with 1 _branching all_ step, and 1 `approval step` (`Return resume and cancel endpoints (windmill)`) in each branch:

![image](https://github.com/windmill-labs/windmill/assets/6146483/2adb4d69-13ba-49ca-aef4-f923048bc5f3)

2. Run the flow

3. Read the results

![image](https://github.com/windmill-labs/windmill/assets/6146483/0edff0d0-0dfb-458c-baec-e4300e26db49)

![image](https://github.com/windmill-labs/windmill/assets/6146483/40929fdb-b0ed-450e-845f-8e9a009ad1a0)

### Expected behavior

The flow should not finish, stay `running` and awaiting the approval actions.

### Application version

EE v1.208.0-5-g9a0ef97eb

### Additional Context

I also tried adding 1 `Approval step` after the `collect step` and the flow only pauses and waits for the last approval step (the one not in a branch).

![image](https://github.com/windmill-labs/windmill/assets/6146483/4461132d-a43d-4f4c-8e67-ce8cde6ac5cf)

**Comment by rubenfiszel** [comment]
Just note that if you add an identity step right after the suspend step (add an action without definiing) it will work. We will fix it by creating a virtual item automatically but the reason it doesn't work is that suspend work by scheduling the next step as waiting for events after the suspend but here there are no next step in the subflow

**Comment by jibe-b** [comment]
I just tried and the flow actually waits for the approvals in this case. I will use the workaround until I see virtual items automatically added.

![image](https://github.com/windmill-labs/windmill/assets/6146483/4fc06539-20a3-45de-86af-7ea21fd7eda0)

Thanks @rubenfiszel for answering so fast. 

These 25 min have been an opportunity for me to dive in the code.

**Comment by rubenfiszel** [comment]
Virtual modules are now inserted everywhere necessary
