### ISSUE TITLE
bug: package-lock.json out of sync

### ISSUE THREAD

**Issue by happysalada** [windmill-labs/windmill#2646]
### Describe the bug

when trying to install the js dependencies just with the package lock, I get the following error
```
> npm ERR! code ENOTCACHED
       > npm ERR! request to https://registry.npmjs.org/@codingame%2fmonaco-editor-treemended failed: cache mode is 'only-if-cached' but no cached response is available.
       >
```

so I went ahead and tried re-creating the package-lock file to see if there would be any changes. but then I got
```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for vscode-ws-jsonrpc@!3.1.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

so I'm guessing the latest vscode-ws-jsonrpc breaks something.
Let me know when you've had time to make the upgrade (no rush, just in case it fits in your schedule)

I've created a PR to mark the update pending in nixpkgs https://github.com/NixOS/nixpkgs/pull/268259

### To reproduce

1. delete node_modules and package-lock.json
2. try to `npm i`

### Expected behavior

the package-lock should be in sync and re-creatable at any time.

### Application version

1.210.0

### Additional Context

I completely understand that this wouldn't make the top priority.
Thanks again for making amazing software!

**Comment by rubenfiszel** [comment]
There was a typo in our package.json, it's fixed in latest (and package-lock.json rebuilt)

**Comment by happysalada** [comment]
Perfect, im closing this. Ill make the update on the next release. Thank you !
