### ISSUE TITLE
question: around database setup and users

### ISSUE THREAD

**Issue by happysalada** [windmill-labs/windmill#2654]
hey, this is more of a question than anything else.
1. I noticed this file is used to initialize the database https://github.com/windmill-labs/windmill/blob/main/init-db-as-superuser.sql
this gives permissions to basically create multilple databases to windmill_user. Is this feature of creating multiple databases used ?
I'm just thinking if people want to deploy this on their machine running other services using postgres, people might object to giving windmill user permission to do everything.
I was wondering if just giving windmill_user privileges on a single database might be enough ?
2. the script talks about windmill_user and windmill_admin. How are those users used ? The reason I ask is that in order to bypass supplying a password with postgres for those users, the unix user running the systemd service has to be the same as the postgres user, in that case postgres won't ask for a password and the database url can be simplified to something like `postgresql:///windmill?host=/run/postgresql` (if the database name is windmill). my understanding is that there are 3 services `windmill-server` , `windmill-worker`, and `windmill-worker-native` , could those just be run with `windmill_user` (and therefore only having windmill-user level access to postgres)? (I know about there also being an lsp, but I plan to tackle that right after.).

**Comment by rubenfiszel** [comment]
windmill_admin and windmill_user are not roles to be used by the services, they are used internally for some transactions by windmill to leverage RLS depending on a if the transaction is relative to an user or admin request.

Yes, you can restrict windmill_user to the database used by windmill only

**Comment by rubenfiszel** [comment]
The role to pass to windmill services should be equal to being superadmin/admin on the databases that it uses. However, there are no needs to have any access outside that one database.

**Comment by happysalada** [comment]
hey, thank you again for your response on this.
here is the initialisation code I ended using

```
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT FROM pg_catalog.pg_roles 
        WHERE rolname = 'windmill_user'
    ) THEN
        CREATE ROLE windmill_user;
        GRANT ALL PRIVILEGES ON DATABASE ${cfg.database.name} TO windmill_user;
    ELSE
      RAISE NOTICE 'Role "windmill_user" already exists. Skipping.';
    END IF;
    IF NOT EXISTS (
        SELECT FROM pg_catalog.pg_roles 
        WHERE rolname = 'windmill_admin'
    ) THEN
      CREATE ROLE windmill_admin WITH BYPASSRLS;
      GRANT windmill_user TO windmill_admin;
    ELSE
      RAISE NOTICE 'Role "windmill_admin" already exists. Skipping.';
    END IF;
END
$$;
EOF
```

that is for the trick of not creating role twice in case they already exist.
on top of that I create a database "windmill" with an owner of "windmill" and that is the user that the app will be using to connect.

I've got a couple more errors from the logs, but it's looking much better
```
ERROR windmill: Metrics are only available in the EE, ignoring...
ERROR windmill_api::embeddings: Failed to initialize model instance: could not get
```

even though I've got
```
          METRICS_ADDR = "false";
```
as an env var

I'm close and hoping to finish the PR next week.

Thanks again for your help!
