### ISSUE TITLE
bug: variabels do not sometimes have their values

### ISSUE THREAD

**Issue by matthewford** [windmill-labs/windmill#2701]
### Describe the bug

TypeError: null is not an object (evaluating 'twilioResource.accountSid')
When I look at the Twilio variable both the account sid and token are set.

### To reproduce

Add twilio variable try and use it in a step, then click run.

### Expected behavior

it uses the variable values

### Screenshots

run id: [018c020e-b62f-6126-30cd-4f4d10fc7d19](https://app.windmill.dev/run/018c020e-b62f-6126-30cd-4f4d10fc7d19?workspace=jfcm)

<img width="789" alt="Screenshot 2023-11-24 at 16 03 59" src="https://github.com/windmill-labs/windmill/assets/215/ef0a63c3-3ca1-4b39-b10f-4cc3177986bf">

### Browser information

Chrome Version 119.0.6045.159 (Official Build) (arm64)

### Additional Context

I had this issue and sometimes hitting refresh many times seemed to help but not any more.

**Comment by matthewford** [comment]
Some how my flow step lost: flow_input.twilio_credentials in the input

**Comment by rubenfiszel** [comment]
@matthewford do you think the loss was a bug or could it have been a human error ? If you can reproduce we can investigate

**Comment by matthewford** [comment]
> @matthewford do you think the loss was a bug or could it have been a human error ? If you can reproduce we can investigate

Probably human error but a confirmation when reassigning or deleting a value that is already set in there could be nice
