### ISSUE TITLE
feature: JSON source for Tabs components

### ISSUE THREAD

**Issue by jibe-b** [windmill-labs/windmill#2711]
In the Apps Editor, `Tabs` components cannot be take a JSON as input.

![image](https://github.com/windmill-labs/windmill/assets/6146483/04a57386-5c5d-4fb3-b289-af81b26914c3)

It would be practical to enable to set the definition of the tabs in JSON object, similarly as the `Select` components do.

![image](https://github.com/windmill-labs/windmill/assets/6146483/c67deb44-02d2-4de7-9ff7-6254e54455dc)

**Comment by rubenfiszel** [comment]
the component "Select Tab" work as you suggest.

For Tabs component it's not possible for it to be dynamic because it's a complex container having multiple subgrids. Or maybe you just want JSON without necessarily making it an eval?

**Comment by jibe-b** [comment]
The "Select Tab" component is interesting but not what I would like to make use of.

A static JSON to set the tabs of the "Tabs" component would be already be 80% of my needs.

I usually place a "Select" component at the top of pages, which sets the tab of one `Invisible Tabs`. A static value would already make it easier when using the UI. In my case, most of the variation in the number of tabs happen at development time. Afterwards it's static.

Having an eval of the JSON would open more possibilities but you point that it is not as feasible.

Thank you as always for your reactivity.
