### ISSUE TITLE
feature: discard result of a branch in branch all

### ISSUE THREAD

**Issue by jbmolle** [windmill-labs/windmill#2726]
Hi!
Thanks a lot for this great software!
I've read the doc but I haven't found any way to do that yet.
I've created a webhook endpoint from a flow with a step "Run all branches" with "All branches run in parallel" set to true.
The three branches are doing API calls to some external services. Right now I have to wait that all three branches are done before going further in the flow. Would it be possible to go further in the flow as soon as one branch is done, discarding the result of the 2 other branches?
Thanks!
JB

**Comment by rubenfiszel** [comment]
@jbmolle that's an interesting feature and you can already do this but it will require more work.

Create an independent flow that just contain the branchall and your 3 branches. Let's call it S

In your original flow, replace your branchall with an approval step that will launch the subflow S  through an api call and pass the resume url as flow input.

That subflow S need to implement that:
- at the end of each branch it needs to call the resume url
- and cancel itself to avoid wasting compute on the other branches

**Comment by jbmolle** [comment]
Thanks for the tip!
