### ISSUE TITLE
Add the 20 most popular oauth integrations

### ISSUE THREAD

**Issue by rubenfiszel** [windmill-labs/windmill#273]
https://github.com/windmill-labs/windmill/blob/main/backend/oauth_connect.json

**Comment by CharityKithaka** [comment]
Hey, do you need help to keep adding popular oauth integrations?

**Comment by rubenfiszel** [comment]
Thanks for offering help, we have a path toward adding more oauth integrations quickly soon, but if there any you would have experience in and would be willing to try, happy to take contributions
