### ISSUE TITLE
bug: INET column type in Postgres

### ISSUE THREAD

**Issue by sieteunoseis** [windmill-labs/windmill#2732]
### Describe the bug

Getting the following error when doing a select statement from Postgres:

ExecutionErr: error during execution of the script:
conversion issue for value at column_name `origipaddr` with type Inet

Looks like there is an issue with the INET column type

### To reproduce

Using postgres resource, do a select statement with a column type of inet filled with IP addresses.

### Expected behavior

Return data as IP address.

**Comment by rubenfiszel** [comment]
Thank you for the report, we're fixing this right now
