### ISSUE TITLE
bug: Stuck on "Loading..." Screen

### ISSUE THREAD

**Issue by monagjr** [windmill-labs/windmill#2741]
### Describe the bug

Running the Docker version on AWS EC2 Ubuntu 20.04.2 LTS instance using Docker Compose on Docker Engine (Docker version 24.0.7, build afdd53b)...
- no errors in Browser Console
- no errors in Docker Compose logs
- All services and containers up and running

Only one change to "docker-compose.yml" file , changing the exposed version of Caddy to "8005" through:
ports:
- 8005:80

Trying to open "http://localhost:8005" shows the loading screen , all assets (js, logo, css) load successfully but it stuck on it!

<img width="822" alt="image" src="https://github.com/windmill-labs/windmill/assets/49984067/7466f83a-4e6e-4092-b443-135fb142ee63">

### To reproduce

1. curl https://raw.githubusercontent.com/windmill-labs/windmill/main/docker-compose.yml -o docker-compose.yml
2. curl https://raw.githubusercontent.com/windmill-labs/windmill/main/Caddyfile -o Caddyfile
3. curl https://raw.githubusercontent.com/windmill-labs/windmill/main/.env -o .env

4. Edit "docker-compose.yml" file to change Caddy exposed port from "80:80" to "8005:80"

5. docker compose up -d

6. open "http://localhost:8005" in browser 

### Expected behavior

WindMill finish loading and showing the homepage

### Screenshots

<img width="822" alt="image" src="https://github.com/windmill-labs/windmill/assets/49984067/16f5b968-f32b-4bb4-b3e5-c7a8afa3e283">

### Browser information

Chrome Version 119.0.6045.159 (Official Build) (x86_64)

### Application version

ghcr.io/windmill-labs/windmill:main

**Comment by rubenfiszel** [comment]
Do you have the same issue if you do not change the port ? The fact you see loading mean you can load the html page but not the js assets (or not all)

**Comment by monagjr** [comment]
@rubenfiszel thanks for fast response! :)

Checking...

**Comment by monagjr** [comment]
ok, I found the issue :)

I was accessing the AWS EC2  Instance through SSH Forward Channel, to map the ports on my local Computer to the remote AWS EC2 instance through SSH.

This seems to break it for some reason.

At least now, I can proceed.

Yet, you may need to look into this :)

**Comment by monagjr** [comment]
More context:
It seems to be more specific to how VS Code Forward Ports.

So making the port forward through CLI like (ssh -L 51902:localhost:80 username@remote_host) would work out

But making the same port forward through VS Code Window Connected to Remote Host will have WindMill stuck on loading screen.

I think you may consider as low priority for now.

<img width="1009" alt="image" src="https://github.com/windmill-labs/windmill/assets/49984067/ef131e6d-5fe9-4445-b184-a64247c79db3">
