### ISSUE TITLE
feature: more control over webhook outputs

### ISSUE THREAD

**Issue by gcleaves** [windmill-labs/windmill#2750]
Hi. I have a flow who's purpose is to create plain CSV text output. Unfortunately when calling the flow via a synchronous webhook, the response is a JSON "quoted string" with a Content-Type header of application/json.  I'd like to Content-Type to be text/csv.

Is there anyway to do that? Thanks!

**Comment by gcleaves** [comment]
Wow, great, I'll give it a try and let you know. My concern though just reading the docs is that the raw output is "Hello;World", when I would expect it to be Hello;World without the quotes.

Anyway I'll try it and report back.

**Comment by gcleaves** [comment]
Is this new feature in Image ghcr.io/windmill-labs/windmill:1.219.1?

**Comment by gcleaves** [comment]
The `"windmill_content_type": "text/csv"` property works wonderfully when calling the flow as a webhook, thanks! (I pulled "latest" Docker tag, which at this moment points to CE v1.219.1-22-gbea0da3d6.)

But when executing the flow via the UI, unfortunately the output is no longer plain text but instead `{result:text, windmill_content_type: "text/csv"}`. Is it possible to know the execution context in the flow (UI vs webhook) and adjust the output accordingly?

**Comment by rubenfiszel** [comment]
Could you explain what is the use-case ? Do you find the output to be hard to read in that form ?

**Comment by gcleaves** [comment]
The use case is as follows. End users need a CSV file of top 100 customers. Some end users prefer the GUI. Other more sophisticated end user know how to call the webhook. With the new development, the webhook output is perfect. 

However, the GUI user see this:
<img width="990" alt="Screenshot 2023-12-04 at 21 46 00" src="https://github.com/windmill-labs/windmill/assets/1041253/3da875cd-c776-4bd7-aa8c-41408f730e0a">

They can't get the exact output they need clicking the copy or download buttons because it is JSON: {result:text, windmill_content_type: "text/csv"}

If I as the Windmill developer have the execution context - UI or webhook - then I can add logic to the flow so as to only use 
{result:text, windmill_content_type: "text/csv"} when the context is webhook.

Have I been able to explain clearly?

**Comment by rubenfiszel** [comment]
Yes, and what seems to be the ideal DX is not to modify the output of the flow but how it's displayed by default. We do the same for tables and images where the JSON is still as-is and you can arrive to it by toggling the "As JSON" but by default we render them as images/tables.

**Comment by rubenfiszel** [comment]
Above is done on latest
