### ISSUE TITLE
bug: Authentik SSO is broken

### ISSUE THREAD

**Issue by JokerQyou** [windmill-labs/windmill#2757]
### Describe the bug

When configured with Authentik SSO, after the superadmin login with Authentik, the request to `/api/oauth/login_callback/authentik` would fail with 400, saying "Bad request: email address not fetchable from user info". Authentik did respond with 200 (inspected from log content). Both windmill and authentik did not log the user_info response content, so I cannot be sure what went wrong.

### To reproduce

1. Setup windmill using docker-compose.
2. Use default superadmin credential to login, and enable only Authentik SSO.
3. Change superadmin email to be the same as in Authentik.
4. Open another browser and login with Authentik.

### Expected behavior

Should be able to login as superadmin, since the Authentik user has the same email as the windmill superadmin.

### Screenshots

Login error:
<img width="915" alt="image" src="https://github.com/windmill-labs/windmill/assets/1465267/de290cdd-64b7-4ffa-beb4-b958a63bed08">

Here's the user_info response log from Authentik:
<img width="2028" alt="image" src="https://github.com/windmill-labs/windmill/assets/1465267/a0174765-4826-4248-8e26-eeed06abdba6">

Authentik provider configuration (I've marked the modified settings in red):
<img width="775" alt="image" src="https://github.com/windmill-labs/windmill/assets/1465267/e2836358-4e88-43a7-b026-edb004871796">
<img width="774" alt="image" src="https://github.com/windmill-labs/windmill/assets/1465267/cec2b38b-9ea9-4eb6-a3c2-09a0bacc88f5">

### Browser information

Chromium 119.0

### Application version

CE v1.219.1-10-g583dae6a7

**Comment by JokerQyou** [comment]
Maybe userinfo is only available with refresh_token rather than access_token (according to [this comment](https://github.com/goauthentik/authentik/issues/2329#issuecomment-1046283740))?
But I don't have the environment to rebuild windmill server to test this. Also authentik seems to respond with 200, so that can't be an authorization error.

**Comment by rubenfiszel** [comment]
Authentik was a community contribution from @samip5 

https://github.com/windmill-labs/windmill/pull/2614

And it seems to work for him, would ask him for advice on setup

**Comment by samip5** [comment]
Hi @JokerQyou, please try to first debug what you get from Authentik while using this oauth test app that will dump you the details: https://github.com/BeryJu/oidc-test-client using the same settings as how you had setup windmill in Authentik.


> And it seems to work for him, would ask him for advice on setup
Hi @rubenfiszel , please be so kind and refrain from making assumptions like that, I even have my pronouns listed at Github when you hover over my username.

**Comment by JokerQyou** [comment]
I just noticed that windmill redirected to Authentik with only these scopes:
<img width="545" alt="image" src="https://github.com/windmill-labs/windmill/assets/1465267/ed174be3-3a69-4e2b-a7bf-69ae034fd511">

While `oidc-test-client` defaults to use scopes `openid,offline_access,profile,email`. I think the missing scope `email` might be the problem.

**Comment by JokerQyou** [comment]
After tinkering with the database to update scopes in `global_settings` table's `oauths` record, windmill can now read my email address from Authentik. However, because previously I logged in with local credentials (to workaround this issue), now windmill complains `Bad request: an user with the email associated to this login exists but with a different login type "password"`. Is there any way to change the user to use OAuth login?

**Comment by rubenfiszel** [comment]
yes, it's in the password table. I will fix Authentik in my next commit by adding that scope. Thanks for the investigation.

**Comment by JokerQyou** [comment]
Changed `password` table's `login_type` to `authentik` and it's working now. Thanks for the info!

**Comment by samip5** [comment]
I think this has been fixed in commit 042504f, aka included in v1.220.0. @rubenfiszel Time to close it?
