### ISSUE TITLE
bug: vscode plugin show review 404

### ISSUE THREAD

**Issue by oulinbao** [windmill-labs/windmill#2759]
### Describe the bug

After I installed vscode plugin and created workspace, it shows 404 when preview the script file. I think the workspace config is correct.

<img width="830" alt="image" src="https://github.com/windmill-labs/windmill/assets/7589619/d8e655fd-2de8-4f24-b4a5-eb02847899b2">

### To reproduce

1. Install windmill plugin in vscode
2. Config windmill plugin, add new workspace by ">Windmill: add a windmill workspace"
3. Open a script file, it shows 404 Not found in preview tab

### Expected behavior

see the workflow page like in browser

### Browser information

vscode 1.84.2, macOS 13.6

### Application version

windmill 1.185, vscode plugin 0.2.7

**Comment by rubenfiszel** [comment]
What version of windmill are you on ? Can you try using app.windmill.dev ?

**Comment by oulinbao** [comment]
<img width="1343" alt="image" src="https://github.com/windmill-labs/windmill/assets/7589619/73b925a6-4abe-4d79-a9ab-fd98a89525e9">

I used app.windmill.dev to try out vscode plugin, it shows nothing.

**Comment by oulinbao** [comment]
I upgrade the latest version to local pc, it works now, thanks a lot! It's amazing! It's more effective by using vscode plugin and tree view.
