### ISSUE TITLE
Properly split workers and server api for the hybrid remote execution model

### ISSUE THREAD

**Issue by rubenfiszel** [windmill-labs/windmill#279]
Currently, workers can only be run co-located with the server API because they have code dependency on it.

Ideally, there should be a mode where the worker execute itself by only connecting to the server API and not the database directly.

The interface exposed by the server API is an HTTP REST interface, to see if that is sufficient or if websockets are more appropriate for listening for changes such as new jobs in the queue. The worker would need to authenticate himself to the server api with a token at start. That token would be tied to either  or  workspace or the entire instance.

Tokens generated for the entire instance require superadmin privilege. Tokens generated for a workspace only require an admin privilege of the workspace.

**Comment by JokerQyou** [comment]
> Ideally, there should be a mode where the worker execute itself by only connecting to the server API and not the database directly.

I see this issue was closed as completed, but I could not find the relative documentation. Currently the default workers require a direct database connection as the API server do. If I'd like to split some data fetch steps to another remote worker, how could I deploy this worker with only HTTP connection to the API server, but not the database?

**Comment by rubenfiszel** [comment]
> > Ideally, there should be a mode where the worker execute itself by only connecting to the server API and not the database directly.
> 
> I see this issue was closed as completed, but I could not find the relative documentation. Currently the default workers require a direct database connection as the API server do. If I'd like to split some data fetch steps to another remote worker, how could I deploy this worker with only HTTP connection to the API server, but not the database?


We've had great success with our customers by simply restricting the role used by the workers to the strict minimum and using a postgresql proxy for maximum security. It's similar to the http model in terms of verifiable security but with much better performances.

**Comment by JokerQyou** [comment]
> by simply restricting the role used by the workers to the strict minimum and using a postgresql proxy for maximum security

By `the role used by the workers` you mean the role of postgresql database (a.k.a. the user connecting to the database)?

**Comment by rubenfiszel** [comment]
> > by simply restricting the role used by the workers to the strict minimum and using a postgresql proxy for maximum security
> 
> By `the role used by the workers` you mean the role of postgresql database (a.k.a. the user connecting to the database)?

Yes, correct
