### ISSUE TITLE
bug:unable to connect to PSQL database with any SSL mode that is not disabled

### ISSUE THREAD

**Issue by ithan** [windmill-labs/windmill#2858]
### Describe the bug

When trying to connect to a PSQL database that uses a sslmode, I get:
Connection error: error during execution of the script: invalid connection string: invalid value for option `sslmode`

### To reproduce

1. Go to resources
2. Click on add resource
3. Add a PSQL database that has a SSL mode, for example vertify-full
4. Try to test the connection, it will fail with the error:   invalid value for option `sslmode`

### Expected behavior

The connection should be established or fail for a reason

### Screenshots

![image](https://github.com/windmill-labs/windmill/assets/4442226/a21eb5f2-3aa6-4e4b-aa93-c414a7be08f2)

### Browser information

Firefox 120.0.1 

### Application version

Windmill version -> CE v1.224.0

**Comment by HugoCasa** [comment]
we're fixing the issue for verify-ca/full (#2861)
however we could not reproduce with "require" which worked correctly in our tests

**Comment by ithan** [comment]
Hello! Thanks for the update!

About the "require", yesterday during our test it was not working, but it may have been something from our side since it works now
