### ISSUE TITLE
After creating app I get a blank page.

### ISSUE THREAD

**Issue by CMCDragonkai** [windmill-labs/windmill#2903]
See the recorded gif.

It's just broken, nothing I can do.

![Peek 2023-12-21 15-16](https://github.com/windmill-labs/windmill/assets/640797/8ec294aa-0dae-4c68-81b0-bcc40a0939f8)

**Comment by CMCDragonkai** [comment]
I can view the app, but I cannot edit the app. Just completely blank and all navigation is then broken.

**Comment by rubenfiszel** [comment]
Will look into it right away

**Comment by rubenfiszel** [comment]
The issue happens if the first thing you do on a new app is "save initial app". It won't happen if you deploy directly. It will be fixed this afternoon

**Comment by rubenfiszel** [comment]
fixed in latest
