### ISSUE TITLE
bug: using emojis in script's code breaks ui

### ISSUE THREAD

**Issue by lplit** [windmill-labs/windmill#291]
UI breaks when an emoji is inserted in script's code. 
It's possible to refresh to fix the unresponsiveness, but the UI breaks again when attempting to edit the script.

**To Reproduce** 

1. Create new script
2. Paste an emoji anywhere inside the code in step 2
3. UI becomes unresponsive

Initially broke with [🎐](https://emojipedia.org/wind-chime/), but was able to reproduce with several others.

**Windmill version** v1.23.0-34-ge85c60ff

**Comment by rubenfiszel** [comment]
Fixed in 6b61227481422fe52384f6de8146388a8471ff60
