### ISSUE TITLE
bug: wmill cli can not add workspace to a local https windmill site

### ISSUE THREAD

**Issue by oulinbao** [windmill-labs/windmill#2916]
### Describe the bug

I deployed windmill (1.219.1) in minikube and k8s (1.28.3) and used ingress with a self-signed certificate for windmill.com. But when I used cli to add workspace for sync pull the workflow scripts, it's failed. BTW, the certificate is valid in the browser already.

### To reproduce

1. install minikube and k8s
2. deploy windmill in minikube
3. deploy kubernetes ingress and make self signed cert for it
4. add wmill workspace

### Expected behavior

can sync pull workflow script from https site which with self-signed cert

### Screenshots

windmill wmill workspace add windmill-https fortihawkeye-v2 https://windmill.com:30896/
? How do you want to login › Browser
Login by going to https://windmill.com:30896/user/cli?port=47168
✅ Granted run access to "open".
Opened browser for you
! Credentials or instance is invalid. Aborting.
error: Uncaught (in promise) TypeError: error sending request for url (https://windmill.com:30896/api/workspaces/exists): error trying to connect: invalid peer certificate: UnknownIssuer
    return await fetch(url, request);
           ^
    at async mainFetch (ext:deno_fetch/26_fetch.js:277:12)
    at async fetch (ext:deno_fetch/26_fetch.js:504:7)
    at async sendRequest (https://deno.land/x/windmill@v1.226.1/windmill-api/core/request.ts:219:12)
    at async https://deno.land/x/windmill@v1.226.1/windmill-api/core/request.ts:289:34

### Browser information

Version 120.0.6099.129 (Official Build) (x86_64)

### Application version

windmill 1.219.1

**Comment by rubenfiszel** [comment]
Can you try adding: `--unsafely-ignore-certificate-errors` to the `deno install` command and see if that solves your issue

**Comment by oulinbao** [comment]
➜  ~ deno install --unstable --unsafely-ignore-certificate-errors -f -A https://deno.land/x/wmill/main.ts

DANGER: TLS certificate validation is disabled for all hostnames
✅ Successfully installed wmill
➜  ~
➜  ~
➜  ~ wmill workspace add windmill-https fortihawkeye-v2 https://windmill.com:30896/
? How do you want to login › Browser
Login by going to https://windmill.com:30896/user/cli?port=23303
Opened browser for you
! Credentials or instance is invalid. Aborting.
error: Uncaught (in promise) TypeError: error sending request for url (https://windmill.com:30896/api/workspaces/exists): error trying to connect: invalid peer certificate: UnknownIssuer
    return await fetch(url, request);
           ^
    at async mainFetch (ext:deno_fetch/26_fetch.js:277:12)
    at async fetch (ext:deno_fetch/26_fetch.js:504:7)
    at async sendRequest (https://deno.land/x/windmill@v1.95.1/windmill-api/core/request.ts:219:12)
    at async https://deno.land/x/windmill@v1.95.1/windmill-api/core/request.ts:289:34
➜  ~

**Comment by oulinbao** [comment]
Will it pass if it's a public cert?

**Comment by rubenfiszel** [comment]
Yes it will work with a public cert @oulinbao

**Comment by oulinbao** [comment]
@rubenfiszel I have got a public cert, but it still not works. Could you help?

➜  ~ wmill workspace add qa1 xxxx-v2 https://windmill.xxxx.com/
? How do you want to login › Token
? Enter your token › ******************************
! Credentials or instance is invalid. Aborting.
error: Uncaught (in promise) TypeError: error sending request for url (https://windmill.fortihawkeye.com/api/workspaces/exists): error trying to connect: invalid peer certificate: UnknownIssuer
    return await fetch(url, request);
           ^
    at async mainFetch (ext:deno_fetch/26_fetch.js:277:12)
    at async fetch (ext:deno_fetch/26_fetch.js:504:7)
    at async sendRequest (https://deno.land/x/windmill@v1.95.1/windmill-api/core/request.ts:219:12)
    at async https://deno.land/x/windmill@v1.95.1/windmill-api/core/request.ts:289:34
➜  ~
➜  ~➜  ~ curl https://windmill.xxxxxx.com
<!DOCTYPE html>
<html lang="en">
	<head>

**Comment by rubenfiszel** [comment]
It seems your certificate is invalid.

We do provide extensive support for our enterprise customers and could guide you more extensively to setup windmill if you were to go for the enterprise edition.

**Comment by oulinbao** [comment]
DENO_CERT=root.crt wmill workspace add ...
This is ok for public cert :)

**Comment by rubenfiszel** [comment]
It looks like `DENO_TLS_CA_STORE=system` could have worked as well (maybe?)
