### ISSUE TITLE
feature: Prevent schedules from starting new jobs when the previous is still running

### ISSUE THREAD

**Issue by andnofence** [windmill-labs/windmill#2919]
We are exploring Windmill as a replacement for Dagster which we use to execute our data pipelines. Common to many of these is that they perform incremental loading of data, often using microbatches. To achieve this we use scheduled tasks that run anywhere from every 5 seconds to once a day.

Sometimes we run into issues that cause the tasks to slow down. When this happens we start piling up overlapping runs. This is problematic for us both because it can lead to data duplication, but also because it causes even more pressure on the system.

It would be great if schedules offered an option to only start new runs of the schedule when no existing jobs are active.

**Comment by rubenfiszel** [comment]
done in latest:
![image](https://github.com/windmill-labs/windmill/assets/275584/ebe2112a-c6c3-4dee-ac5d-39390d79b01e)

**Comment by andnofence** [comment]
I've updated my instance and turned on the flag. Amazed to see this implemented so quickly! 😄👏
