### ISSUE TITLE
bug: Windmill installation fails: Error Migrating database on fresh installation

### ISSUE THREAD

**Issue by manuelkamp** [windmill-labs/windmill#2923]
### Describe the bug

Error: Migrating database: while executing migrations: error returned from database: syntax error at or near "TRIGGER"

Caused by:
    0: while executing migrations: error returned from database: syntax error at or near "TRIGGER"
    1: error returned from database: syntax error at or near "TRIGGER"
    2: syntax error at or near "TRIGGER"

### To reproduce

first start ever:
docker compose up -d
see logs of container to find this error

### Expected behavior

migrate (or do initial database setup)

### Browser information

n.a.

### Application version

ghcr.io/windmill-labs/windmill:main

### Additional Context

using dedicated postgres server (configured in .env file). Connection seems to be ok, the migration script seems to have a syntax error.

**Comment by rubenfiszel** [comment]
windmill require PG >= 14 due to one of our migration relying on a syntax that only exist from PG14 upward

It's possible to skip it by applying the migration by hand:

```

CREATE FUNCTION "notify_global_setting_delete" ()
RETURNS TRIGGER AS $$
BEGIN
    PERFORM pg_notify('notify_global_setting_change', OLD.name::text);
    RETURN OLD;
END;
$$ LANGUAGE PLPGSQL;
  
REPLACE TRIGGER "notify_global_setting_delete"
 AFTER DELETE ON "global_settings"
    FOR EACH ROW
EXECUTE FUNCTION "notify_global_setting_delete" ();

UPDATE _sqlx_migrations SET checksum = '\\x73d147a83a3251281c126e62280f905ac15467f7164e1da8dfa03f7cdd0e9792d13288cdbbe78129a77f2d9a01a24dab' WHERE version = '20231002123723';
```

**Comment by manuelkamp** [comment]
well...I am running 12.17 and cannot upgrade due to dependencies of other apps using postgres. however, manually executing is also not possible:

```
ERROR:  syntax error at or near "REPLACE"
LINE 9: REPLACE TRIGGER "notify_global_setting_delete"
```

**Comment by rubenfiszel** [comment]
I made a small mistake in the snippet above, it's CREATE and not REPLACE. 

And the last command should be:
```
INSERT INTO _sqlx_migrations (version, description, installed_on, success, checksum, execution_time) VALUES (20231002123723, '', now(), True, '\\x73d147a83a3251281c126e62280f905ac15467f7164e1da8dfa03f7cdd0e9792d13288cdbbe78129a77f2d9a01a24dab', 0);
```

**Comment by manuelkamp** [comment]
ok, thanks, that worked, but now the error is:
```
Error: Migrating database: migration 20231002123723 was previously applied but h                                                                   as been modified

Caused by:
    migration 20231002123723 was previously applied but has been modified
```

**Comment by rubenfiszel** [comment]
Apologies, I made a typo for the last statement. It's:
```
INSERT INTO _sqlx_migrations (version, description, installed_on, success, checksum, execution_time) VALUES (20231002123723, '', now(), True, '\x73d147a83a3251281c126e62280f905ac15467f7164e1da8dfa03f7cdd0e9792d13288cdbbe78129a77f2d9a01a24dab', 0);
```

or 

```
update  _sqlx_migrations set checksum = '\x73d147a83a3251281c126e62280f905ac15467f7164e1da8dfa03f7cdd0e9792d13288cdbbe78129a77f2d9a01a24dab' where version = 20231002123723;
```

if you already inserted it @manuelkamp
