### ISSUE TITLE
bug: --fail-conflicts isn't working

### ISSUE THREAD

**Issue by andnofence** [windmill-labs/windmill#2942]
### Describe the bug

I don't think the --fail-conflicts option is working. When I sync using the --yes and --fail-conflicts flags in my github workflow the changes from the remote overwrite the changes I'm trying to push.

### To reproduce

While the full flow involves git in the middle, it can be reproduced using two Windmill instances (in my case I have my local Windmill instance and a remote Windmill instance (my production instance).

1. Create a script in a local workspace, e.g:

```
def main():
    print("test")
```

2. Pull the script down to your local filesystem:

        wmill sync pull

```
╰─$ wmill sync pull
Computing the files to update locally to match remote (taking .wmillignore into account)
remote (ndap) -> local: 2 changes to apply
+ script f/tools/sync_test.script.yaml
+ script f/tools/sync_test.py
```

3. Switch workspace to the "prod" workspace and push the script:

        wmill switch prod_ndap
        wmill sync push

Already at this point there's a problem, the sync command suggests to delete the script locally:

```
─$ wmill sync push
You need to be up-to-date before pushing, pulling first.
Computing the files to update locally to match remote (taking .wmillignore into account)
remote (prod_ndap) -> local: 2 changes to apply
- script f/tools/sync_test.script.yaml
- script f/tools/sync_test.py
```

4. Use --skip pull

        wmill sync push --skip pull

```
╰─$ wmill sync push --skip-pull
Computing the files to update on the remote to match local (taking .wmillignore into account)
remote (prod_ndap) <- local: 2 changes to apply
+ script f/tools/sync_test.script.yaml
+ script f/tools/sync_test.py
? Do you want to apply these 2 changes? (Y/n) › Yes
Applying changes to files ...
Creating script with a parent f/tools/sync_test

Done! All 2 changes pushed to the remote workspace ndap named prod_ndap.
```

5. Edit the script in a conflicting way
For example, I added a print line in local like this:
```
def main():    
    print("local")
    print("test")
```

And then in the prod instance I instead did this:

```
def main():    
    print("prod")
    print("test")
```

6. Run sync push to prod (which is what the git workflow does)

```
╰─$ wmill sync push --fail-conflicts
You need to be up-to-date before pushing, pulling first.
Computing the files to update locally to match remote (taking .wmillignore into account)
remote (prod_ndap) -> local: 1 changes to apply
~ script f/tools/sync_test.py
def main():
    -print("local")
    +print("prod")
    print("test")
? Do you want to apply these 1 changes? (Y/n) › No
Pull done, now pushing.

Computing the files to update on the remote to match local (taking .wmillignore into account)
remote (prod_ndap) <- local: 1 changes to apply
~ script f/tools/sync_test.py
def main():
    -print("prod")
    +print("local")
    print("test")
```

(The colors are lost so I've added the +/- prefixes)

As you can see the sync tool suggest to run pull first which will delete my "local" line and replace it with "prod". As I answer no it then attempts to push my "local" line.

### Expected behavior

The tool should fail on a conflict (and it shouldn't attempt to delete my new changes on the first push either)

### Additional Context

I first tested this on wmill 1.227.1 and then updated to 1.232.0 which was used for this test.

**Comment by rubenfiszel** [comment]
I will write a longer answer later but to sync between workspaces, what you want is actually --raw

**Comment by andnofence** [comment]
Perhaps I should have made this clearer: I experience this problem when using a Github workflow. The full workflow I have is this:
1. Develop locally using `wmill sync` to keep my local git code and my local wmill instance is sync
2. Push the changes to my git repo which I based on https://github.com/windmill-labs/windmill-sync-example
3. The github workflow then pushes the changes to my production Windmill instance

The problem I'm having is that the `--fail-conflicts` option isn't working as expected. And in fact I also experience the problem shown in step 3 above here where the github workflow will actually *remove* any new scripts I push.

I tried to simplify the reproduction by taking git out of picture since what the git workflow is essentially doing is just running the `wmill sync` command based on the contents of the filesystem.

**Comment by rubenfiszel** [comment]
There is some confusion about how stateful syncing work in windmill and the difference between --raw and non --raw, why the CLI will pull before it push in stateful sync and how do we detect conflicts.

Stateful sync is only meant to be used with one workspace. When pushing to other workspaces, the --raw option should be used which has for purpose to clone the current repo completely to other workspaces (including deleting what is on the target workspace and not locally). It is not possible to detect merge conflicts to other workspaces at the moment. For that, we would need a .wmill folder per workspace.

In stateful sync (non --raw)
.wmill is a snapshot of the last pull. It allows to compute on the next pull, what are conflicting and non conflicting changes.  If a file has been modified by another person (in the UI or through their own CLI sync), we can detect that the current state of the file is different than the one we had for last pull and highlight that there is a conflict if it has also been modified locally (file state is different than in .wmill)

Why do we pull before we push?

Because we detect the conflicting changes during pull (not push) and deployment should be done after solving your merge conflicts. 

So I believe that your feature request is to make .wmill specific to the workspace one is currently syncing to.

**Comment by andnofence** [comment]
My high level goal is to have a workflow where I can work locally against my local Windmill and then get the changes into prod using git, i.e. I don't want to ever bypass git and push directly to the prod instance using sync. I'm actually not sure if I want to allow making changes directly in prod and thus need the github "pull to main" workflow, my instinct tells me it's a recipe for trouble, but for now I've just used the example actions from your example git workflow repository.

So if I understand you correctly:
1. using --raw in the Github workflow that pushes to the prod instance would completely sync the filesystem code and the Windmill code. 
2. If anyone has made changes in the prod instance those would be lost
3. Unless they are explicitly exempt using .wmillignore). 
4. And there's should be no need for the "pull windmill to main" git workflow

This also means that if someone runs `sync push` against prod by accident we can simply run the github workflow to restore.

One pitfall I can see is that I've sometimes configured secrets in production and if I forget to update the .wmillignore file the secret will be deleted on the next sync. But I was debating this approach with myself. I really like the fact that you can store encrypted secrets in the git repo as this means there's no manual configuration step, everything is in code. And with the permission system I guess it's possible to hide the most important secrets from anyone but Windmill admins.

**Comment by andnofence** [comment]
Assuming we use --raw in the github workflow I'm still not 100% sure how the developers should act locally. When working locally it's quite convenient to build workflows in the UI. To sync the resulting code back to my local filesystem so that I commit it I thus need to run `wmill sync`. So I guess the .wmill folder must be shared? But as you say it's only intended for one workspace, so is my local developer instance a different workspace from my colleague's? It also seems that when I write new scripts I either need to manually create .yaml files, or `wmill sync` to get those generated, correct?

**Comment by andnofence** [comment]
Sorry for spamming, but this is a very important part of the setup for us. To convince the team that Windmill will work for us it's important that the workflow is good (and the code must be in git). So given that:
1. All code should go through git to get to production
2. We have multiple developers
3. We have a single production instance (for the time being no staging)

My understanding now is that the following workflow should achieve this:
1. The `.wmill` folder is in .gitignore.
2. Developers run a local Windmill using `docker compose`
3. When developers start up for the first time they must sync their instance using `--raw`.
4. Developers can make changes through the UI or using their editor of choice. They use `wmill sync` to keep their local instance in sync. When adding new scripts they must either add the necessary `yaml` file by hand, or by pushing to their instance and then pulling the resulting `yaml` file that Windmill generates.
5. After `git pull` developers just run a normal `wmill sync` to update their own instance.
6. Code is committed and PR-ed as normal to Github. The git workflow runs on merges to `main` and uses `--raw` to push the updated code to the prod WM instance.
7. Manually editing code in the prod Windmill instance is not possible, such code will be overwritten by the next github merge to main.
8. There is thus no need for a job that pulls changes from the production instance and back into main
9. As a consequence, there is also no need for automated commits from the git workflow like the example repository does

Perhaps this isn't the right place for this discussion. I guess there's no bug in the `wmill sync` code, just in my understanding of it 😅 I think the Windmill documentation could benefit from clarifying the various workflow options though. But I'd be happy to close this issue and move the discussion somewhere else.

**Comment by andnofence** [comment]
The updates to the recommended approach on how to integrate with git in https://github.com/windmill-labs/windmill-sync-example has the answers I need so I'm closing this issue.
