### ISSUE TITLE
feature: Create secret variables programmaticaly from Python

### ISSUE THREAD

**Issue by andnofence** [windmill-labs/windmill#2943]
The `wmill.set_variable` function creates only non-secret variables. It was easy to create a script to create secret variables, but I think it would be nice if the `set_variable` function added a new optional argument`secret: bool = False` so I could just use a wmill built-in.

**Comment by rubenfiszel** [comment]
will be added on next release, thanks for the feedback

**Comment by rubenfiszel** [comment]
done in latest, part of next release 1.243.1
