### ISSUE TITLE
bug: Built-in script sync hub resource type fail

### ISSUE THREAD

**Issue by vnStrawHat** [windmill-labs/windmill#2949]
### Describe the bug

Hi everyone, 

I try to deploy winmill instance with helm version 2.0.59. Everything work fine except can not sync resource type with hub.

The built-in script "Synchronize Hub Resource types with instance" execute with error "Credentials or instance is invalid. Aborting"

![image](https://github.com/windmill-labs/windmill/assets/4435695/6fc80959-d3c4-4f27-b6a6-4852abf3f4b4)

I was try to run the same command with wmill CLI but output is same:
![image](https://github.com/windmill-labs/windmill/assets/4435695/5e18bce3-26c5-47c2-a00c-5e3a8f3364a2)

Is this a bug or am i missing something ?

### To reproduce

1. Go to 'admins workspace'
2. Click on script 'Synchronize Hub Resource types with instance'
3. Click Run

### Expected behavior

script run successfully

**Comment by rubenfiszel** [comment]
Can you run:
`echo $BASE_INTERNAL_URL`
and share the result. Are you using the raw helm chart without modification ?
For the second issue, you seem to be unable to connect to the instance URL from where you ran the command. "Forbidden" is not an http status code you would get from windmill so most likely you have an ingress issue that filter that request.

**Comment by vnStrawHat** [comment]
Hi @rubenfiszel,

Thanks for your response. Out infastructure can not directly to internet, so the HTTP_PROXY and HTTPS_PROXY is root cause. 
after bypass proxy for localhost by adding env NO_PROXY=localhost. I was able to sync resource type from hub.
