### ISSUE TITLE
bug: forloop jobs results are collected not necessarily in the order of the steps

### ISSUE THREAD

**Issue by rubenfiszel** [windmill-labs/windmill#295]
@sqwishy 

This is because 

```                let results = sqlx::query_as(
                    "
                  SELECT result
                    FROM completed_job
                   WHERE id = ANY($1)
                     AND workspace_id = $2
                     AND success = true
                    ",
                )
                .bind(jobs.as_slice())
                .bind(w_id)
                .fetch(db)
                .map_ok(|(v,)| v)
                .try_collect::<Vec<serde_json::Value>>()
                .await?;
```

Does not follow necessarily the order of jobs.  Thoughts on how to fix ? Maybe returning the id as well and then aligning the order of jobs id and the resulting vec ids ?

**Comment by sqwishy** [comment]
Yeah sorry I tried to point this out in a comment in the PR earlier but I guess it wasn't visible [1]. My *assumption* there was to add `ORDER BY` to the query -- given the job id is sequential each iteration will have a larger id than previous iterations.

[1] https://github.com/windmill-labs/windmill/pull/257#discussion_r930453572

**Comment by rubenfiszel** [comment]
@sqwishy that is smart. will do just that

**Comment by rubenfiszel** [comment]
There is likely even smarter, you can order by the _index arg in the flow input :)

**Comment by rubenfiszel** [comment]
Sorting by id is not super feasible since the id is uuid

**Comment by sqwishy** [comment]
Yeah I wasn't certain about that when I added the comment. I didn't look at it too much but I _think_ since you're generating UUIDs from `ulid` it should be generated sequentially or monotonically or whatever but I'm not 100%.

**Comment by rubenfiszel** [comment]
You might be right but this is even more certain: https://github.com/windmill-labs/windmill/commit/df6a44a949c2ca2d27bb545e5f1a4d4760f3df03

**Comment by rubenfiszel** [comment]
(had to force push the as index typo I made: https://github.com/windmill-labs/windmill/commit/0c5a7f12bae92cbf27641736c3b915c728483be0)
