### ISSUE TITLE
bug: Deleting workspace fails with FK violation

### ISSUE THREAD

**Issue by andnofence** [windmill-labs/windmill#2960]
### Describe the bug

I tried to delete a workspace in my local Windmill instance and got a FK violation. I'm not sure which token is causing this so I don't know how to get out of this state.

The detailed error message:

```
windmill-db-1                      | 2024-01-05 14:46:34.176 UTC [56371] ERROR:  update or delete on table "workspace" violates foreign key constraint "token_workspace_id_fkey" on table "token"
windmill-db-1                      | 2024-01-05 14:46:34.176 UTC [56371] DETAIL:  Key (id)=(kid) is still referenced from table "token".
windmill-db-1                      | 2024-01-05 14:46:34.176 UTC [56371] STATEMENT:  DELETE FROM workspace WHERE id = $1
windmill-windmill_server-1         | 2024-01-05T14:46:34.176591Z ERROR request: windmill_common::error: error="Sql error: error returned from database: update or delete on table \"workspace\" violates foreign key constraint \"token_workspace_id_fkey\" on table \"token\"" method=DELETE uri=/api/workspaces/delete/kid username="***" email="***"
```

### To reproduce

This workspace was very basic, I had just created it and added two small scripts, so I guess it's sufficient to:
1. Create a workspace
2. Try to delete it

### Expected behavior

It should be possible to delete a workspace, or get a good error message that explains what to do in case something is preventing the delete.

**Comment by rubenfiszel** [comment]
Thanks for the report, will fix shortly

**Comment by rubenfiszel** [comment]
This is fixed on latest
