### ISSUE TITLE
bug: AgGrid not firing result change event on edit when source is Postgres

### ISSUE THREAD

**Issue by andness** [windmill-labs/windmill#3053]
### Describe the bug

When the source for an AgGrid is a Postgres query, declaring a frontend background runnable that depends on the `.result` property of the AgGrid does not work.

### To reproduce

I've reproduced this here: https://app.windmill.dev/apps/edit/u/andness/aggrid_not_calling_dependent_script_with_sql_source

The `bg_0` runnable is set up to watch `a.result` and updates `state.ranAt` when it runs. The AgGrid is set up to be editable. When I edit a cell and hit enter `bg_0` does not fire. This works correctly if the source is the static data source, and I also have an AgGrid using a Python source which works fine.

### Expected behavior

`bg_0` should fire when I hit enter to submit an edit to the AgGrid.

### Application version

1.248.0

**Comment by andness** [comment]
I take back what I said about it working for a Python source, it doesn't.

FWIW a simple workaround (and perhaps better solution anyway?) was to depend on the `newChange` property.

**Comment by rubenfiszel** [comment]
This should be fixed on latest
