### ISSUE TITLE
feature: Provide a method to accept user-input for scripts and flows that can be masked in the job run history

### ISSUE THREAD

**Issue by jstaffin-presidio** [windmill-labs/windmill#3142]
We would like a way to mask script or flow input in some way in the UI.

Example use-case:
user runs a script that includes an input arg for a sensitive value such as a password or SNMP community string.
when viewing the job run sensitive, the input arg is masked from view. 

A suggested way to handle this could be for the UI to create a linked secret variable, scoped to the user or schedule running the script or flow, that could accept the input and automatically store it in the secret variable, then provide the reference to the variable when queueing the job

**Comment by rubenfiszel** [comment]
@fatonramadani this can be complementary to the new `password` field option.

When the schema form is used in the context of the new run page and a field is secret, when you press run, the password would be assigned to the secret `u/<user>/run_secret_<script_path>_<timestamp>` and in the variable/secret page, we would have a dedicated tab for those (if any) and have a button to clear them all.

**Comment by rubenfiszel** [comment]
Done, every string input marked as a password input now behaves as explained above: 
![image](https://github.com/windmill-labs/windmill/assets/275584/6e3f80bb-3a56-408f-886d-627033ba10e6)
 meaning only the caller can see it

**Comment by gabriel-r** [comment]
Would this be a good way to handle PII (in the GDPR sense) data? This would be data that I may want to see during the run, but not log it.
