### ISSUE TITLE
bug:Sql error: error returned from database: permission denied to set role "windmill_admin"

### ISSUE THREAD

**Issue by lingxuzi** [windmill-labs/windmill#3155]
### Describe the bug

Server shows Sql error: error returned from database: permission denied to set role "windmill_admin" after few hours

### To reproduce

deploy a python script and wait for few hours

### Expected behavior

Everything works

**Comment by rubenfiszel** [comment]
This section should be helpful: https://www.windmill.dev/docs/advanced/self_host#use-an-external-database

![image](https://github.com/windmill-labs/windmill/assets/275584/af9eba97-c116-409f-b83c-f9b47ca302fe)
