### ISSUE TITLE
bug: Windmill exposing credentials in pypi index urls in lock files

### ISSUE THREAD

**Issue by sspencer-hubble** [windmill-labs/windmill#3173]
### Describe the bug

We use AWS Codeartifact for our internal pypi repo for Python.  This means that we authenticate to this private repo with a token (that changes after 12 hours).  Whenever I try to upload a script, it grabs my currently configured pypi repo URL (which includes my personal credentials) and throws them into the lock section of the script yaml.  There does not appear to be a way to stop this.  I have to manually clear out these rows.  Related, as far as I can tell there is no way to handle this kind of auth in Windmill.  I would like if there were some way to handle setup/configuration of PyPi before a script runs, globally, but that's a different issue.  In short, I think Windmill should detect basic auth credentials in any configured pypi index urls and at least warn the user if not refuse to add them automatically to lock files.  The current naive copying is very dangerous.

### To reproduce

1.  Create a file at $HOME/.config/pip/pip.conf

```
[global]
index-url = https://aws:fakecreds@notreal-12353464678853.d.codeartifact.us-east-1.amazonaws.com/pypi/python/simple/
```

2. Create a python script with dependencies and run:
`wmill script generate-metadata`

3.  Observe that the script.yaml file has the above --index-url with credentials in it.

### Expected behavior

There should be some way to configure the behavior around, this or some sort of warning that credentials are about to be exposed.

**Comment by rubenfiszel** [comment]
Hi @sspencer-hubble , aws codeartifact is handled by the enterprise edition.

About the rest, i'm very surprised by what you are describing since:
`wmill script generate-metadata` doesn't rely on your local pip but on the remote instance dependency install jobs
