### ISSUE TITLE
bug: CLI - Deno warning about --unstable flag

### ISSUE THREAD

**Issue by btorresgil** [windmill-labs/windmill#3197]
### Describe the bug

Running `wmill` cli command on Deno 1.40.x (possibly other versions) produces the following warning:

```
⚠️  The `--unstable` flag is deprecated and will be removed in Deno 2.0. Use granular `--unstable-*` flags instead.
Learn more at: https://docs.deno.com/runtime/manual/tools/unstable_flags
```

### To reproduce

1. Install latest Deno
2. Install wmill cli with `deno install -q -A https://deno.land/x/wmill/main.ts`
3. Run `wmill` without any arguments
4. Observe warning

### Expected behavior

Should not be a warning, expected to use granular `--unstable-*` flags instead of deprecated `--unstable` flag.

### Application version

Deno 1.40.3 and wmill cli v1.266.1

**Comment by rubenfiszel** [comment]
You must have a previous install of wmill with --unstable. Try uninstalling wmill and then installing again with the command from your issue

**Comment by btorresgil** [comment]
@rubenfiszel That resolved it. Thanks!

For anyone finding this, I used these commands to resolve:

```
# Uninstall wmill cli
deno uninstall wmill

# Reinstall wmill cli
deno install -q -A https://deno.land/x/wmill/main.ts
```
