### ISSUE TITLE
bug: Sleep parser in flows not parsing correctly

### ISSUE THREAD

**Issue by nullhack** [windmill-labs/windmill#3238]
### Describe the bug

I'm trying to make the flow sleep for a random time after the first step. But it is not parsing the `result` of the first step correctly 

### To reproduce

Run the following flow:

```bash
summary: ""
description: ""
value:
  modules:
    - id: a
      sleep:
        expr: result
        type: javascript
      value:
        lock: ""
        type: rawscript
        content: |-
          MAX_DELAY="$1"

          echo $(($RANDOM % MAX_DELAY))
        language: bash
        input_transforms:
          MAX_DELAY:
            expr: flow_input.MAX_DELAY
            type: javascript
        tag: ""
    - id: b
      value:
        lock: ""
        type: rawscript
        content: |
          echo "Hello World"
        language: bash
        input_transforms: {}
schema:
  $schema: https://json-schema.org/draft/2020-12/schema
  properties:
    MAX_DELAY:
      type: integer
      description: ""
      default: 10
      format: ""
      min: 1
  required: []
  type: object
  order:
    - MAX_DELAY
```

### Expected behavior

I expect the parser to parse the output as a random number e.g. 4 instead of Ok(String("4"))

### Screenshots

![image](https://github.com/windmill-labs/windmill/assets/11466701/025ae9f3-c03e-4fc0-bb16-92ae0545262a)

**Comment by rubenfiszel** [comment]
it's not really a bug, result is a string since it comes from bash. Replace:
`        expr: result`
with:
`        expr: Number(result)`

**Comment by nullhack** [comment]
Works! thank you @rubenfiszel
