### ISSUE TITLE
feature: passing arguments to published application via URL variables 

### ISSUE THREAD

**Issue by Girgitt** [windmill-labs/windmill#3341]
Hello, I have rather a question than a feature request. 

Is it possible to pass values to application via URL variables added to URL under which given application UI is published  (and then use such variables as values for input fields or pass to scripts etc.) ?  

I mean a feature similar to what Grafana offers for its dashboards (https://grafana.com/docs/grafana/latest/dashboards/build-dashboards/create-dashboard-url-variables/#passing-multiple-values-for-a-variable).

**Comment by rubenfiszel** [comment]
In apps, you can get the query args under ctx.query. For the script/flow runs page, it is something we are working on.

**Comment by Girgitt** [comment]
Thank you. Your response time is amazing.
