### ISSUE TITLE
feature: Add proper documentationLink in tooltip of component config

### ISSUE THREAD

**Issue by hcourdent** [windmill-labs/windmill#3360]
https://github.com/windmill-labs/windmill/assets/122811744/e5a391d4-778a-44d8-ac1b-e43fcba2b032

would there be possible to make documentationLinks available for tooltips of components' configurations ?

Currently is quite painful to access link. These are currently defined at the component configuration level as just a string, we need to support links as well.

https://discord.com/channels/930051556043276338/1031563807694258176/1189208166001541240

**Comment by fatonramadani** [comment]
@hcourdent We can already do that, we need to update the [components.ts](https://github.com/windmill-labs/windmill/blob/main/frontend/src/lib/components/apps/editor/component/components.ts)

```typescript		
tooltip: 'Sets how an animation progresses through the duration of each cycle.',
documentationLink: 'https://developer.mozilla.org/en-US/docs/Web/CSS/animation-timing-function'
