### ISSUE TITLE
Incorrect times in "Previous Runs" table

### ISSUE THREAD

**Issue by hershagarwal** [windmill-labs/windmill#3459]
I had an error with a workflow in my 8am run, but when I looked at previous runs, it showed it was successful. The times are actually all off by one, so the 8am failure is showing up as the 7pm one failing, even though the 7pm one ran successfully.

Below is a screenshot of the previous runs table, and the 8am failure. I accessed this 8am failure by clicking on the 7pm "failure" in the previous runs table.

![image](https://github.com/windmill-labs/windmill/assets/69086073/b7830918-870a-4700-b0cc-82f5e07be2d8)

![image](https://github.com/windmill-labs/windmill/assets/69086073/72d03074-805a-4834-9c5b-ed130f3d6daa)

**Comment by rubenfiszel** [comment]
We use created_at when we should have used started_at. We will fix in the next version, thanks!

**Comment by HugoCasa** [comment]
#3461

**Comment by hershagarwal** [comment]
Hi,

It looks like this issue is still present. When I click on the 9:00 AM run
in the first table, the page it takes me to shows that it was the 11:00AM
run. It looks like they're actually offset somehow, where they are showing
the details for the prior run in the first table.
