### ISSUE TITLE
bug: script execution does not work on arm64

### ISSUE THREAD

**Issue by jackychen-sg** [windmill-labs/windmill#35]
**Describe the bug** A clear and concise description of what the bug is.
after cloned the project I login as admin. and then I create a script. and click `run preview`

**To Reproduce** Steps to reproduce the behavior:

1. cloned the project 
2. run `docker volume create caddy_data && docker-compose up`
3. go to ui, login as admin
4. create a script, and run preview
5. check the log window

**Expected behavior** A clear and concise description of what you expected to
happen.
the script is expected to run successfully

**Screenshots** If applicable, add screenshots to help explain your problem.
<img width="970" alt="image" src="https://user-images.githubusercontent.com/8581013/167752251-e6c12584-750b-4e4f-aa61-7edc1651cf8f.png">

**Additional context** Add any other context about the problem here.

**Comment by rubenfiszel** [comment]
@chenfei-io thanks for the bug-report. 

Could you go on the left menu -> admin -> User Settings and return the printed version in "Running windmill version (backend): XXX" (alternatively: `curl http://localhost:8000/api/version`)

Is there something non-standard about your docker installation ? For instance, are you allowed to run privileged container ? Because of the use of nsjail, running windmill as a privileged container is necessary and that error is reminiscent to me of the container being not run as privileged (even though it is what is specified in the docker-compose). Can you share your docker version and anything to be aware of too ?

**Comment by chenfei-io** [comment]
1. Running windmill version (backend) v1.6.1-1-g9219b65
2. I don't think anything special about my docker installation, this is my `docker version`
```
Client:
 Cloud integration: v1.0.24
 Version:           20.10.14
 API version:       1.41
 Go version:        go1.16.15
 Git commit:        a224086
 Built:             Thu Mar 24 01:49:20 2022
 OS/Arch:           darwin/arm64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.8.1 (78998)
 Engine:
  Version:          20.10.14
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.15
  Git commit:       87a90dc
  Built:            Thu Mar 24 01:45:44 2022
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.5.11
  GitCommit:        3df54a852345ae127d1fa3092b95168e4a88e2f8
 runc:
  Version:          1.0.3
  GitCommit:        v1.0.3-0-gf46b6ba
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by rubenfiszel** [comment]
I am not sure but I would suspect that it is related to being on arm64. I am myself on linux/amd64 and did not encounter the issue trying to reproduce on that exact version. I will investigate more, thank you for the report!

**Comment by rubenfiszel** [comment]
@chenfei-io could you try adding `--platform linux/amd64` to your docker run command ?

**Comment by chenfei-io** [comment]
@rubenfiszel since I am using the docker-compose.
I added the `platform: linux/amd64` after line 21 in `docker-compose.yml` file.

![image](https://user-images.githubusercontent.com/8581013/167824249-aa14cb9a-7e7b-4610-a068-b39c8aaf07da.png)

and after I do `docker-compose up`, it still have the same issue as I mentioned in the first post.

and I also tried restart docker, that doesn't help

**Comment by rubenfiszel** [comment]
Thanks for your attempt. Sorry that it does not seem to work easily.

I will try to get my hands on an arm64 environment but in the meantime, I have created this PR https://github.com/windmill-labs/windmill/pull/44 to experiment with arm64 support. If you are up for it, I will push an image on ghcr for you to try on in the next few minutes.

**Comment by chenfei-io** [comment]
no worries, thanks for the help!
I have tried to refreshed the docker images. but I think it still has the same issue.
```
Creating network "windmill_default" with the default driver
Pulling db (postgres:13)...
13: Pulling from library/postgres
dfdd5ffb2577: Pulling fs layer
504b51ce876f: Downloading [>                                                  ]  42.35kB/4
dfdd5ffb2577: Downloading [>                                                  ]  310.5kB/30.07MB70ff7f: Downloading [====================>                              ]     660B/1.648kB872817: Waiting
dfdd5ffb2577: Downloading [==>                                                ]  1.551MB/30.07MB70ff7f: Download complete
dfdd5ffb2577: Downloading [====>                                              ]  2.476MB/30.07MBde44d5: Waiting
dfdd5ffb2577: Downloading [=====>                                             ]  3.414MB/3
dfdd5ffb2577: Pull complete
504b51ce876f: Pull complete
6d167d70ff7f: Pull complete
de307e992d6e: Pull complete
f5268e872817: Pull complete
974a8608df9f: Pull complete
02e7d1de44d5: Pull complete
d8971303fa6d: Pull complete
7dd0e89c5c72: Pull complete
5d991803adb6: Pull complete
edd926712db3: Pull complete
Digest: sha256:4212d7808c83011f7dc9ef8f46d954fc4b7fa2db720418783be0cd905bbe8d1a
Status: Downloaded newer image for postgres:13
Pulling windmill (ghcr.io/windmill-labs/windmill:main)...
main: Pulling from windmill-labs/windmill
c32ce6654453: Pull complete
f7096f3691f0: Pull complete
ec79109ab657: Pull complete
a914c7c19e4d: Pull complete
db7477d67275: Pull complete
b26df0524a39: Pull complete
4f4fb700ef54: Pull complete
Digest: sha256:1445cbf0d03ca06c7e58d1b84b3a9858b57dbb5ff463aaf9c77b6e84ec54778f
Status: Downloaded newer image for ghcr.io/windmill-labs/windmill:main
Pulling caddy (caddy:)...
latest: Pulling from library/caddy
9981e73032c8: Pull complete
83aa37f2341b: Pull complete
0dc050d3d6ff: Pull complete
8adaff0bd78d: Pull complete
f703c61da5ec: Pull complete
Digest: sha256:eb2cce28a50cb1f20f1e4a13181f3e453e58d20999cffa7750222d9907023b6b
Status: Downloaded newer image for caddy:latest
Creating windmill_caddy_1 ... done
Creating windmill_db_1    ... done
Creating windmill_windmill_1 ... done
Attaching to windmill_db_1, windmill_caddy_1, windmill_windmill_1
```

**Comment by chenfei-io** [comment]
will it be easier if I run it natively on my machine?
I managed to make `cargo run` works and get the UI up and running.
but I got this in the logs window
I believe sth else need to be setup, nsjail or python-client related? but I don't have enough instructions to follow
![image](https://user-images.githubusercontent.com/8581013/167835960-8a0d4dbe-6e95-42fe-b98d-9e234e7bb6d5.png)

**Comment by rubenfiszel** [comment]
Yes you would need to have nsjail installed on your machine and available in your PATH

**Comment by rubenfiszel** [comment]
@chenfei-io I am having issues using the emulator to build for arm64. I am happy to assist you if you wanna attempt further but I'm gonna focus on #1 first. Sorry about that

**Comment by chenfei-io** [comment]
@rubenfiszel thanks for replying.
I am keen to setup this project natively on my machine.  and I will be happy to help to complete the setup documentation for this Repo.
I am currently trying to install  `nsjail` like what you mentioned in your previous comment. 
Could you point me to some other places where I can understand how to install it?

**Comment by rubenfiszel** [comment]
I do not know your distribution so I do not know i there are premade binaries for it. I use arch and I can use the package manager to install nsjail

You can always install it from source. Here is how it's done for the windmill docker image: https://github.com/windmill-labs/windmill/blob/main/Dockerfile#L5-L20
