### ISSUE TITLE
bug: step id same as parent run one branch id

### ISSUE THREAD

**Issue by whollacsek** [windmill-labs/windmill#3520]
### Describe the bug

When coming back to edit an existing flow if we add a new step its id will be assigned the same as their parent id (in this case run one branch) which leads to editor confusion and worse when deleting the step the whole subtree from parent is also deleted since they share the same id.

If we create the run one branch with its child steps in one go this doesn't happen. It might be that the id assignment logic is flawed.

### To reproduce

1. Open an existing flow that has a Run one branch with some branches setup
2. Click on the plus icon to add an action
3. The side pane displays the Run one branch details instead of the action/scripts selector
4. If we now click on the Export button we see the assigned step id is the same as the parent Run one branch's id

### Expected behavior

id should be distinct and deleting a step should not delete the parent

### Application version

CE v1.303.2-3-g5cee360bf

**Comment by rubenfiszel** [comment]
could you please send exact reproduction steps:

The export of the flow that you edited
the branch that you added a node to

**Comment by whollacsek** [comment]
Just sent you the .yaml file by email that has this behavior
