### ISSUE TITLE
bug: script - go package retrieved is not latest

### ISSUE THREAD

**Issue by denispol** [windmill-labs/windmill#3523]
### Describe the bug

Windmill does not pick up the latest release available of Go package [go-dbase](https://github.com/Valentin-Kaiser/go-dbase), but the first released version

```
ExecutionErr: ExitCode: 1, last log lines:
call.Handle
../../../cache/go/pkg/mod/github.com/!valentin-!kaiser/go-dbase/dbase@v0.0.0-20220622120602-842944cf2977/table.go:88:32: undefined: syscall.Handle
../../../cache/go/pkg/mod/github.com/!valentin-!kaiser/go-dbase/dbase@v0.0.0-20220622120602-842944cf2977/interpreter.go:98:33: undefined: syscall.Handle
../../../cache/go/pkg/mod/github.com/!valentin-!kaiser/go-dbase/dbase@v0.0.0-20220622120602-842944cf2977/interpreter.go:104:36: undefined: syscall.Handle
../../../cache/go/pkg/mod/github.com/!valentin-!kaiser/go-dbase/dbase@v0.0.0-20220622120602-842944cf2977/io.go:151:36: too many errors
```

### To reproduce

1. Import package "github.com/Valentin-Kaiser/go-dbase/dbase" in Go code on a Windmill instance running on Linux
2. Call dbase.OpenTable on a path (a .dbf file present in "./shared" is easiest)
3. See error

### Expected behavior

Go should download the latest available version of package go-dbase, which is the behaviour if run manually on the same system using `go get`.

### Browser information

Brave, Version 1.64.116 Chromium: 123.0.6312.105 (64-Bit)

### Application version

CE v1.304.2, Azure Linux, Kubernetes

### Additional Context

I am unsure if this is related to the [Go package](https://github.com/Valentin-Kaiser/go-dbase)'s configuration, or if it is an issue with Windmill. Again, this problem does not occur in a local Linux environment using `go get` to retrieve the package. I also replied to an [existing issue](https://github.com/Valentin-Kaiser/go-dbase/issues/56) on the package's repo.

**Comment by rubenfiszel** [comment]
We use "go mod tidy", https://github.com/windmill-labs/windmill/blob/acf80dc6a005ccd048ffc193841b3c599e93c50d/backend/windmill-worker/src/go_executor.rs#L408 can you confirm that this behavior doesn't match the behavior of that command ?

**Comment by denispol** [comment]
It seems that the issue was fixed upstream by the package's owner, however I still struggle with the exact same error in windmill. Despite restarting kubernetes, resetting pods, etc., Windmill uses cached Go packages. Is there any way to clean the cached Go packages, or force a specific package version?

I found the below information in table pip_resolution_cache in postgres:
| hash | expiration | lockfile |
| :--- | :--- | :--- |
| go-42c7345e0b459a3ca477b38562997a339d4a07b5b56b5d932fdcd7e7b0c02103 | 2024-04-08 17:36:13.583505 | module mymod<br/><br/>go 1.21.6<br/><br/>require github.com/Valentin-Kaiser/go-dbase/dbase v0.0.0-20220622120602-842944cf2977<br/><br/>require golang.org/x/text v0.3.7 // indirect<br/>//go.sum<br/>github.com/Valentin-Kaiser/go-dbase/dbase v0.0.0-20220622120602-842944cf2977 h1:IdD5/12dIkjAEsNee02Eo7MuAvKSLo4sZ4/Ygfe0lXI=<br/>github.com/Valentin-Kaiser/go-dbase/dbase v0.0.0-20220622120602-842944cf2977/go.mod h1:9avgiWHapkpDy/pjZKbs7yobyJ9aCMPv3DnEG9hh+Xs=<br/>golang.org/x/text v0.3.7 h1:olpwvP2KacW1ZWvsR7uQhoyTYvKAupfQrRGBFM352Gk=<br/>golang.org/x/text v0.3.7/go.mod h1:u+2+/6zg+i71rQMx5EYifcz6MCKuco9NR6JIITiCfzQ=<br/> |

Thank you for your help

**Comment by denispol** [comment]
The issue was laying in the Go package, in the way the release tags and directories within the module were handled and this caused trouble when not using latest parameter with Go install.
