### ISSUE TITLE
bug: Flow Input default values overflow horizontally

### ISSUE THREAD

**Issue by wasnertobias** [windmill-labs/windmill#3641]
### Describe the bug

When e.g. having a very long String as a default value for a flow input variable the Flow Input view overflows big time. This causes crashing of the browser, if you want to scroll all the way to the right to use the "Delete" or "Edit" buttons etc.

### To reproduce

1. Create Flow (in edit view)
2. Add Argument to the Flow Input, which has a **very big** default value
3. Try to delete the Argument (have fun scrolling)
4. Browser crashes before you can reach the delete button, e.g. Chrome with "Error code: 5"

If no crash happens, you did not choose a big enough default value ;)

### Expected behavior

Text is hidden after a certain length, to avoid insanity

### Browser information

Chromium Version 124.0.6367.92

### Application version

EE v1.320.3-4-g39e1ea3d5

**Comment by rubenfiszel** [comment]
Fixed in [450201d](https://github.com/windmill-labs/windmill/commit/450201deb8f4cd1ef426d0ff6987615f6fbbf5df)
