### ISSUE TITLE
bug: Flow input type "date" not selectable as advanced format

### ISSUE THREAD

**Issue by wasnertobias** [windmill-labs/windmill#3643]
### Describe the bug

We have several input fields with the type marked as "date" format already. It is also shown correctly labeled in the UI as "date":
![Screenshot 2024-04-30 at 15 15 26](https://github.com/windmill-labs/windmill/assets/1354793/e629d3dc-b98b-4a87-a77e-ae077e9f2bd1)

However, when trying to create another "date" field, I do not see any option, which I can select. I can only select "datetime", which I don't want. When investigating which type is already selected for the existing one it shows me the following:
![image](https://github.com/windmill-labs/windmill/assets/1354793/cc1a9a20-f9bf-426d-a00c-838a0d6c631a)

### To reproduce

1. Go to flow input "+ Add Argument"
2. Select "String"
3. Click on "Format"
4. Try to select "date" => It's missing

### Expected behavior

"Date" is selectable as format.

### Browser information

Chromium Version 124.0.6367.92

### Application version

EE v1.320.3-4-g39e1ea3d5

**Comment by wasnertobias** [comment]
It is still possible to create right now, but only through JSON import:
```
{
  "order_date": "2023-01-01"
}
 ```

**Comment by rubenfiszel** [comment]
we need to add date support but we do not support it right now

**Comment by wasnertobias** [comment]
In DatabaseStudio, I have a column with the Type "Date," but it still renders in the Insert Form as date-time.
