### ISSUE TITLE
bug: "Name is required" although name is existing

### ISSUE THREAD

**Issue by wasnertobias** [windmill-labs/windmill#3644]
### Describe the bug

In the UI there are sometimes validations that do seem to cause incorrect warnings, such as "Name is required", although a name is input in the field.
![image](https://github.com/windmill-labs/windmill/assets/1354793/20fde6eb-f8f1-4cff-829b-364d123c5d7c)

### To reproduce

1. Open Flow Input
2. Click on "Edit" button of one Argument
3. Warning is shown for Field name

### Expected behavior

No warning

### Browser information

Chromium Version 124.0.6367.92

### Application version

EE v1.320.3-4-g39e1ea3d5

**Comment by rubenfiszel** [comment]
fixed on latest
