### ISSUE TITLE
bug: Unable to *not* send optional fields through UI

### ISSUE THREAD

**Issue by wasnertobias** [windmill-labs/windmill#3692]
### Describe the bug

If a string field of a flow input is not required, but if it is given, it is validated based on some logic in our case: So it makes a huge difference if the field is set, but an empty value is given or if the field is not set => None value.

Through the UI, if no value is given for a string value, **it falls back to setting the field with an empty string value**, which causes a validation error in our case. Because of that, we have to use the REST interface and Postman for testing any requests.

### To reproduce

Flow input with an optional string field.

### Expected behavior

Give me the possibility to "remove" the field, if it is not required.
Or: Give me the possibility to edit raw JSON data.

### Browser information

Chrome 124.0.6367.119

### Application version

EE v1.323.6-9-g1795522d2

**Comment by fatonramadani** [comment]
![Screenshot 2024-05-21 at 14 56 14](https://github.com/windmill-labs/windmill/assets/456655/23274d87-0137-42bc-b037-8ab9074b56cd)

A field can now be "nullable": If enabled, the default value will be null and not an empty string.
