### ISSUE TITLE
bug:S3 input is unsupported resource for security reasons

### ISSUE THREAD

**Issue by linlin-coder** [windmill-labs/windmill#3713]
### Describe the bug

I set some input key and some key's type are S3-object, during my building app from flows, S3 object cannot use beacuase of security reasons.
![image](https://github.com/windmill-labs/windmill/assets/77706356/4356ca72-ddb0-45de-bb86-ae51376935cd)

### To reproduce

1. create a flow
2. choose inputs, some inputs are S3-object-resource
3. build app

### Expected behavior

when i building a app, and this input can used for file update without security warning.

### Application version

v1.324.1-3-gbb8af8fa9

**Comment by fatonramadani** [comment]
Hi, for security purposes, we need to explicitly white-list the resources you want to expose.
We have a component that let's you do that:
https://www.windmill.dev/docs/apps/app_configuration_settings/resource_select
