### ISSUE TITLE
bug: Bun local imports now failing "error: Cannot find module "./name.ts" from "/tmp/bun/main.ts"

### ISSUE THREAD

**Issue by mattb-prg** [windmill-labs/windmill#3721]
### Describe the bug

Our previously working Bun scripts are currently failing when being run with the following error: 

```
ExecutionErr: ExitCode: 1, last log lines:
error: Cannot find module "./name.ts" from "/tmp/bun/main.ts"
Bun v1.1.7 (Linux x64 baseline)
```

The module that can't be found is a script in the same folder with some exported functions(no main export). Deploying the script works fine though.

### To reproduce

1. Create a Bun script that exports a function.
2. Create a Bun script that imports the above script's function.
3. Attempt to run.

### Expected behavior

The script that imports a local function to run.

### Application version

EE v1.327.0-4-gc3fb407c7

**Comment by rubenfiszel** [comment]
Acked, this seems specific to NSJAIL mode so to the cloud, will be fixed today. Thanks for the report

**Comment by rubenfiszel** [comment]
Should be fixed now, thanks for the report

**Comment by mattb-prg** [comment]
Thanks a lot!
