### ISSUE TITLE
bug: File input UI is incorrectly reset when contained in a conditional tab

### ISSUE THREAD

**Issue by joshuamcginnis** [windmill-labs/windmill#3728]
### Describe the bug

If you add a file to a file input component contained in a conditional tab and then toggle the visibility of the tab containing the file input, when it becomes visible again, the UI doesn't show the attached file but still has the result from the previously uploaded file.

Example app:
[file_toggle_example.json](https://github.com/windmill-labs/windmill/files/15310006/file_toggle_example.json)

### To reproduce

1. Create a conditional tab
2. Create a toggle
3. Add a file component inside a conditional tab dependent upon the toggle.result
4. Add a file
5. Toggle the visibility of the tab
6. Observe the file input UI no longer shows the attached file but the component result is unchanged

### Expected behavior

The file UI should still show the previously attached file between visibility toggles.

**Comment by rubenfiszel** [comment]
Fixed
