### ISSUE TITLE
bug: Copying an unnamed script causes name of new script to be "Copy of "

### ISSUE THREAD

**Issue by wasnertobias** [windmill-labs/windmill#3740]
### Describe the bug

It should rather also be empty!

### To reproduce

1. Copy a script, which is unnamed
2. Name of copied script is "Copy of "

### Expected behavior

The copied script also does not have a name - it is distinguishable through the path. It should also have the same directory selected per default!

**Comment by fatonramadani** [comment]
Fixed in latest
