### ISSUE TITLE
bug: Runs grid overflows horizontally

### ISSUE THREAD

**Issue by wasnertobias** [windmill-labs/windmill#3761]
### Describe the bug

Default view (right panel not increased in size): Scrolling is possible horizontally. The table header is detached.

### To reproduce

1. Have run histories with long paths and long "triggered by" columns
Fullscreen on MacBook Pro 14-inch (3024 × 1964).

### Expected behavior

No detachment of table header! Probably break lines?

### Screenshots

<img width="1355" alt="Screenshot 2024-05-17 at 09 58 46" src="https://github.com/windmill-labs/windmill/assets/1354793/7994d247-1c6d-4721-97e7-19061f9397d9">

### Browser information

Chrome Version 124.0.6367.208

### Application version

EE v1.331.0-2-gf3b8e0198

**Comment by fatonramadani** [comment]
Fixed here: https://github.com/windmill-labs/windmill/pull/3781
