### ISSUE TITLE
bug: False positives on "Confirm deleting step with dependents"

### ISSUE THREAD

**Issue by wasnertobias** [windmill-labs/windmill#3783]
### Describe the bug

Step a is deleted, example:
<img width="515" alt="Screenshot 2024-05-21 at 17 07 24" src="https://github.com/windmill-labs/windmill/assets/1354793/b2eb73fd-8146-477b-b919-015fd043b723">

### To reproduce

See above

### Expected behavior

-

### Application version

EE v1.333.5

**Comment by fatonramadani** [comment]
Fixed: https://github.com/windmill-labs/windmill/pull/3802
