### ISSUE TITLE
feature: Is it possible to delete a workspace?

### ISSUE THREAD

**Issue by waynehamadi** [windmill-labs/windmill#3804]
I can't delete workspace.
I found this :
https://www.windmill.dev/docs/advanced/cli/workspace-management#adding-a-workspace

<img width="871" alt="Screenshot 2024-05-23 at 6 29 31 PM" src="https://github.com/windmill-labs/windmill/assets/9652976/6f50056e-bbb7-4d39-8b66-a0a5ed210bd9">

but this is confusing: this is to remove a workspace from the ones listed in the CLI. It doesn't mean it removes it

**Comment by rubenfiszel** [comment]
workspace settings -> general -> delete

**Comment by waynehamadi** [comment]
thanks
