### ISSUE TITLE
"Use past inputs" not working

### ISSUE THREAD

**Issue by waynehamadi** [windmill-labs/windmill#3827]
### Describe the bug

When clicking on use past input, it doesn't fill the value in:
https://www.loom.com/share/caee4ff5fd43486c8cd105fd4284ccfa

### To reproduce

https://www.loom.com/share/caee4ff5fd43486c8cd105fd4284ccfa

### Expected behavior

It should populate the values

**Comment by waynehamadi** [comment]
working in the input step, not in the test flow step
<img width="1347" alt="Screenshot 2024-05-27 at 4 27 26 PM" src="https://github.com/windmill-labs/windmill/assets/9652976/0c639f7c-2b2d-497a-bd0c-a1403a0d2b58">

**Comment by fatonramadani** [comment]
Fixed on latest
