### ISSUE TITLE
Incorrect copy: "Previous versions of this hash"

### ISSUE THREAD

**Issue by jaller94** [windmill-labs/windmill#383]
On a page of a script, it says "Previous versions of the hash".
That doesn't make any sense, because it's a list of hashes and a hash can't have versions.

![](https://user-images.githubusercontent.com/10872136/183962676-f41d7f0c-3e43-4623-bced-bd490e9e9151.png)

I think this should say:
* Previous versions of this script (favourite, because it's easier to understand)
* Previous hashes of this script

**Comment by rubenfiszel** [comment]
@jaller94 Thanks for catching this wording error. Fixed in favor of:
```
<h3>
	Previous versions of this script <Tooltip
		>When you edit a script, a new hash is created and the hashes corresponding to the
		previous versions of this script are archived</Tooltip
	>
</h3>
```
Lmk if that seems satisfactory ?
