### ISSUE TITLE
feature: identify when an action's input is not connected

### ISSUE THREAD

**Issue by waynehamadi** [windmill-labs/windmill#3857]
I am not going to ask for the exact feature but instead talk about the problem.
It took me some time to find what's wrong with one of my flow: one input campaign_id wasn't populated.
But these types of mistakes are obvious, because if there is an input it should always be populated.

If wish there was an easy way to spot them so I don't spend time debugging this.

<img width="1085" alt="Screenshot 2024-06-01 at 8 42 37 AM" src="https://github.com/windmill-labs/windmill/assets/9652976/16e8d92b-e279-4a2c-b3b7-3302f8bf44b4">

**Comment by fatonramadani** [comment]
We recently added a warning indicator for missing required inputs!
