### ISSUE TITLE
feature: Support for Non-Root iFrame Embedding

### ISSUE THREAD

**Issue by bigcat88** [windmill-labs/windmill#3858]
**Description:**

We are integrating Windmill into Nextcloud, and for this integration to work seamlessly, Windmill needs to support operations within an iFrame that does not use the root address.

**Example iFrame URL:**
```
http://nextcloud.local/apps/app_api/proxy/windmill_app
```

We have configured the correct `kit.paths.base` in `svelte.config.js`, and observed that JS/CSS files are successfully loaded. Additionally, we have set the correct URL for the generated "backend-client" in Windmill, ensuring that all requests to `/api` and some requests to `/user` endpoints are correctly routed.

However, in the TypeScript files of Windmill, all `goto` operations are relative to the root of the site, leading to incorrect redirects.

**Example Windmill Code:**
```typescript
export async function logout(): Promise<void> {
    await clearUser()
    goto(`/user/login`)
    sendUserToast('you have been logged out')
}
```

**Documentation for `goto`:**
```
Params:
url – Where to navigate to. Note that if you've set config.kit.paths.base and the URL is root-relative, you need to prepend the base path if you want to navigate within the app.
opts – Options related to the navigation
```

**Request:**

We kindly request that the Windmill frontend code be modified to respect the `config.kit.paths.base` by prepending it to the path in `goto` operations. This change is crucial for our integration, as manually editing the entire Windmill frontend is not feasible for us.

We appreciate your attention to this matter and want to express our gratitude for maintaining such an excellent open-source project.

**Comment by rubenfiszel** [comment]
The issue with svelte.config.js approach is that it  require to maintain your own fork of windmill which will a heavy burden. Ideally, we can find a solution that work with the stock image of windmill and can be passed as env variable without requiring a re-build of the frontend.

**Comment by rubenfiszel** [comment]
Do you have any possibility to have windmill be hosted as a subdomain, for instance:
http://windmill.nextcloud.local ?

**Comment by rubenfiszel** [comment]
The other possibility that i see is that we have a new image that support windmill not as a SPA with fallback mode, but as a server rendered website (running the frontend on node.js) that you can pass the base as an env variable to the image.

**Comment by bigcat88** [comment]
From what I know, we still want to install Windmill as a container, and it’s not difficult for us to rebuild only the frontend without rebuilding the entire binary when we creating that container.
And to serve frontend from that folder(let's call it static_frontend)

We need all the “goto” to add the 'base' value from svelte.config.js as a prefix. And maybe some "hrefs" with absolute urls need to respect 'base' too.


Something like this: 

```javascript
function customGoto(href, options) {
  const prefix = '/custom-prefix'; // we will take it from "svelte.config.js"
  const modifiedHref = prefix + href;

  // Call the original goto function with the modified URL
  return originalGoto(modifiedHref, options);
}
```

**Comment by rubenfiszel** [comment]
It should work but regardless, you should find out in your tests soon enough. Yes, if you can do the work, we will be gladly accepting your PR, thank you very much!

**Comment by bigcat88** [comment]
Does frontend for EE differs from default one?
As we change `basePath` and plan use frontend from standart image for EE edition - will it work, or the source for EE are different?
