### ISSUE TITLE
bug: too many tokens causing windmill to freeze

### ISSUE THREAD

**Issue by zs-ko** [windmill-labs/windmill#3869]
### Describe the bug

when listing a users token in windmill ui the ui freezes when the user has many tokens. probably should be paginated and searchable. 

### To reproduce

1. Go to user -> account settings
2. See error

### Expected behavior

only return a x number of token

### Screenshots

![image](https://github.com/windmill-labs/windmill/assets/123738040/876cbeb2-fa8b-4a47-9805-1a0732184da9)

**Comment by rubenfiszel** [comment]
Fixed in latest
