### ISSUE TITLE
feature: In table view, allow to select per column

### ISSUE THREAD

**Issue by hcourdent** [windmill-labs/windmill#3878]
Currently, results Table mode is cool, especially as it allows to select rows and download as CSV the selected rows.

Would be cool to have the same for columns: when you get a large result but only want to deal with a few columns, pick them as you would do for rows.

https://github.com/windmill-labs/windmill/assets/122811744/0f3c9a54-629e-4bf2-a8d1-1707205723b8

**Comment by rubenfiszel** [comment]
done
