### ISSUE TITLE
bug: Modal z-order is above editor popup

### ISSUE THREAD

**Issue by dm-canteen** [windmill-labs/windmill#3900]
### Describe the bug

![image](https://github.com/windmill-labs/windmill/assets/109326069/f1352d73-b725-4da6-b06e-a5fbde833eb2)

### To reproduce

1. Add modal to project.
2. Click modal button to open it.
3. Add results to modal.
4. Add frontend script to Modal Results' Data Source.
5. Hover over error in editor, popup renders below Modal.

### Expected behavior

The editor popup should be above the modal as it originates from "outside" the preview window which the modal is filling.

### Screenshots

see above

### Browser information

Firefox 126

### Application version

CE v1.344.3

**Comment by dm-canteen** [comment]
@fatonramadani Thanks for the quick fix, it's almost perfect:
![image](https://github.com/windmill-labs/windmill/assets/109326069/91378eb0-6606-4574-a2d1-ff3874f66460)

**Comment by fatonramadani** [comment]
@dm-canteen Fixed on latest!
