### ISSUE TITLE
feature: Detect TypeScript's implied types in function parameters with defaults

### ISSUE THREAD

**Issue by jaller94** [windmill-labs/windmill#393]
## Script code
```js
export async function main(
  active: boolean,
  enabled: boolean = true,
  sensitive = false,
) {}
```
* `active` and `enabled` state their types explicitly.
* `sensitive` does not state its type explicitly but has a default value from which a type can be implied.

## Detected Inputs
![Screenshot 2022-08-12 at 02-56-29 New Script Windmill](https://user-images.githubusercontent.com/10872136/184265970-f76f8788-200c-4f44-9afa-141cefcb174d.png)
* `active` and `enabled` get a checkbox because their type `boolean` is explicitly stated and picked up by Windmill.
* `sensitive` has the form component of a JSON object.

## Expected
Windmill uses the same logic as TypeScript and implies that the type of `sensitive` is `boolean`.

## Actual
Windmill detects the type of `sensitive` as a JSON object or isn't sure what type it is.

## Notes
The same goes for strings and numbers. TypeScript implies these types, if the default value is of such type.

```js
export async function main(
  amount = 4,
  message = "Hello world!"
) {}
```

**Comment by rubenfiszel** [comment]
That's an interesting one. I've skimmed the docs of typescript and see no notion of implied type. 

My naive understanding of how the typescript compiler could possibly interpret:
`amount = 4` is `amount: any = 4` and not `amount: number = 4` as you're suggesting.

If that is the case, I am bit afraid of diverging from typescript actual signature types.

**Comment by rubenfiszel** [comment]
Done in https://github.com/windmill-labs/windmill/commit/b9dfbfa2d8d86f0313d4f8b1829c27a1b1c1c380
