### ISSUE TITLE
bug: inferArgs err when non-ASCII characters 

### ISSUE THREAD

**Issue by southball** [windmill-labs/windmill#3952]
### Describe the bug

When non-ASCII character is used in script code, arguments inferment from code no longer works and errs.

### To reproduce

1. Create any script, choose TypeScript (Bun) as language
2. Use non-ASCII character in code (emoji / Japanese etc.)
3. Profit (see screenshot)

### Expected behavior

It does not err, and `inferArgs` continue to work

### Screenshots

![image](https://github.com/windmill-labs/windmill/assets/6523469/c4a07ee6-0457-4030-97a2-14187b0cd013)

### Browser information

Chrome Version 126.0.6478.114

### Application version

EE v1.350.3-1-ge5db2782f

### Additional Context

I tried digging into the code. I even threw the `windmill_parser_wasm_bg.wasm` into Ghidra, and before the error `serde_json::to_string` seems to be run, so I think it is likely that the `to_string` returned `Err(/* something */)`.

If someone would tell me how to modify `windmill-parser-wasm/src/lib.rs`, build it and have it be used in my local copy of Windmill frontend I would be grateful, but it might be faster for you to replicate and debug on your side.

To see the bug on TypeScript side, you can modify `parse_deno` in `node_modules/windmill-parser-wasm/windmill_parser_wasm.js` to add `catch (err) { console.error(err); }` to the try-statement, and then run `rm -rf node_modules/.vite && npm run dev`. Then you will the following error.

```
ScriptBuilder.svelte:338 error RuntimeError: unreachable
    at windmill_parser_wasm_bg.wasm:0x3b3f7e
    at windmill_parser_wasm_bg.wasm:0x407748
    at windmill_parser_wasm_bg.wasm:0x405f82
    at windmill_parser_wasm_bg.wasm:0x4196c6
    at windmill_parser_wasm_bg.wasm:0x3c1142
    at parse_deno (windmill-parser-wasm.js?v=ccbd4200:178:10)
    at inferArgs (infer.ts:72:31)
    at async saveDraft (ScriptBuilder.svelte:335:21)
```

**Comment by rubenfiszel** [comment]
Thanks for the repro, we will take a look next week!
All of our parsers are here for reference: https://github.com/windmill-labs/windmill/tree/f626a361c4f8c533ba841319f23db42ee780bc70/backend/parsers

**Comment by ImSingee** [comment]
Encountered this today (cloud version, EE v1.352.0-1-g2a88fcbfd), but without non-ASCII characters:

<img width="1391" alt="image" src="https://github.com/windmill-labs/windmill/assets/11208082/4d8598d8-fa67-465e-a53e-4b58c33fe413">

```js
import { publicDecrypt } from 'node:crypto';
// Remove the above line and the error will disappear

export function main() {
  console.log("hello world")
}
```

**Comment by ImSingee** [comment]
@HugoCasa @rubenfiszel Hi I got a new error now: Unreachable code should not be executed (evaluating 'wasm.parse_ts_imports(s,o,_)')

(Code is the same as I provided previously)

**Comment by rubenfiszel** [comment]
@ImSingee can you test with the latest release please

**Comment by ImSingee** [comment]
@rubenfiszel The error disappears now! Thank you!
