### ISSUE TITLE
Installation of the Windmill Binary works ok but executing it fails with error messages

### ISSUE THREAD

**Issue by bmullan** [windmill-labs/windmill#3956]
### Describe the bug

**Host OS:  Ubuntu 24.04 LTS**

Using the Binary install cmds listed here:  **[https://github.com/windmill-labs/windmill#run-from-binaries](https://github.com/windmill-labs/windmill#run-from-binaries)**

$ BINARY_NAME='windmill-amd64' # or windmill-ee-amd64 for the enterprise edition
LATEST_RELEASE=$(curl -L -s -H 'Accept: application/json' https://github.com/windmill-labs/windmill/releases/latest)
LATEST_VERSION=$(echo $LATEST_RELEASE | sed -e 's/.*"tag_name":"\([^"]*\)".*/\1/')
ARTIFACT_URL="https://github.com/windmill-labs/windmill/releases/download/$LATEST_VERSION/$BINARY_NAME"
**wget "$ARTIFACT_URL" -O windmill**

--2024-06-23 10:25:22--  https://github.com/windmill-labs/windmill/releases/download/v1.352.0/windmill-amd64
Resolving github.com (github.com)... 140.82.114.4
Connecting to github.com (github.com)|140.82.114.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://objects.githubusercontent.com/github-production-release-asset-2e65be/488804911/1d704756-c141-45fc-b0e4-26aa9db7117a?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20240623%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240623T142522Z&X-Amz-Expires=300&X-Amz-Signature=f821c67f3fdf5c2e32db8423a106ec4ddcb33d251ead76608878c850bf6ae3f2&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=488804911&response-content-disposition=attachment%3B%20filename%3Dwindmill-amd64&response-content-type=application%2Foctet-stream [following]
--2024-06-23 10:25:22--  https://objects.githubusercontent.com/github-production-release-asset-2e65be/488804911/1d704756-c141-45fc-b0e4-26aa9db7117a?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20240623%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240623T142522Z&X-Amz-Expires=300&X-Amz-Signature=f821c67f3fdf5c2e32db8423a106ec4ddcb33d251ead76608878c850bf6ae3f2&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=488804911&response-content-disposition=attachment%3B%20filename%3Dwindmill-amd64&response-content-type=application%2Foctet-stream
Resolving objects.githubusercontent.com (objects.githubusercontent.com)... 185.199.109.133, 185.199.110.133, 185.199.111.133, ...
Connecting to objects.githubusercontent.com (objects.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 267797696 (255M) [application/octet-stream]
Saving to: ‘windmill’

**_windmill                                                               100%[==========================================================================================================================================================================>] 255.39M  27.9MB/s    in 11s_**     

2024-06-23 10:25:33 (23.9 MB/s) - ‘windmill’ saved [267797696/267797696]

**$ ls**
windmill

**$ chmod +x ~/windmill**

**$ ~/windmill**
_2024-06-23T14:25:55.193574Z  INFO src/main.rs:125: jemalloc enabled
2024-06-23T14:25:55.193606Z  INFO src/main.rs:187: Mode not specified, defaulting to standalone
2024-06-23T14:25:55.193615Z  INFO src/main.rs:250: Connecting to database...
**Error: Bad config: Either DATABASE_URL_FILE or DATABASE_URL env var is missing**_

### To reproduce

see above

### Expected behavior

no error when executing the 1st time

### Screenshots

see above

### Browser information

Firefox 128.0b6 - 64-bit

### Application version

can't ... not getting that far

### Additional Context

I searched for Open & Closed bugs that might give me an idea what is causing the error but found nothing.

Searched all the Docs & found nothing.  

So I am assuming this is either a Bug or some steps are missing in the section about Installing the Binary?

Any ideas.

**Comment by rubenfiszel** [comment]
The error is telling you that you provided no DATABASE_URL  to a postgresql instance. I recommend studying our docker-compose and Dockerfile to understand how to run the binary.

Running the binary is much harder than using our images and there are many ways to shoot yourself in the foot because of the lack of isolation. For an enterprise setting, we recommend having us you guide you through it.

**Comment by bmullan** [comment]
@rubenfiszel 
If that DATABASE_URL to postgres is required then don't you think it deserves a mention in the README secfion labeled:

**Run from binaries** 

I am more than capable of setting up a database if I know what is needed but the README Run from Binaries section doesn't even mention it as a requirement.

Also,  I certainly can run Docker and do at times.  But for Containers I much prefer either LXD system containers or the newer fork of LXD called Incus & its system containers.   

*Having to use Docker is* **highly redundant** *for people like me and frankly quite unnecessary!*    

I only use Docker when there is some tool I want to use and there is absolutely no alternative what to install it other than Docker.

Although I am interested in trying to use Windmill its not at this point a critical app to me and I'd just like to avoid Docker if possible.

Hope you understand what I am saying _and I DO understand_ why your Windmill Devs might want to utilize Docker.

I'll try to figure it out but may just have to avoid windmill if I can't resolve the problem.

Thanks for the reply!

Brian
