### ISSUE TITLE
bug:  Missing input indicator on the flow step (on required input) not firing after removing dependant step

### ISSUE THREAD

**Issue by wasnertobias** [windmill-labs/windmill#3972]
### Describe the bug

When step b and c depends on a. I am now deleting a, it warns me before doing so. The feature of "missing input on required input indicator" now does not fire, as I would have expected. It assumes that the now clearly invalid "results.a" is ok.

### To reproduce

Described above

### Expected behavior

Warning indicator

**Comment by fatonramadani** [comment]
Fixed in https://github.com/windmill-labs/windmill/pull/4008
