### ISSUE TITLE
bug: Deployment is successful, but no success toast, only error toast

### ISSUE THREAD

**Issue by wasnertobias** [windmill-labs/windmill#3982]
### Describe the bug

Error toast states "Could not parse code, are you sure it is valid?"

No success toast visible

=> Yes, I am sure it is valid btw.

### To reproduce

-

### Expected behavior

Two toasts, or no error toast at all

**Comment by rubenfiszel** [comment]
Could you share the code or a sharable version of it that trigger this error please
