### ISSUE TITLE
bug: Step input incorrectly emptied out, when undoing deletion of flow step

### ISSUE THREAD

**Issue by wasnertobias** [windmill-labs/windmill#3990]
### Describe the bug

When having a flow with a single step or multiple at once (loop) being deleted and then pressing CTRL + Z to undo it the step inputs are all empty.

### To reproduce

1. Open flow editor with some steps, which have inputs
2. Delete a step
3. undo deletion

### Expected behavior

Step input is recovered as well.

**Comment by rubenfiszel** [comment]
@fatonramadani should save the state and restore it after cancel

**Comment by fatonramadani** [comment]
Fixed on latest
