### ISSUE TITLE
bug: Content searching with a lot of results causes UI render bug

### ISSUE THREAD

**Issue by wasnertobias** [windmill-labs/windmill#3996]
### Describe the bug

Developer console shows:
```
data:image/png;base64,${base64String}:1 
GET data:image/png;base64,${base64String} net::ERR_INVALID_URL
```

### To reproduce

Open content search and e.g., search for "g"

### Expected behavior

-

### Screenshots

<img width="1166" alt="image" src="https://github.com/windmill-labs/windmill/assets/1354793/9964739d-996b-4021-b0e1-c8e7b06531e9">

### Browser information

Chrome Version 126.0.6478.116

### Application version

EE v1.349.1-5-g4bfda45c7

**Comment by wasnertobias** [comment]
Ok, it is not limited to only one character. It is reproducible for us with the search string "content".

As the color scheme changes, the results are unreadable, which renders the whole content search unusable. :(

**Comment by rubenfiszel** [comment]
This should be all fixed on very latest
