### ISSUE TITLE
bug: Flow editor and viewer freezes partly

### ISSUE THREAD

**Issue by wasnertobias** [windmill-labs/windmill#4001]
### Describe the bug

"Not recognized input type fields (undefined, javascript)"

When viewing it freezes when clicking on step b (does not show script content / step input).

On initial save it worked just fine.

### To reproduce

Will send you confidential example flow in private.

### Expected behavior

-

### Application version

EE v1.349.1-5-g4bfda45c7

**Comment by rubenfiszel** [comment]
I think we fixed that recently, could you try on latest by any chance?

**Comment by wasnertobias** [comment]
We will update this weekend, will tell you next week.

**Comment by wasnertobias** [comment]
Yes, it seems fixed!
