### ISSUE TITLE
bug: Runs page empty, filter not working

### ISSUE THREAD

**Issue by wasnertobias** [windmill-labs/windmill#4005]
### Describe the bug

Clicking on a run of a hourly flow, then clicking on "Edit schedule", then on "View runs". Forwards to the runs page, which has the path-filter correctly set, but it does not show any runs.

Also I do not understand why there is a time difference in the flow page which shows past runs, looks like it did not run for the current hour, but it did.

### To reproduce

Described above

### Expected behavior

Linked runs page should not be empty, times of last run should be shown correctly.

### Screenshots

<img width="576" alt="Screenshot 2024-07-01 at 10 14 28" src="https://github.com/windmill-labs/windmill/assets/1354793/b68bd892-668d-4455-b37a-29eeebd1992f">
<img width="429" alt="Screenshot 2024-07-01 at 10 14 37" src="https://github.com/windmill-labs/windmill/assets/1354793/6fc45ce4-e482-4c0c-95f2-bb8d7e78ec1a">
<img width="1644" alt="Screenshot 2024-07-01 at 10 15 49" src="https://github.com/windmill-labs/windmill/assets/1354793/b399ace4-f2c9-4f6f-b13e-37907c506bcf">

### Application version

EE v1.355.3

**Comment by rubenfiszel** [comment]
You've disabled the toggle "CRON schedule", admittedly we should default set it to true when coming through this UX flow @fatonramadani  (just the url to change since it's already a query param)

**Comment by rubenfiszel** [comment]
above done on latest
