### ISSUE TITLE
bug:markdown table cannot display the correct format

### ISSUE THREAD

**Issue by linlin-coder** [windmill-labs/windmill#4055]
### Describe the bug

table is normal component in markdown file, but when I use windmill , it cannot display the correct format, as follow
platform version:[v1.356.1](https://github.com/windmill-labs/windmill/releases/tag/v1.356.1), and i create app with docker-compose command  
![image](https://github.com/windmill-labs/windmill/assets/77706356/34d0609f-d66e-4f64-b8b4-4027037b98a5)

### Expected behavior

I look forward to the author fixing the bug

### Browser information

Microsoft Edge 126.0.2592.87 (正式版本) (64 位)

### Application version

v1.356.1

**Comment by fatonramadani** [comment]
Fixed on latest
