### ISSUE TITLE
bug: incorrect cookie secure set

### ISSUE THREAD

**Issue by vanhtuan0409** [windmill-labs/windmill#408]
**Describe the bug**

Authentication cookie is set to `secure`, which will require a TLS to make it work.

**To Reproduce**

1. Setup an internal domain point to windmill. The fastest way is to put it on `/etc/hosts`
2. Go to windmill login page using custom domain
3. Try to login

**Expected behavior**

Windmill should be able to detect the schema from `BASE_URL`. If start with `https` then use secure otherwise if start with `http` then use non secure cookie

**Windmill version**
windmill.dev backend v. v1.30.0-17-g08886c4

**Additional context** Add any other context about the problem here.

Cookie is hardcoded to use secure schema here
https://github.com/windmill-labs/windmill/blob/main/backend/src/users.rs#L1281

**Comment by rubenfiszel** [comment]
Fixed in 1275f5f
