### ISSUE TITLE
bug: Script run shows "0 s" instead of "0.527 s"

### ISSUE THREAD

**Issue by wasnertobias** [windmill-labs/windmill#4083]
### Describe the bug

It shows me "Ran in 0s" although it took 527 ms according to attribute "duration_ms" returned by:
api/w/WORKSPACE_ID/jobs_u/get/JOB_UUID

### To reproduce

-

### Expected behavior

-

### Application version

EE v1.362.0

**Comment by fatonramadani** [comment]
Fixed on latest, thanks for the feedback!
