### ISSUE TITLE
bug: Run labels not working for bash

### ISSUE THREAD

**Issue by wasnertobias** [windmill-labs/windmill#4092]
### Describe the bug

https://app.windmill.dev/run/0190c053-950f-fa20-c801-f28b393eadd1?workspace=demo

### To reproduce

Seems to work with Python, but not with bash?

### Expected behavior

Does also work with bash

### Screenshots

<img width="1075" alt="image" src="https://github.com/user-attachments/assets/83998601-cb16-4759-88a1-a5272449d484">

**Comment by rubenfiszel** [comment]
bash by default has a string output.

If you want a json output, write that string to ./result.json

**Comment by wasnertobias** [comment]
Thanks! :)
