### ISSUE TITLE
Previously stable code suddenly stopped working, only in full flows

### ISSUE THREAD

**Issue by hershagarwal** [windmill-labs/windmill#4144]
I have a script that gets an authorization code from a website after logging in. It's used in several workflows, and has been working perfectly for a while. However, starting on Friday, it suddenly stopped, with the below error message.

If I test the step independently, it still works. However, when it runs as part of a flow (testing or deployed), it results in the below message. Seems like something changed on Windmill's side to cause this.

ExecutionErr: ExitCode: 1, last log lines:

14245 | }
14246 | }
14247 | class CDPClientAdapter extends BidiMapper.EventEmitter {
^
TypeError: undefined is not an object (evaluating 'BidiMapper.EventEmitter') at /tmp/bun/main.js:14247:42
note: missing sourcemaps for /tmp/bun/main.js
note: consider bundling with '--sourcemap' to get unminified traces

Bun v1.1.18 (Linux arm64)

**Comment by hershagarwal** [comment]
The script is located at f/Procare/procare_auth called Procare Authorization Code. It's being used in Daily Time Card and Hourly Procare Alerts

**Comment by rubenfiszel** [comment]
Are you on the cloud ? If yes, what workspace ?

**Comment by hershagarwal** [comment]
Yes, on the cloud, the workspace is "allaroundchildren". Same error also
occurring on "aac_procarereporting" workspace.

**Comment by rubenfiszel** [comment]
We added a new method to optimize runtime performance that pre-bundle the scripts. 

It seems that those scripts in particular could not be bundled with bun 1.1.18 but can in 1.1.21 which we lastly deployed. To make sure your scripts get re-bundled, force it by making a slight change to the script (such as adding a comment) and then redeploy

Also as an escape hatch, one can add `//nobundling` but it seems not necessary here.

**Comment by hershagarwal** [comment]
Ahh gotcha ok.

I had actually tried something similar where I created a new script, and
pasted the code, but actually ran into the same error. I would have though
creating that new script would have fixed the issue, but it didn't.

However, I edited the code like you suggested and it appears to be working,
so I think we're good.

Thanks!
Hersh
