### ISSUE TITLE
bug:  cannot convert between the Rust type `core::option::Option<alloc::string::String>` and the Postgres type `(name of pg enum)`

### ISSUE THREAD

**Issue by m-thomson** [windmill-labs/windmill#4226]
### Describe the bug

A simple select statement fails when one of the columns is an enum.

### To reproduce

1) Create a Postgres enum type. 2) Attempt to create a select query for it as shown in the screenshot.

### Expected behavior

No error, data should load

### Screenshots

<img width="1410" alt="Screencap2024 08 09 2119" src="https://github.com/user-attachments/assets/d6593295-c1c3-47cc-94fa-c3056a7303a4">

![Screencap2024 08 09 2120](https://github.com/user-attachments/assets/127d873b-fdb2-481c-8331-506208e5f813)
![Screencap2024 08 09 2121](https://github.com/user-attachments/assets/d48ee2b8-a00b-4408-94a0-8859e6c95e4c)

### Application version

Windmill EE v1.377.1-9-g479f2fc0c

**Comment by rubenfiszel** [comment]
Sorry for late answer but Windmill cannot decode enums as arbitrary json value. What should be done is casting it to text in your query.

**Comment by m-thomson** [comment]
Hi,

Thanks for the reply.

I'm not sure I understand. Windmill shouldn't need to decode anything. A Postgres enum value is literally just a text string when returned from a Postgres SELECT query.

(From a client perspective, an enum column is just a text column that only allows certain values to be *written*. It is otherwise identical to a text column in reading, joining, etc)

https://www.postgresql.org/docs/current/datatype-enum.html
