### ISSUE TITLE
feature: Configurable Snowflake timeout

### ISSUE THREAD

**Issue by kosborn** [windmill-labs/windmill#4232]
The Snowflake client is hardcoded to timeout after 10 seconds. Despite the Warehouse being configured to run longer on the Snowflake side, it appears the client overrides that.

https://github.com/windmill-labs/windmill/blob/1d0807f54238c8d8d242e3e5534c6d0868b3172b/backend/windmill-worker/src/snowflake_executor.rs#L301-L308

I think the simplest solution would be to allow that configuration in the Snowflake resource like the database values.

**Comment by rubenfiszel** [comment]
@HugoCasa can you take a look at this please
