### ISSUE TITLE
feature: dotnet runtime support

### ISSUE THREAD

**Issue by anchurcn** [windmill-labs/windmill#4254]
Is there any dotnet runtime support plan? And I am interested in support dotnet.

**Comment by sx98083714** [comment]
I'd love to know that, too

**Comment by rubenfiszel** [comment]
We will investigate adding support once we're done with Rust

**Comment by sx98083714** [comment]
very good! great job! great soft!

**Comment by markgraphene** [comment]
+1 for dotnet support

**Comment by wendrul** [comment]
Starting version v1.438.0 Windmill supports C#:
https://github.com/windmill-labs/windmill/releases/tag/v1.438.0

There haven't been requests so far for other lanugages in the dotnet family, so I'm closing this issue
