### ISSUE TITLE
bug: conditional tabs not updating if ctx or state changes

### ISSUE THREAD

**Issue by vzhemchuzhnikov** [windmill-labs/windmill#4276]
### Describe the bug

When I use navbar to change query params (go to current app and set query param to `?param_name=param_value`) and set conditional tabs component condition to `ctx.query,param_name == "some_value"` with `watch ctx.query` enabled, they are being selected correctly when in preview mode, but in production mode only default tab is shown. If you refresh the page, correct tab is selected.

App to reproduce: 
[conditional_tabs_bug.json](https://github.com/user-attachments/files/16709238/conditional_tabs_bug.json)

### To reproduce

1. Go to Conditional Tabs Bug app
2. Click on Test button
3. See that condition 1 tab is selected (It says `You pressed "Test"`)
4. Deploy the app
5. Go to deployed app
6. Click on Test button
7. See that default tab is selected (It says `I think you didn't press "Test"`)
8. Refresh the page
9. See that condition 1 tab is selected (It says `You pressed "Test"`)

### Expected behavior

Point 7 should also display condition 1 tab.

### Browser information

Microsoft Edge Version 126.0.2592.102 (Official build) (64-bit)

### Application version

CE v1.379.3

**Comment by rubenfiszel** [comment]
fixed in https://github.com/windmill-labs/windmill/commit/7882d4ecdd1007e73a51d2a408cf2e6dc1f83213,

thanks for the report
