### ISSUE TITLE
bug: circular imports cause an infinite loop

### ISSUE THREAD

**Issue by invakid404** [windmill-labs/windmill#4284]
### Describe the bug

If you have scripts that import each other forming a circular import, trying to deploy them causes Windmill to enter an infinite loop, filling the job queue with dependency tasks.

I tested this specifically with Bun scripts, but I'd imagine this could be true for other languages as well.

### To reproduce

1. Create two scripts that import each other (I personally did this all at once with the Windmill CLI). For example:

```ts
// u/windmill/a.ts
import { world } from "./b.ts";

export const hello = () => {
  return world();
};

export async function main() {
  return hello();
}

// u/windmill/b.ts
import { hello } from "./a.ts";

export const world = () => {
  return "Hello, world!";
};

export async function main() {
  return hello();
}
```

2. Try clicking "Deploy" on either of them
3. Observe the job queue getting filled with dependency runs

### Expected behavior

Windmill should detect and report circular import errors like these and fail.

### Application version

EE v1.383.1

**Comment by rubenfiszel** [comment]
Thanks, we will take a look

**Comment by rubenfiszel** [comment]
Fixed in https://github.com/windmill-labs/windmill/commit/cdd7349f6769a0195f367a1ac27f802287a1f900
