### ISSUE TITLE
bug: can't deploy new scripts

### ISSUE THREAD

**Issue by Viral** [windmill-labs/windmill#4299]
### Describe the bug

create a new script, press deploy. get error:

Error while saving the script: Sql error: no column found for name: starred

### To reproduce

docker tag: main

1. Go to create new script
2. Click on deploy
3. See Error

### Expected behavior

a job gets deployed when pressing "deploy"

### Additional Context

fixed by rolling back to 1.380.0

**Comment by rubenfiszel** [comment]
Update to latest release, we had a few broken commit in between this release 1.386.0 and the last one
