### ISSUE TITLE
bug: improve file docker-compose 

### ISSUE THREAD

**Issue by csuXinda** [windmill-labs/windmill#43]
change db_data to ./db_data  or promt to make the directory

**Comment by rubenfiszel** [comment]
Could you elaborate a bit more ?

**Comment by csuXinda** [comment]
the file is 404 ooh,https://github.com/windmill-labs/windmill-server/blob/main/docker-compose.yml and I use the file on the master branch but it didn't work

**Comment by rubenfiszel** [comment]
The proper link is https://github.com/windmill-labs/windmill-server/blob/main/docker-compose.yml . I fixed it on the README. Thanks for the pointer

**Comment by gaby** [comment]
@csuXinda The docker-compose is pointing to a Docker Volume, not a file on the current folder. That's why it doesn't have "./"

If you want a local folder you can do so by using: 

```
    volumes:
      - /path/on/host/:/var/lib/postgresql/data
```
