### ISSUE TITLE
bug:AgTable pagination does not display in safari

### ISSUE THREAD

**Issue by intelyfabs** [windmill-labs/windmill#4338]
### Describe the bug

The AgTable pagination is not appearing in Safari on Mac M1 Pro

### To reproduce

1. Create an app with an AgTable
2. Enable pagination
3. Dynamically load rows from file input
4. Note lack of pagination

### Expected behavior

I expect the pagination controls to appear at the bottom of the table

### Screenshots

In Safari:
![image](https://github.com/user-attachments/assets/03c86b40-373c-45f4-929b-9a94f4be226d)

In Chrome:
![image](https://github.com/user-attachments/assets/d4af77be-7642-48f4-b93e-1def223721f1)

### Browser information

Safari Version 17.2.1 (19617.1.17.11.12)

### Application version

Windmill EE v1.387.0-1-g5c82f815a

**Comment by rubenfiszel** [comment]
Apologies for the delay on this, we will tackle this asap
