### ISSUE TITLE
bug: Git Sync has inconsistent requirement

### ISSUE THREAD

**Issue by svzi** [windmill-labs/windmill#4355]
### Describe the bug

Hi there!

First of all thanks for delivering such an amazing product!

I'm self-hosting Windmill since a few days. I'm currently trying to reproduce all my automations I build with n8n. So far I really like the experience. During my learning I've stumbled upon a very cool feature, called "Git Sync". According to the documentation (e.g. see here https://www.windmill.dev/docs/advanced/version_control#git-sync and here https://www.windmill.dev/docs/advanced/git_sync) it should be available for self-hosted instances. I did my very best to follow the video and everything is connected as it should, but my connection isn't saved. As soon as I leave the page and enter it again, the connection seems to be lost.

In addition (and probably most importantly)  my UI says that "Syncing workspace to Git is an EE feature":

<img width="827" alt="image" src="https://github.com/user-attachments/assets/99d3d557-d9cc-49b2-8eb8-190c1f4339db">

So I guess the documentation is outdated? Or did I configure something wrong, that it doesn't work for me? Any help would be really much appreciated.

Best,
Sven

### To reproduce

see above

### Expected behavior

Either the documentation should be update to reflect that it's an EE only feature or the UI in the CE should be updated accordingly.

### Browser information

Brave Version 1.69.160

### Application version

CE v1.393.1-2-g1e813b261

**Comment by rubenfiszel** [comment]
It's available for self-hosted instances but only on EE, we will make it clearer on the docs. Thanks for the feedback

**Comment by svzi** [comment]
Thank you very much for the ultra fast response! Now I can focus on other tasks. :-)

**Comment by jontstaz** [comment]
@rubenfiszel - I distinctly remember using Git sync on my instance sometime last year or the year prior and Ive never had the EE. Had this feature been paywalled since that time? Because now it seems I cannot use it at all...

**Comment by rubenfiszel** [comment]
Nothing changed. Git sync was always EE and the CLI has always been open source. So you can still use the CLI to sync pull/push but it being triggered by windmill is EE like it always has been
