### ISSUE TITLE
bug: When upgrading Windmill, PostgreSQL is returning error that it cannot create a temporary directory. 

### ISSUE THREAD

**Issue by avo-sepp** [windmill-labs/windmill#4363]
### Describe the bug

Upgrading from Helm chart 2.0.67 to 2.0.267 (and some other previous versions had this issue) the Windmill App pods fail to start. Returning an `Error: Migrating Database`. This is using Azure PostgreSQL as the backing database, which is configured to create temporary tablespaces. 

```Error: Migrating database: while executing migration 20240223231005: error returned from database: cannot create temporary directory "pg_tblspc/16386/PG_15_202209061/pgsql_tmp": No such file or directory

Caused by:
    0: while executing migration 20240223231005: error returned from database: cannot create temporary directory "pg_tblspc/16386/PG_15_202209061/pgsql_tmp": No such file or directory
    1: error returned from database: cannot create temporary directory "pg_tblspc/16386/PG_15_202209061/pgsql_tmp": No such file or directory
    2: cannot create temporary directory "pg_tblspc/16386/PG_15_202209061/pgsql_tmp": No such file or directory```
    
This error is preventing upgrade. 


### To reproduce

Upgrade from 2.0.67 -> some newer version. 
Using Azure PostgreSQL Flexible Server

### Expected behavior

Windmill should update successfully. 

### Screenshots

_No response_

### Browser information

_No response_

### Application version

_No response_

### Additional Context

_No response_

**Comment by avo-sepp** [comment]
`azure.enable_temp_tablespaces_on_local_ssd = off` is configured for the database. I am double checking this.

**Comment by rubenfiszel** [comment]
@avo-sepp you should be able to reproduce this running:
https://github.com/windmill-labs/windmill/blob/main/backend/migrations/20240223231005_add_index_completed_job.up.sql#L2-L3 on your database.

It won't break your capability to still upgrade windmill due to the existence of `if not exists`

**Comment by avo-sepp** [comment]
This is resolved! Sorry! Our fault, or maybe Azures. That toggle was "off" but must have not actually performed the configuration. Turning it On and Off again fixed the database. 

Thank you!!
