### ISSUE TITLE
bug: worker selected for flow is changed if nested flow is run when same_worker is true

### ISSUE THREAD

**Issue by vzhemchuzhnikov** [windmill-labs/windmill#4367]
### Describe the bug

When shared folder is enabled, flow is run on the same worker, and I expect all steps to be scheduled to the same worker.
I also expect steps to be scheduled to non-native workers if there are at least one step that uses non-native worker (e.g. a bash script).
It is working like this; however, it breaks if I add a nested flow that only consists of native scripts.
Every step that is run after the nested flow is scheduled to native worker, which can break flows.
For example, I install additional binaries to my default workers and use them in my bash scripts.
These scripts breaks if it is run on native worker, due to missing binary.

### To reproduce

1. Start both default and native workers.
2. Run attached flow.
3. See that the last step (bash script) is run on a native worker.
4. Remove nested flow from the flow.
5. Run again.
6. See that the last step (bash script) is run on a non-native worker.

### Expected behavior

p.3 should be run on non-native worker

### Application version

CE v1.383.1

### Additional Context

[wrong_worker_flow.json](https://github.com/user-attachments/files/16957471/wrong_worker_flow.json)
[nested_flow.json](https://github.com/user-attachments/files/16957472/nested_flow.json)

**Comment by rubenfiszel** [comment]
There was a bug but not the one you have in mind. The nested flows should have been executed fully on the same worker as the parent flow. It's now fixed on latest. 

Native and non-native workers are just workers pre-configured to listen to specific tags (the language specific ones). Same workers override that behavior and execute everything on the workers that listen to the 'flow' tag irrespective of the flow content. It would be inconsistent to make a difference for nested flows. If you use same worker to share data in a shared folders, it should be possible to share that data between the parent and the nested flow.
