### ISSUE TITLE
bug: `wmill sync pull` does not pull Rust scripts

### ISSUE THREAD

**Issue by invakid404** [windmill-labs/windmill#4370]
### Describe the bug

When using `wmill sync pull`, the metadata and lockfile for Rust scripts is pulled, but not the source itself.

### To reproduce

1. Create a Rust script
2. Run `wmill sync pull`
3. Observe the issue

### Expected behavior

`wmill sync pull` should pull Rust scripts

### Application version

wmill 1.394.1

**Comment by rubenfiszel** [comment]
cc @wendrul

**Comment by wendrul** [comment]
Thanks for the report! We will be fixing this soon

**Comment by invakid404** [comment]
@wendrul on my end, this doesn't appear to be fixed:

![](https://img.qilin-qilin.ts.net/raw/2024-09-24_10-27-40_zwQJS.webp)

I am using the latest Windmill CLI and it still only pulls the `.script.yaml` and `.script.lock` files, not the script itself. My instance is also latest:

![](https://img.qilin-qilin.ts.net/raw/2024-09-24_10-29-27_YoVcY.webp)

What am I missing?

**Comment by wendrul** [comment]
The issue should be resolved now (1.400).
