### ISSUE TITLE
bug: JSONSchema input validation not working for numbers

### ISSUE THREAD

**Issue by rsmith-onespark** [windmill-labs/windmill#4378]
### Describe the bug

JSON Schema validation is not being applied for numbers.

### To reproduce

1. Create a script or flow with a number input
2. Set the min to 10
3. Try submit with a value less than 10

Or 
2. Set the min to 10 and max to 20. 
3. Try submit with a value greater than 20

### Expected behavior

The input validation from JSON Schema should be enforced

### Screenshots

Function
```deno
export async function main(
  a: number,
) {
  return { foo: a };
}
```

![image](https://github.com/user-attachments/assets/6a7c428e-7a93-48fd-9077-9a949b4a98fa)
JSON Schema
![Uploading image.png…]()

With min and max validation on
![Uploading image.png…]()

### Browser information

Brave, Version 1.69.168 Chromium: 128.0.6613.138 (Official Build) (64-bit)

### Application version

windmill community edition, self-hosted, v1.390.1

**Comment by rubenfiszel** [comment]
It's enforced on the form input, but not by the server/backend. Was the html number input not have the proper min and max?

**Comment by rsmith-onespark** [comment]
Thanks for responding so quickly!
This is what the schema looks like in JSON 
![image](https://github.com/user-attachments/assets/80beab53-86fb-427b-b3b0-88caf08d790c)


I tried submitting from the form and it still didn't enforce it
![image](https://github.com/user-attachments/assets/370c5c59-6177-46da-8faf-2d2aa4b3c251)
![image](https://github.com/user-attachments/assets/1277a991-0aee-4501-8ee4-8d1675fd956d)

**Comment by rsmith-onespark** [comment]
Here is an example with a min and max
![image](https://github.com/user-attachments/assets/316d1072-0089-4772-9ea2-77fd72428036)

Still doesn't enforce validation:
![image](https://github.com/user-attachments/assets/316d1072-0089-4772-9ea2-77fd72428036)

**Comment by rubenfiszel** [comment]
:+1: , I think what you're seeing is the default behavior of min/max on the html input element. We will add one layer to make it undefined/invalid if not in the boundary. Thanks for the report

**Comment by rsmith-onespark** [comment]
I thought the JSON schema would automatically validate inputs before it even hits the script/flow.. That would be very powerful, and prevent many data errors.

**Comment by rubenfiszel** [comment]
We plan to add this option as an opt-in toggle but there are many drawbacks to it as well (slight performance hit and rigidity). But mostly a todo

**Comment by rubenfiszel** [comment]
fixed on latest:
![image](https://github.com/user-attachments/assets/24098250-81a8-4a6b-8afe-25b145119d3e)
