### ISSUE TITLE
bug: show this field only when conditions are met is causing crashes when conditions change

### ISSUE THREAD

**Issue by jhygate** [windmill-labs/windmill#4380]
### Describe the bug

Showing and hiding certain flow input fields is either jankily slow or straight up crashes in my browser.

Using a boolean switch to hide other fields crashes.

### To reproduce

1. Create a new flow
2. add a boolean switch
3. create a new  object field
4. DO NOT use a custom object type and populate the default with pure json e.g
`{
  "test2": 1,
  "test1": ""
}`
5. Set 'show this field only when conditions are met' - to the boolean
6. try and switch the bool in different situations and feel the pain

### Expected behavior

Not to crash - or the fields to show/hide  (semi)-instantly

### Browser information

Version 128.0.6613.120 (Official Build) (arm64)

### Application version

Windmill CE v1.394.1

**Comment by rubenfiszel** [comment]
Does it happen with a trivial 2 field form:
```
{
	"$schema": "https://json-schema.org/draft/2020-12/schema",
	"properties": {
		"foo": {
			"default": false,
			"nullable": false,
			"required": [],
			"type": "boolean",
			"description": "",
			"order": [],
			"properties": {}
		},
		"bar": {
			"type": "string",
			"description": "",
			"default": "",
			"properties": {},
			"required": [],
			"showExpr": "fields.foo",
			"password": false,
			"nullable": false,
			"order": [],
			"disableVariablePicker": false,
			"disableCreate": false
		}
	},
	"required": [],
	"type": "object",
	"order": [
		"foo",
		"bar"
	]
}
```
?
If not, can you share the schema and your browser please

**Comment by rubenfiszel** [comment]
We removed an obsolete animation on latest, try updating in 30mins when our build is released

**Comment by jhygate** [comment]
Working now, thanks for the help!
