### ISSUE TITLE
How to upgrade? 

### ISSUE THREAD

**Issue by francescor** [windmill-labs/windmill#4451]
### Describe the bug

We need to upgrade from (docker swarm mode) version:

```
image: ghcr.io/windmill-labs/windmill:1.107
```
to 

```
image: ghcr.io/windmill-labs/windmill:latest
```

but latest code needs the windmill_migration table starting with this https://github.com/windmill-labs/windmill/blob/main/backend/migrations/20240204212055_auto_bypassrls.up.sql

so the direct upgrade 107 => latest  fails

```
ERROR windmill-api/src/db.rs:168: Could not apply job completed index fix migration: Sql error: error returned from database: relation "windmill_migrations" does not exist
```

What is the correct approach for upgrading? do we 

108, 109, 110, ..... till 402 ? :( 

### To reproduce

direct upgrade 107 => latest

### Expected behavior

no issues

### Additional Context

Context is Docker Swarm, with Ubuntu 22.04 nodes

**Comment by francescor** [comment]
I was able to migrate with these steps

```
1.107 
1.260.1
1.261.0
1.262.0
1.263.0
1.264.0 (and here I have the windmill_migrations table)
1.401.0
```

But I have the feeling I am not doing what I am supposed to have a correct upgrade

**Comment by rubenfiszel** [comment]
Hi @francescor , yes those migrations are quite old. Honnestly my recommendations would be to use `wmill sync pull` to back your workspace, nuke your db, recreate it and have windmill do all the migrations automatically and rehydrate it with `wmill sync push`
