### ISSUE TITLE
bug: `wmill script generate-metadata` times out on long tasks

### ISSUE THREAD

**Issue by invakid404** [windmill-labs/windmill#4452]
### Describe the bug

When using `wmill script generate-metadata` on, e.g., Rust scripts with plenty of dependencies, the dependency job scheduled to generate the lock file gets canceled due to `fetch` timing out in the CLI.

The timeout for `fetch` seems to be 5 minutes by default, so any dependency job that takes longer than that will be canceled early, resulting in an error.

### To reproduce

Run `wmill script generate-metadata` on some script that takes more than 5 minutes to build.

### Expected behavior

The timeout should be increased, or the lock file generation logic should become asynchronous, where the CLI polls until the job completes.

### Screenshots

![image](https://github.com/user-attachments/assets/5baf2b00-dbe5-4535-a1ab-2d8b54cf684e)
![image](https://github.com/user-attachments/assets/c0e48ced-2dff-4844-b748-b47944561a66)

### Browser information

N/A

### Application version

Windmill v1.401.0

**Comment by wendrul** [comment]
Thanks for the report, I'll take a look. We can maybe skip the building all together and have just the lockifile generation when using the cli.
