### ISSUE TITLE
feature: Allow Custom HTTP routes and preprocessors to handle binary uploads

### ISSUE THREAD

**Issue by gcleaves** [windmill-labs/windmill#4471]
I have a flow which processes a file and returns some data about the file. At the moment the flow takes base64 input. But I'd like to see if I can decrease the upload size by allowing a binary upload instead of having to use base64 text. The goal is also to improve the endpoint consumer's experience so they can use a tool like Postman or Curl without first needing to convert the file to base64.

Maybe the acceptable content-type could be set in the Custom HTTP route and it passes the raw body to the preprocessor.

Copied from discussion https://github.com/windmill-labs/windmill/discussions/4470

**Comment by gcleaves** [comment]
Olé!

**Comment by HugoCasa** [comment]
@gcleaves we now support multipart/form-data directly
the files will be uploaded to s3 and you will get the path

**Comment by gcleaves** [comment]
Glad to see my use case makes sense. Thanks!
