### ISSUE TITLE
bug: Edit ID button does not work in apps

### ISSUE THREAD

**Issue by vzhemchuzhnikov** [windmill-labs/windmill#4472]
### Describe the bug

When I try to edit an id of a component, pressing the Edit ID button (pencil icon) does nothing.

### To reproduce

1. Create an empty app
2. Add any component
3. Try to change its id

### Expected behavior

You are able to edit and save the ID

### Browser information

Edge Version 128.0.2739.42 (Official build) (64-bit), Firefox 130.0.1 (64-bit)

### Application version

CE v1.402.3

**Comment by rubenfiszel** [comment]
fixed on latest

**Comment by vzhemchuzhnikov** [comment]
@rubenfiszel Popup is showing but it does not save the result.

**Comment by vzhemchuzhnikov** [comment]
Created #4483
