### ISSUE TITLE
bug:[python] dependencies from relative imports are not resolved automatically

### ISSUE THREAD

**Issue by smuun** [windmill-labs/windmill#4476]
### Describe the bug

Dependencies from relative imports are not resolved automatically

### To reproduce

In the web editor:
1. Create two scripts in different folders - script 1 should have  some external import statements 
2. Import script 1 into script 2 as `from f.folder1 import script_1`
3. Run script 2 -> runtime error when the function from script 1 tries to call the external dependency

### Expected behavior

Script 1's dependencies should be resolved automatically when running script 2.

This can be fixed by copy-pasting all the import statements from script 1 into script 2.

**Comment by rubenfiszel** [comment]
Try `from f.folder1.script_1 import main` instead (or replace main with any other function within
