### ISSUE TITLE
bug: Issues when creating a schedule with a long name

### ISSUE THREAD

**Issue by jaller94** [windmill-labs/windmill#449]
## Describe the bug

HTTP 500 and mysterious error in the webapp when creating a schedule with a long name.

`Internal: Could not insert into queue 0182b0f2-b7cd-1448-c7b3-8f4f1dd1a991: error returned from database: value too long for type character varying(50)`

## To Reproduce

1. Go to https://app.windmill.dev/schedule/add
2. Create a name that's longer than 50 characters including `/u/your_username/`
3. Click on "Schedule"

## Expected behavior
* The length isn't restricted at 50 but at 200 or some other length which I'm unlikely to hit.
* The form knows about the limit and does client-side validation.
* The server returns a nice HTTP 400 with the info that the `path` (UI needs to translate this to the name field) is too long.
  * URL: `POST https://app.windmill.dev/api/w/j94_test/schedules/create`

## Screenshots
![Screenshot_2022-08-18_14-38-54](https://user-images.githubusercontent.com/10872136/185397833-30c20a20-9c81-44de-ba31-eea66424d24c.png)

## Windmill version
v1.31.0-19-g918f6db
## Additional context

**Comment by rubenfiszel** [comment]
Fixed in https://github.com/windmill-labs/windmill/commit/ae44a1ecc1e977e1fc2ea11e20f6152f02724df2

**Comment by jaller94** [comment]
The fix only increases the limit but does not
* prevent the HTTP 500,
* prevent the webapp from displaying a database error. Instead show "name too long".

**Comment by rubenfiszel** [comment]
@fatonramadani small FR for you, match the char limits in the DB with our input validation, starting with schedule name. The actual limit is 255 - 2 - username.length. For simplicity we can limit those to 200 max since usernames cannot be longer than 50 chars

**Comment by jaller94** [comment]
The limit of 50 has not yet been increased on the instance https://app.windmill.dev running windmill version (backend) v1.35.0-2-ge8aec1c.

```
Sql error: error returned from database: value too long for type character varying(50)
```

**Comment by rubenfiszel** [comment]
Fixed in latest commit and deployed
