### ISSUE TITLE
My first python script was wrong in saving ：Error while saving the script as a draft: structuredClone is not defined

### ISSUE THREAD

**Issue by sx98083714** [windmill-labs/windmill#4524]
After installing windmill, I tried to use python to complete the first script. I chose python as the language and kept the default for all the others. Then I clicked Draft, and an error message appeared:

> Error while saving the script as a draft: structuredClone is not defined

I had to close the window, re-click the edit button at the end of the script from the script list page, and it said again: 

> structuredClone is not defined

and the page didn't display anything.

Can you tell me why this is and what I did wrong?

Waiting for your answer, thank you for your kindness!

**Comment by rubenfiszel** [comment]
What browser and version are you using that is not supporting structuredClone ?

**Comment by sx98083714** [comment]
Thank you very much for your reply!

haha, I really did not expect, it is really the browser problem, I switched to chrome, now the problem is solved! Thank you very much, wish you a happy life!
