### ISSUE TITLE
How do I prevent windmill from automatically updating to the latest version at startup?

### ISSUE THREAD

**Issue by sx98083714** [windmill-labs/windmill#4525]
After each `docker compose up ` execution, windmill will automatically upgrade the system to the latest version, I don't want it to do this, I only want to manually upgrade when I need to, how do I edit the Docker-compose.yml file?

Look forward to your answer, thank you, warm heart, wish you good luck!

**Comment by alpetric** [comment]
in the `.env` file you can replace:

`WM_IMAGE=ghcr.io/windmill-labs/windmill:main`

with a specific tag you can find [here](https://github.com/windmill-labs/windmill/pkgs/container/windmill)

e.g
`WM_IMAGE=ghcr.io/windmill-labs/windmill:1.407`

**Comment by sx98083714** [comment]
Thank you! Warm heart! I thought it should be modified here, but I did not find the corresponding instructions, I am not quite sure, in short, thank you very much!
