### ISSUE TITLE
bug: s3 upload component does not persist uploaded files after changing tabs

### ISSUE THREAD

**Issue by smuun** [windmill-labs/windmill#4537]
### Describe the bug

Upload component shows empty after changing tabs using the windmill tab component.

### To reproduce

In a new app:
1. create tabs
2. in tab 1, create s3 upload
3. upload a file; upload succeeds and file shows up in component
4. switch to tab 2
5. switch back to tab 1; file is gone from UI

### Expected behavior

File should stay in the component UI, allow users to clear files with the delete button, etc.  Accessing component.result even after the tab change returns the uploaded files correctly.

### Application version

EE v1.407.2-3-g0915968eb

**Comment by rubenfiszel** [comment]
fixed on very latest, still building
