### ISSUE TITLE
bug: job error when using turn schedule on/off api

### ISSUE THREAD

**Issue by vanhtuan0409** [windmill-labs/windmill#454]
**Describe the bug**

Using [Turn on/off schedule](https://hub.windmill.dev/scripts/windmill/1326/turn-on%2Foff-a-schedule-windmill) from windmill hub return error as 

```
Internal: fetching flow status 0182b659-12a1-26c3-90a0-b6f3d9d1cf2c while reporting true Object({}): no rows returned by a query that expected to return at least one row
```

It is worth noting that the schedule is indeed turned off, only the script run reported an error

**To Reproduce** Steps to reproduce the behavior:

1. Setup a Flow using [Turn on/off a schedule](https://hub.windmill.dev/scripts/windmill/1326/turn-on%2Foff-a-schedule-windmill). Pass in `schedule_path: Deno.env.get("WM_SCHEDULE_PATH")` and `enabled: false` 
2. Enable the schedule for the above Flow
3. Run the schedule

**Expected behavior**

The Flow successfully runs and reports no error. The Schedule is turned off.

**Windmill version** 

 v1.31.0-43-g77a6851

**Additional context** 

As for my troubleshooting: `set_enabled` will in turn invoke `clear_schedule` to delete the record from the `queue` table
Later when the script is run, `update_flow_status_after_job_completion` will be invoked and will query the last flow status, which is already deleted in `set_enbaled`

My suggestion here is that we can mark the record as canceled or skipped in `clear_schedule` instead delete it from the table. Later in `jobs.pull`, we can filter out those canceled/skipped records, or perform a double check on whether the schedule is turned off or not
A double check would be preferred because, just in case we want to switch to another msg queue in the future, not all msg queues will support the delete operation. But the canceled/skipped mark would be quicker to implement

https://github.com/windmill-labs/windmill/blob/main/backend/src/schedule.rs#L402
https://github.com/windmill-labs/windmill/blob/main/backend/src/schedule.rs#L221
https://github.com/windmill-labs/windmill/blob/main/backend/src/worker_flow.rs#L86
https://github.com/windmill-labs/windmill/blob/main/backend/src/jobs.rs#L1395

**Comment by rubenfiszel** [comment]
Thank you very much for the investigation, I will come up with a fix. There is another issue currently plaguing flows  execution in some rare cases which also give the same error.

**Comment by rubenfiszel** [comment]
@vanhtuan0409 I think: 0cd814c should fix it and be the appropriate behavior.

**Comment by rubenfiszel** [comment]
The relevant changes being: https://github.com/windmill-labs/windmill/commit/0cd814cfec3ab088f7646b6b9f6970e48961e710#diff-7cba380cbf5fe25865c4e23ea2fca04c37fa7c34637341e56ef7769387808856R222

**Comment by vanhtuan0409** [comment]
things work flawlessly now :D thank you a lot
