### ISSUE TITLE
bug: Flow Editor Step Input dropdown elements unselectable

### ISSUE THREAD

**Issue by lukeod** [windmill-labs/windmill#4682]
### Describe the bug

In the flow editor (/flows/edit/<flow_path>) if a flow step is selected that has multiple inputs that includes a dropdown item, the options cannot be selected if there's an input item below it in the form. See attached video for example.

https://github.com/user-attachments/assets/f44839b4-2781-4c39-87f7-4333b5b1df6d

### To reproduce

1. Create a python script with the following code:

`import wmill
import requests
from typing import Literal

def main(some_string:str, some_literal:Literal["literal_one", "literal_two", "literal_three"], some_other_string:str):
    return input_one
`
2. Add the script as a step in the Flow editor
3. Attempt to select one of the drop down items for the "some_literal" variable. It will be blocked by the variable below it (some_other_string) being rendered over the top of the drop down elements

Behavior exists for both chrome and firefox latest versions as of the time of writing, on Win10 (Chrome 130.0.6723.117, Firefox 132.0.1)

### Expected behavior

I would expect the drop down elements to render over the top of any input variables below it, allowing them to be selected

### Screenshots

![image](https://github.com/user-attachments/assets/1d00cf3a-12d4-45be-9e67-de809f111edc)

### Browser information

Chrome 130.0.6723.117, Firefox 132.0.1

### Application version

CE v1.421.2-7-g02170032a

**Comment by rubenfiszel** [comment]
fixed in latest, thanks for the report
