### ISSUE TITLE
bug: Pattern validation on strings unintentionally enforces the field to be mandatory on an app

### ISSUE THREAD

**Issue by rsmith-onespark** [windmill-labs/windmill#4768]
### Describe the bug

When building an app from a flow, using the same inputs, an optional string input with pattern validation weirdly becomes a mandatory input on the app UI.

### To reproduce

1. Create a flow with this input structure
```json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "properties": {
        "name": {
            "type": "string",
            "description": "",
            "default": "",
            "nullable": false,
            "disableVariablePicker": true
        },
        "email": {
            "type": "string",
            "description": "",
            "pattern": "^[\\w-+.]+@([\\w-]+\\.)+[\\w-]{2,4}$",
            "default": null,
            "nullable": true,
            "disableVariablePicker": true
        }
    },
    "required": [
        "name"
    ],
    "type": "object",
    "order": [
        "name",
        "email"
    ]
}
```

2. Deploy flow
3. Click "Build App"
4. Leave defaults and Deploy App
5. Try submit the form without an email

### Expected behavior

I expect to be able to submit the form with an optional input being null.

### Screenshots

Flow with an optional email set to null (works as expected)
![image](https://github.com/user-attachments/assets/0856542b-7012-4a37-a887-b82ccb7dd701)

Flow with an optional email set to invalid email (works as expected)
![image](https://github.com/user-attachments/assets/d58051a5-be94-49b4-9803-cc6e9099716e)

App with optional email not filled in (**doesn't work** - the submit button is disabled because the email is not filled in)
![image](https://github.com/user-attachments/assets/7ab97412-f84c-41d1-91c6-5d7af023e358)
![image](https://github.com/user-attachments/assets/ae8c38a0-66ea-4402-9b4e-3057967e2d01)

### Browser information

Brave: Version 1.73.89 Chromium: 131.0.6778.69 (Official Build) (64-bit)

### Application version

windmill version v1.411.1

**Comment by rubenfiszel** [comment]
fixed in very latest
