### ISSUE TITLE
bug: formatter popup/error in deno scripts

### ISSUE THREAD

**Issue by tennox** [windmill-labs/windmill#4798]
### Describe the bug

When I Ctrl-S inside a deno script, I get this popup:

![image](https://github.com/user-attachments/assets/2761071c-daf6-46bd-a493-ad265111d349)

### To reproduce

1. Create new deno script
2. Press `Ctrl-S` inside editor

### Browser information

Firefox 132.0 (64-bit) - linux

### Application version

CE v1.430.2

**Comment by rubenfiszel** [comment]
should be fixed on very latest
