### ISSUE TITLE
bug: permission inconsistencies between executions from the flow UI and App UI

### ISSUE THREAD

**Issue by rsmith-onespark** [windmill-labs/windmill#4827]
### Describe the bug

A flow being executed from the flow UI uses the permissions of the user executing the script (correct).
The same flow, wrapped in an App and executed in the App UI by the same user, uses the permissions of the flow owner when the flow is executed from the App UI.

More details in the screenshots section...

### To reproduce

1. Create folders `test_folder_1`, `test_folder_2`
2. Create a user `test@test123.com` and give them operator access to `test_folder_1`
3. Create a script in `test_folder_2`
3. Create a secret in `test_folder_2`
4. Create a flow in `test_folder_1` that uses the script above and has a Bun node that fetches a secret from `test_folder_2`
6. Execute flow in UI (as test user)
7. Create and build app from the flow UI
8. Execute the flow from the App UI (as test user)

### Expected behavior

Consistent permissions across flow/app executions. The permissions should always relate to the user executing the flow/script/app.
Clearer documentation on flows/apps that reference flows/apps in other folders and how that should be handled.

### Screenshots

Assume there is a `test` user who has access to a folder `test_folder_1`. `test` should be able to execute a flow inside `f/test_folder_1`. But, what if that flow contains scripts from `folder_2` that `test` does not have access to? Currently, `test` would be able to execute this flow in `test_folder_1` and I think that is correct.
As seen below, the script in `test_folder_2` is executable from the flow `test_folder_1` even though the user doesn't have permissions to that folder. On the right pane, the node definition is unavailable due to access restrictions, but is still executable.
![image](https://github.com/user-attachments/assets/e65687c1-42c1-47f0-a4e1-0c1b917e8b44)

Here is a second flow in `test_folder_1` being executed from the flow UI. `whoami` returns the executing user (correct), allows the user to execute flows from `test_folder_2`, but doesn't allow the user to fetch secrets from `test_folder_2` (weird inconsistency).
![image](https://github.com/user-attachments/assets/9cec3e36-1eff-4d48-bd32-1e6e9aa5298f)

`whoami` output
![image](https://github.com/user-attachments/assets/922e219a-72f6-41bd-b52d-7ac26f371481)

fetching secret from `test_folder_2` failure:
![image](https://github.com/user-attachments/assets/fda6ceb1-6a92-4ed3-ab19-0b47c9c9fdd0)

Now, the output below is from executing the exact same flow above in the App UI (same test user).
`whoami` output - user returned is the creator, not the executor (wrong)
![image](https://github.com/user-attachments/assets/5f83f625-caed-47bf-bf46-14c1dedd4873)

fetching secret from `test_folder_2` now works (the creator has access to that folder but the executor doesn't)
![image](https://github.com/user-attachments/assets/a5c02eb3-26aa-421f-b725-fcae44f2f7fc)

### Browser information

Brave Version 1.73.91 Chromium: 131.0.6778.85 (Official Build) (64-bit)

### Application version

Running windmill version v1.411.1

**Comment by rubenfiszel** [comment]
No it's intended behavior. For scripts and flows, you give access directly to them. For apps, it would be way too complex to have to both give access to the apps AND all the underlying scripts and flows they rely on. When you give access to an app, you give access to everything that app use and to do so, we use the mechanism of "on behalf of" where everything executing within an app is executed on behalf of the publisher. To ensure security, at deployment time we compute a complex policy that makes sure that the only thing that can be called from the apps are the scripts/flows (workspace and inline)  used in the app and the only degree of freedoms are the non static fields.
