### ISSUE TITLE
Self-Hosted from Container Issue

### ISSUE THREAD

**Issue by EnsoKeegan** [windmill-labs/windmill#484]
I'm receiving this error upon trying to run Python scripts in Windmill, hosted in a container. Any direction for resolving the error would be super helpful!

`
Error during execution of the script
last 5 logs lines:
[E][2022-08-24T11:14:16+0000][32] int nsjail::standaloneMode(nsjconf_t*)():272 Couldn't launch the child process
`

System Info:
  Model Name:	MacBook Pro
  Model Identifier:	Mac14,7
  Chip:	Apple M2

**Comment by rubenfiszel** [comment]
@EnsoKeegan I don't know if you still have this issue but have you tried disabling nsjail:
DISABLE_NSJAIL=true as env variable.

Nsjail does not seem to be supported on Apple M2. Nsjail is solely used for sandboxing so it's not very useful if on your own laptop.

**Comment by EnsoKeegan** [comment]
Resolved :) Thank you! The M2 chip issue was the culprit with the suggested fix doing the job.
