### ISSUE TITLE
bug: Playwright script deployment fails with Bun runtime - chromium-bidi resolution error

### ISSUE THREAD

**Issue by goosetapa** [windmill-labs/windmill#4872]
### Describe the bug

When deploying a Playwright script using Bun TypeScript runtime, the deployment fails due to unresolved dependencies related to chromium-bidi modules.

### To reproduce

1. Create a TypeScript script using Playwright
2. Configure the script to run with Bun runtime (worker group tag: chromium)
3. Deploy and execute the script
4. Observe the deployment error

### Expected behavior

1. All dependencies including chromium-bidi modules should resolve correctly
2. The Playwright browser automation should initialize and run without dependency-related errors
3. The script should complete its intended automation tasks successfully

### Screenshots

![image](https://github.com/user-attachments/assets/685cf076-4a9f-4d9b-81c1-2ef6a0d7c445)

### Application version

Windmill CE v1.435.2

### Additional Context

Error deploying this script
This script has not been deployed successfully because of the following errors:

```
job=0193a99d-0e44-5b4d-4651-24633f53c932 tag=chromium worker=wk-reports-94k8d-sgPVX hostname=windmill-workers-reports-8445df6466-94k8d

bun install v1.1.34 (5e5e7c60)
Saved lockfile
+ playwright@1.49.0
+ windmill-client@1.435.2
3 packages installed [12.00ms]
7 | var bidiMapper = _interopRequireWildcard(require("chromium-bidi/lib/cjs/bidiMapper/BidiMapper"));
                                                     ^
error: Could not resolve: "chromium-bidi/lib/cjs/bidiMapper/BidiMapper". Maybe you need to "bun install"?
    at /tmp/windmill/wk-reports-94k8d-sgPVX/0193a99d-0e44-5b4d-4651-24633f53c932/node_modules/playwright-core/lib/server/bidi/bidiOverCdp.js:7:50
8 | var bidiCdpConnection = _interopRequireWildcard(require("chromium-bidi/lib/cjs/cdp/CdpConnection"));
                                                            ^
error: Could not resolve: "chromium-bidi/lib/cjs/cdp/CdpConnection". Maybe you need to "bun install"?
    at /tmp/windmill/wk-reports-94k8d-sgPVX/0193a99d-0e44-5b4d-4651-24633f53c932/node_modules/playwright-core/lib/server/bidi/bidiOverCdp.js:8:57
Non-zero exit status: 1
```

**Comment by rubenfiszel** [comment]
Try with //nobundling at the very top of the file

**Comment by goosetapa** [comment]
> Try with //nobundling at the very top of the file

I worked! Thanks!
