### ISSUE TITLE
bug: can not log in with microsoft sso

### ISSUE THREAD

**Issue by DZiso** [windmill-labs/windmill#4890]
### Describe the bug

When clicking "microsoft"  on the login page i get the following error message:

> Bad request: failed to exchange code: InternalErr("ErrorResponse { status: 401, error: ErrorResponse { error: InvalidClient, error_description: Some(\"AADSTS7000222: The provided client secret keys for app 'c3ace029-7524-4ece-b34b-41fe5f5f4b86' are expired. Visit the Azure portal to create new keys for your app: https://aka.ms/NewClientSecret, or consider using certificate credentials for added security: https://aka.ms/certCreds. Trace ID: 6819c4f6-a1cc-4d42-93c0-8fc804834e00 Correlation ID: dffa9ccb-ed1c-457d-90db-991422455c74 Timestamp: 2024-12-10 15:28:35Z\"), error_uri: Some(\"https://login.microsoftonline.com/error?code=7000222\") } }")

Whole org is affected, to my knowledge the azure sso configuration is fully on your side.

 

### To reproduce

1. Go to portal.office.com & login
2. Go to 'https://app.windmill.dev/user/login'
2. Click on 'Microsoft'
3. Redirect to Microsoft & Back
4. Error pops open on the side

### Expected behavior

To be loged in.

### Screenshots

<img width="299" alt="image" src="https://github.com/user-attachments/assets/2ec41d1a-f577-4b9d-a126-683b5d342234">

### Additional Context

Affected Account: David.Siegel@findiq.de(might still in your system as David.Zisowsky@findiq.de)

**Comment by rubenfiszel** [comment]
It's a cloud issue, we're on it

**Comment by rubenfiszel** [comment]
fixed

**Comment by DZiso** [comment]
works as expected :) thanks!
