### ISSUE TITLE
bug: db high cpu usage

### ISSUE THREAD

**Issue by i5shuyi** [windmill-labs/windmill#4911]
### Describe the bug

postgres container high cpu usage

### To reproduce

1.Self hosting windmill on windows 11
2. Wait several hours

### Expected behavior

Under low load, CPU usage should be very low.

### Screenshots

![0005a40ac38b2fdeb30c511f6ff7984a](https://github.com/user-attachments/assets/605f1dd3-3a16-4fcf-90de-6ad35e2fc14e)

### Browser information

Safari 18.2 (20620.1.16.11.8)

### Application version

CE v1.437.1-13-g0dab23f6b

**Comment by rubenfiszel** [comment]
you can modify SLEEP_QUEUE (default 50) to a number that suits your desires to reduce polling but no windmill is not designed to have low db load when load is small but to have stable db load regardless of workload since the db is meant to run on dedicated servers.
