### ISSUE TITLE
bug: Project do not have access to model 'gpt-4o-2024-08-06'

### ISSUE THREAD

**Issue by imlopes** [windmill-labs/windmill#4929]
### Describe the bug

I created a new project on https://platform.openai.com/settings and adding a new API key.
When setting on windmill, my key do not have access to a specific gpt model.

Checking my project, the model mentioned is no more available and all available models are allowed.

I checked the code and I didnt find how to change the model to use.

### To reproduce

1. Go to 'workspace settings'
2. Click on 'Windmill AI'
3. Set the openAI Api and click on test key

### Expected behavior

API key works

### Screenshots

![image](https://github.com/user-attachments/assets/f051e3ed-d3e6-4cb1-9628-bb413ee1d721)

![image](https://github.com/user-attachments/assets/25cd0a1f-cda9-4e02-8d0e-c6372df34f75)

### Application version

Windmill CE v1.439.0-1-gd39193063

**Comment by HugoCasa** [comment]
You account probably doesn't have access to this model. I've seen here https://github.com/Aider-AI/aider/issues/2031 that you need at least 5$ credit in your OpenAI account.
