### ISSUE TITLE
bug: Unable to restart flow job step within a loop

### ISSUE THREAD

**Issue by vica-admin** [windmill-labs/windmill#4956]
### Describe the bug

We're unable to use the "Restart a completed flow at a given step" API endpoint to restart a flow job step that is included within a loop (For & While loops).

If the loop went through as usual, you get "Internal: Flow cannot be restarted from step {id} as it could not be found."

If the loop was early stopped succesfully, you get "Internal: Flow cannot be restarted from a non successful module".

### To reproduce

1. Create a flow that includes a "For loop"
2. Run a job
3. Call the API endpoint "Restart a completed flow at a given step" by passing a step ID that is within the loop

### Expected behavior

The flow should restart at the specific step within the loop at the right iteration based on the branch_or_iteration_n variable.

### Screenshots

<img width="275" alt="image" src="https://github.com/user-attachments/assets/dadf45f9-23f3-432a-9959-8bfa342b33fc" />
<img width="359" alt="image" src="https://github.com/user-attachments/assets/2aa92d92-2c49-4dff-bc5a-41839cb58959" />
<img width="265" alt="image" src="https://github.com/user-attachments/assets/142ed243-65b2-472e-8d5c-b0e53bfba7de" />
<img width="365" alt="image" src="https://github.com/user-attachments/assets/758ae7f5-e69f-4302-b6ff-4dfd29271321" />

### Browser information

Chrome 131.0.6778.140 (Official Build) (64-bit)

### Application version

Windmill Cloud (EE v1.440.2-2-gcfd93a3ea)

**Comment by HugoCasa** [comment]
Hi @vica-admin 
You can restart the for loop at a specific iteration but not at a specific node (that's why you don't see the restart button in the frontend in that case).
