### ISSUE TITLE
feature: Show absolute dates on Runs

### ISSUE THREAD

**Issue by jaller94** [windmill-labs/windmill#578]
## Use case

When debugging failed runs, I'd like to know at which date and time a specific run took place. The format that I use most naturally is absolute dates (e.g. "What happened on 2022-09-09?")

## Issue
Both the overview and detail page use relative timestamps at decreasing specificity (e.g. "yday at 11:00:01 PM", "17 days ago").

![Screenshot 2022-09-15 at 20-58-38 Runs Windmill](https://user-images.githubusercontent.com/10872136/190487726-ceed3b85-bd26-42db-ac2d-7561cf6eff3e.png)

![Screenshot 2022-09-15 at 21-04-28 Run 01831ee7-086a-9511-3295-69d38ea991fe Windmill](https://user-images.githubusercontent.com/10872136/190488165-4f40a7a1-c625-49b5-8001-f0fd90f14b37.png)

## Proposed solution

Use absolute timestamps like "2022/9/15 at 11:00:00 PM" for all timestamps. This is already used for timestamps in the future, e.g. "Scheduled for 2022/9/15 at 11:00:00 PM".

**Comment by rubenfiszel** [comment]
@jaller94 What about having the absolute timestamp on hover but keep this "human date" ?

**Comment by jaller94** [comment]
For my use case any relative date past "today" and "yesterday" is hard to figure out.

This is for daily downloads where the date is a key variable. e.g. "I want to download the GTFS static archive of 2022-09-09". It took me several tries to find the run of that date.

I'd prefer to have all of them in an absolute format.

**Comment by rubenfiszel** [comment]
Fixed on [6f767ab](https://github.com/windmill-labs/windmill/commit/6f767abec167e4d2f9b58c0ff248b26dddfd1559)

![Screenshot 2022-10-02 at 02-59-50 Runs Windmill](https://user-images.githubusercontent.com/275584/193433570-c04001ec-aa7a-4644-a0c4-49638face1d9.png)
