### ISSUE TITLE
bug: Text inside DefaultButton wraps

### ISSUE THREAD

**Issue by jaller94** [windmill-labs/windmill#579]
## Describe the bug

The text inside buttons wrap, so that depending on the line content and screen width the start of a button appears in a different line than its end.

See "View runs" which is split in half:

![Screenshot 2022-09-15 at 21-07-43 Run 01831ee7-086a-9511-3295-69d38ea991fe Windmill](https://user-images.githubusercontent.com/10872136/190489746-50d59557-e319-44c5-a6bc-79eb4b546f39.png)

## To Reproduce

1. Go to a detail page of a Run, e.g. https://app.windmill.dev/run/01831ee7-086a-9511-3295-69d38ea991fe

## Expected behavior

![Screenshot 2022-09-15 at 21-12-29 Run 01831ee7-086a-9511-3295-69d38ea991fe Windmill](https://user-images.githubusercontent.com/10872136/190489710-0e8bfe3d-7ed5-4b08-b4a2-072bc2ebe422.png)

## Windmill version
v1.35.0-59-g126dd24

## Additional context
The solution could look somewhat like this:

```css
.default-button-secondary {
    white-space: nowrap;
}
```

This may need to be applied to other buttons as well.

**Comment by rubenfiszel** [comment]
Fixed
![Screenshot 2022-10-01 at 23-36-30 Run 018390fd-d089-23a1-5392-b3d5d8263f8a Windmill](https://user-images.githubusercontent.com/275584/193429259-796d3aee-c25a-4c82-aa64-e7de394d6168.png)
