### ISSUE TITLE
bug: Flow input schema: items in `required` are not deduplicated

### ISSUE THREAD

**Issue by jaller94** [windmill-labs/windmill#585]
**Describe the bug**

I've gotten this as a JSON input schema:

```json
{
    "type": "object",
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "required": [
        "room_id",
        "wifi_id",
        "matrix_res",
        "matrix_res"
    ],
    "properties": {
        "room_id": {
            "type": "string",
            "format": "",
            "description": ""
        },
        "wifi_id": {
            "type": "string",
            "format": "",
            "description": ""
        },
        "matrix_res": {
            "type": "object",
            "format": "resource-matrix",
            "description": ""
        }
    }
}
```

Workspace: j94_test
https://app.windmill.dev/flows/get/u/christian/post_openwifimap_links_to_matrix

**To Reproduce** Steps to reproduce the behavior:

1. Create a flow
2. Add a required input as "String -> Resource Path"
3. Edit the input to "Object -> Resource"
4. Save the flow
5. Look at the JSON schema of the flow.

**Expected behavior**

`"matrix_res"` shouldn't be included twice in that array.

**Windmill version**
Latest on app.windmill.dev as of 2022-09-16.

**Comment by rubenfiszel** [comment]
Fixed in 56608f8
