### ISSUE TITLE
fix: Rebalance flow input vs results spacing in flow preview

### ISSUE THREAD

**Issue by lplit** [windmill-labs/windmill#618]
Flow inputs statically take up half the vertical space, which makes the flow results crowded and hard to read through. 

It would be nice to be able to collapse the whole inputs row (keeping the run again button visible), or have it adjust in size dynamically maybe? 

![image](https://user-images.githubusercontent.com/3811272/191760880-945adf5a-475f-4a9f-be8e-30d575fbadb7.png)

**Comment by rubenfiszel** [comment]
Done
