### ISSUE TITLE
Make it explicit in the list of the tokens which one is the one of the current session

### ISSUE THREAD

**Issue by nickers** [windmill-labs/windmill#64]
**Describe the bug** Can not delete token and "undefined" email displayed in user settings

**To Reproduce**:

1. login with default admin account using "login without third party"
2. go to "user settings"
3. change default password
4. click red "delete" in list of tokens
5. Error message is displayed
6. refresh page 
7. "undefined" is shown instead of email address

Am I partially logged out after that? (i am guessing that i am trying to remove token used in current session)

![image](https://user-images.githubusercontent.com/77998/169611975-0966f30d-271b-4c29-b274-a434cde61be9.png)

**Windmill version**: windmill.dev backend v. v1.6.1-4-g02c8bea

**Comment by nickers** [comment]
Checked just now and I don't need to click anything to see "undefined" as email. I is enough to refresh page "user settings".

**Comment by rubenfiszel** [comment]
Thanks for the issue, looking into it today!

**Comment by rubenfiszel** [comment]
@nickers yes you have deleted your current session token. The fix would be to make it more visible on the list of tokens, which one is the current one. I'm editing the title
