### ISSUE TITLE
bugs: variable length limit

### ISSUE THREAD

**Issue by jaller94** [windmill-labs/windmill#654]
![Screenshot 2022-10-01 at 17-01-34 Variables Windmill](https://user-images.githubusercontent.com/10872136/193415639-45cefa1b-ad8f-4345-82f9-fb5d84836ce8.png)

1. The limit is 2999, not 3000. (In the UI. I have not checked the API.)
2. The UI disables the "Add a variable", but doesn't tell you which input field is invalid, so one has to guess that the variable length is the issue.
3. The "hide/show" button overlaps the last characters of a long variable.

P.S. Use this JavaScript to quickly get 3000 characters `a.repeat(3000)`.

**Comment by rubenfiszel** [comment]
Fixed in b9518d7, thanks for the bug report.
![Screenshot 2022-10-01 at 23-31-39 Variables Windmill](https://user-images.githubusercontent.com/275584/193429106-eef8c337-6c44-448f-9b40-21cacedef225.png)
Now show the number of chars dynamically/3000.
