### ISSUE TITLE
bug: Editing a renamed flow with a schedule creates another schedule

### ISSUE THREAD

**Issue by jaller94** [windmill-labs/windmill#781]
### Describe the bug

Whenever I edit a flow, a new, disabled schedule is created.

I think it fails to detect the primary schedule because I renamed the flow.

### To reproduce

1. Create a flow.
2. Create a schedule for the flow.
3. Edit the name of the flow.
4. Point the schedule at the new flow name.
5. Edit the flow.
6. A new schedule gets created automatically.

### Expected behavior

No new, additional schedule gets created.

### Screenshots

1.
![Screenshot_2022-10-20_20-24-16](https://user-images.githubusercontent.com/10872136/197028543-e3923715-b7ab-4c67-8e84-a38fefed56e0.png)

2.
![Screenshot_2022-10-20_20-24-29](https://user-images.githubusercontent.com/10872136/197028565-8acfb031-751a-4c14-97d1-79d68846d111.png)

3.
![Screenshot_2022-10-20_20-24-51](https://user-images.githubusercontent.com/10872136/197028590-5c415b10-cfba-4b1f-8cda-b16e6c8740fe.png)

4.
![Screenshot_2022-10-20_20-25-12](https://user-images.githubusercontent.com/10872136/197028625-c85d4bc0-26bf-4082-a44c-8793eda22cee.png)

### Application version

Running windmill version (backend) v1.39.0-1-g8ec33c5

**Comment by rubenfiszel** [comment]
Fixed in: 4ce3e07

The issue was that we were creating a schedule for any flow changes
