### ISSUE TITLE
bug: Z-Index issue with the Schedules and Resources tables

### ISSUE THREAD

**Issue by jaller94** [windmill-labs/windmill#783]
### Describe the bug

Z-Index issue with the Schedules and Resources tables

### To reproduce

1. Go to https://app.windmill.dev/schedules or https://app.windmill.dev/resources
2. Open the profile menu.

### Expected behavior

The text of the table shouldn't be visible through any popups.

### Screenshots

![Screenshot 2022-10-20 at 20-28-35 Schedules Windmill](https://user-images.githubusercontent.com/10872136/197029636-5a6a1882-c1b4-4e0f-b3ef-40a3d458a7fb.png)

### Browser information

Firefox 106

### Application version

Running windmill version (backend) v1.39.0-1-g8ec33c5

**Comment by rubenfiszel** [comment]
Fixed in: 57ab699
