### ISSUE TITLE
Internal server error when saving script with syntax error

### ISSUE THREAD

**Issue by nickers** [windmill-labs/windmill#8]
**Describe the bug**
Internal server error reported in the browser when saving invalid python script.

**To Reproduce**
1. Scripts -> New script
2. Set valid "name" for the script
3. Click "Next"
4. Modify example python script and make syntax error in it.
5. Click "Save (commit)"

**Current behaviour:**
There will be "Internal server error" reported (see screenshot)

**Expected behaviour:**
Error pointing to script error (second message on the screenshot).

**Screenshots**
![image](https://user-images.githubusercontent.com/77998/167497684-a17ba2e8-e3e5-40e4-ba37-577a7790a719.png)

**Comment by rubenfiszel** [comment]
Fixed by https://github.com/windmill-labs/windmill/commit/02c8bea0840e492c31ccb8ddd1e5ae9676a534b1
