### ISSUE TITLE
bug: connect to workspace doesn't appear as connected for the slack integration

### ISSUE THREAD

**Issue by mrl5** [windmill-labs/windmill#846]
### Describe the bug

connect to workspace doesn't appear as connected for the slack integration

### To reproduce

1. Go to workspace where you're admin
2. Click on "Connect to Slack"
3. Finish the flow of connecting to slack
4. Save the resource
5. Go back to workspace view
6. see the bug: `Status: Not connected`

### Expected behavior

you can see that the slack is connected

### Screenshots

![image](https://user-images.githubusercontent.com/31549762/199293763-08e79da5-71c6-4b73-aa67-c8ef21d522ae.png)

**Comment by rubenfiszel** [comment]
Done in 918fb1f9a448037f172b4d4edbd55f094224863d
