### ISSUE TITLE
bug: errors in some cases when switching between workspaces

### ISSUE THREAD

**Issue by mrl5** [windmill-labs/windmill#847]
### Describe the bug

the issue occurs when user is currently in non-generic aka workspace specific view and chooses to switch to another workspace

## scenario 1
1. go to scripts view
2. select some script
3. switch to another workspace
4. see toast error message about "script not found"

## scenario 2
1. switch to workspace where you're admin
2. go to workspace view
3. switch to another workspace where you're not admin
4. get logged out

the nasty thing about **scenario 2** is that when you log in and select a workspace where you're not admin you're logged out again -- the only way to recover from **scenario 2** is to select a workspace where you're admin, change the view and then switch to another workspace where you're not admin

### Expected behavior

I think while switching between workspaces frontend should modify url to `/` so that user always lands on home view when switching between workspaces

**Comment by rubenfiszel** [comment]
Scenario 2 is solved in 14c296dbb85131c355980cd416c26a88c4823978, scenario 1 is low-prio, some could argue it's expected behavior since you can switch back and forth easily
