### ISSUE TITLE
Commercial license restrictions?

### ISSUE THREAD

**Issue by BojanOro** [windmill-labs/windmill#897]
Hi folks 👋 

I found Windmill today from Hacker News and I'm so far a big fan of the product. I noticed on the pricing page you have "Commercial license for self-hosting" as an enterprise option. Is this implying that if I intend my commercial organization to use Windmill as a stand-alone product for process automation, that I would be required to purchase the enterprise edition? Or does this simply say that if I wish to integrated this into my product I require a commercial license?

Some additional context about the licensing would be appreciated!

**Comment by rubenfiszel** [comment]
Hi!

Sorry for the lack of clarity, I will improve the landing page wrt to those points.

Windmill is AGPLv3 which means that as long as you are comfortable with this license you do not need a commercial license, so to answer your question more directly

>  my commercial organization to use Windmill as a stand-alone product for process automation, that I would be required to purchase the enterprise edition? 

No you do not need to get a commercial license to use it internally and will never need to. However, the enterprise edition benefit from support, large scale deployment tools and more advanced collaboration, ACL and audit logs features.

> Or does this simply say that if I wish to integrated this into my product I require a commercial license?

If your product is not AGPLv3, then in that case you would need indeed need a commercial license to embed Windmill within your product.

**Comment by BojanOro** [comment]
Perfect, thanks for the additional details Ruben 🙏

**Comment by kuklis** [comment]
Can you elaborate on what embed means? Let's say I put Windmill behind ServiceNow and it calls Windmill API. Is this embedding? Or I need to develop a product that includes Windmill source code?

**Comment by kuklis** [comment]
Thanks Ruben. It is hard to draw a line when you develop _on_ a platform like ServiceNow your catalog and call Windmill as an engine to do the heavy lifting.

**Comment by rubenfiszel** [comment]
That's a fine use, it looks like you are a user of windmill and servicenow, and want to have them talk to each other. It would be an issue if you were ServiceNow and were selling as part of your product, workflows that would run on windmill. We are still hoping that you would see sufficiently many benefits to the enterprise edition that you would switch to it but it's not a requirement.

**Comment by razuro** [comment]
What if my commercial product includes a Windmill image and predefined scripts and flows, that:
- my backend API calls to do tasks;
-  Windmill, scripts and flows, were never exposed to or interact by end user;

Do I still need to acquire the commercial license?

**Comment by rubenfiszel** [comment]
Yes, don't include windmill as a component of your product that you sell
without a license from us.

You may however built an integration with windmill and require your
customer to also install separately a full fledged windmill instance.

**Comment by razuro** [comment]
Sorry, but doesn't that contradict with ` For business uses, you should be fine if you do not re-expose Windmill in any way to your users and are comfortable with AGPLv3.` ?

**Comment by rubenfiszel** [comment]
For the same reasons you can't just put a frontend with your name on it and resell Windmill as a software without our permission/license agreement. 

The quote you mentioned is for business that use windmill as part of their internal stack, not businesses that sell software to self-host.

For more details, you can ask our legal counsel at legal@windmill.dev
