### ISSUE TITLE
Cannot delete custom resource after creation (button doesn't work)

### ISSUE THREAD

**Issue by rossmccrann** [windmill-labs/windmill#94]
After creating a custom resource in Windmill I am unable to delete the resource as the button is not functioning. Currently, nothing happens after the button is clicked.

<img width="1083" alt="Screenshot 2022-06-03 at 13 23 34" src="https://user-images.githubusercontent.com/43697404/171914866-d8a41f2d-244a-463a-a312-377fd52de996.png">

**Comment by rubenfiszel** [comment]
Only workspace admins can delete resource types because they have no owners. The only way to make this possible would be to:
- add a created by field to resource type and allow creator to delete the resource type if and only if it is not used by any resources
