### ISSUE TITLE
bug: Windmill logging into undefined user and workspace

### ISSUE THREAD

**Issue by rossmccrann** [windmill-labs/windmill#95]
**Describe the bug** A clear and concise description of what the bug is.
Windmill automatically logging into undefined user and undefined workspace.

**To Reproduce** Steps to reproduce the behavior:

1. Go to '[Windmil](https://docs.windmill.dev/)'
2. Click on Windmill Cloud button'https://app.windmill.dev/user/login'
4. See error in undefined user and workspace

**Expected behavior** A clear and concise description of what you expected to
happen.

Windmill should sign into my user account and default workspace or ask me to select a workspace

**Screenshots** If applicable, add screenshots to help explain your problem.
<img width="161" alt="Screenshot 2022-06-03 at 14 41 02" src="https://user-images.githubusercontent.com/43697404/171926520-0e8d66b3-6c00-4ae1-9ee7-69575dd79dd4.png">
<img width="292" alt="Screenshot 2022-06-03 at 14 41 47" src="https://user-images.githubusercontent.com/43697404/171926631-81d2a07b-e731-40fe-b6c6-b77dbbf3a26a.png">
<img width="1124" alt="Screenshot 2022-06-03 at 14 42 20" src="https://user-images.githubusercontent.com/43697404/171926698-004e4569-cb96-4c9a-b7c4-1e9ba6acd039.png">

**Windmill version** "Running windmill version (backend): v. v1.8.6-36-g0fe276b".

**Additional context** Add any other context about the problem here.

**Comment by rubenfiszel** [comment]
Probably fix in main
